### ISSUE TITLE
Menu text not displaying correctly in latest pre-release.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#103]
As per subject.  

Running 0.5.0-PRERELEASE-20191216112834 results in menu items being displayed as follows:

![cx2](https://user-images.githubusercontent.com/1912425/70941554-9b002680-20b1-11ea-80ff-c4a520b3a108.png)
![cx1](https://user-images.githubusercontent.com/1912425/70941555-9b002680-20b1-11ea-9b0f-f8b7aeee164d.png)

**Comment by mcpierce** [comment]
I noticed that. It was an errant comma in one of the translation files that I thought I had pushed a fix up for. I'll make sure it's done and generate a new build.

**Comment by bareheiny** [comment]
Fixed in latest pre-release.
