### ISSUE TITLE
Unable to install via UNRAID docker

### ISSUE THREAD

**Issue by kingfenix** [comixed/comixed#1095]
Error received during install of docker container from community app store on UNRAID

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='ComiXed' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'PGID'='100' -e 'PUID'='99' -p '7171:7171/tcp' -v '/mnt/user/Comics/':'/library':'rw' -v '/mnt/cache/appdata/comixed/database/':'/root/.comixed':'rw' -v '/mnt/user/Downloads/Complete/':'/incoming':'rw' -v '/mnt/cache/appdata/comixed':'.comixed':'rw' 'comixed/comixed:latest'

Error response from daemon: invalid volume specification: '/mnt/cache/appdata/comixed:.comixed:rw': invalid mount config for type "bind": invalid mount path: '.comixed' mount path must be absolute

The command failed.

**Comment by mcpierce** [comment]
This is a packaged distribution of our docker image, yeah? I thinkt he error might be with one of their arguments being passed to Docker:

```
-v '/mnt/cache/appdata/comixed':'.comixed':'rw'
```

This is passing a relative, not absolute, path, which is the complaint that Docker is raising. You'll want to contact the package maintainer and ask them to fix this issue to resolve the problem.
