### ISSUE TITLE
Issue numbers containing period and letters being dropped off in file names.

### ISSUE THREAD

**Issue by kingfenix** [comixed/comixed#1101]
**Describe The Bug**
When importing issue numbers such as 016.HU and 051.LR the .HU and .LR get dropped in file naming

**To Reproduce The Bug**
1. I imported The Amazing Spider-Man 2018 series which includes multiple issues such as described.
2. using the file naming rule of "$PUBLISHER/$SERIES ($VOLUME)/$SERIES v$VOLUME #$ISSUE ($COVERDATE)", I ended up with issues 016 and 051 with the period and the letters having been dropped in the new file name upon consolidating library.

**Expected Behavior**
I would expect that the full contents of the issue be maintained and nothing be dropped.

**Desktop (please complete the following information):**
 - ComiXed version [from **Help** -> **Build Details**]
 v0.10.5-1.0 [#920]
 MacOS Monteray 
 - Browser name [e.g. chrome, safari]
 Firefox
 - Browser version [e.g. 22]
94.0.1 64-bit

**ComiXed Build Detail:**
Build Details
The code was build from a branch named ebf2aa04d07485fac36af2c4a0c3da5bcd7aa16c
The code was built on October 26, 2021 at 12:15:26 AM GMT-4.
Code was built on a machine named fv-az209-571.
The code was marked with a Build version of 0.10.5-1.0.
The latest commit hash on the source branch is ebf2aa04d07485fac36af2c4a0c3da5bcd7aa16c.
This commit was created on October 26, 2021 at 11:47:41 AM GMT-4.
Commit Message
Changed the release version to v0.10.5-1.0 [#920]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed;create=true

**Comment by mcpierce** [comment]
@kingfenix I wasn't able to reproduce this locally.

On the release branch, I scraped a comic as The Amazing Spider-Man v2016 016.HU and then consolidated my library using the rules described. The final comic filename was:

```
The Amazing Spider-Man #16.HU (Apr 2019).cbz
```

Did you scrape the comic using ComiXed or did you import it and then consolidate your library? Can you post a screeenshot of the **Details** tab for the issue in question, showing what publisher, series name and issue number is displayed there?

**Comment by kingfenix** [comment]
I had imported and consolidated, I was unable to scrape them due to the import block problem, I will try again today and let you know if the problem happens again now that I am past that.

**Comment by kingfenix** [comment]
I am liking this new build you have shared with me, about the only thing missing to get me to really get on board is the reorder thing to fix covers to show, drives me crazy seeing a normal page rather than a cover when its there to be seen, lol

also I would suggest a new "home" page other than statistics and maybe just put a link to stats down by the build link. how about a "Home" page that gives a sort of plex view, like a row by most recently added and other rows sorted other ways?

That or a home page just sorting or grouped by publisher/series or series/Alphabetical idk

________________________________

**Comment by kingfenix** [comment]
just went to scrap a comic in the new build, and when I select correct comic from the list, the cover box that pops up is too low and I cant see the buttons to say yes this is the right one, and it wont let me scroll down anymore

do you want me to let you know of things I am running into on this new build?

________________________________

**Comment by kingfenix** [comment]
this new build also still has the coverdate issue....CV shows for example Nov 2018 in store, Dec 2018 Cover Date, and Comixed puts Jan 2019 on my filename even though comixed itself shows the correct date on the details...check this pic, shows comixed has the right date, but the filename gets plus 1 month apparently...



________________________________

**Comment by mcpierce** [comment]
> I had imported and consolidated, I was unable to scrape them due to the import block problem, I will try again today and let you know if the problem happens again now that I am past that.

Okay, I'm guessing then that the filename scraping didn't get the full issue number since I think it's only looking for numeric characters. So it's not a consolidation issue, it's a filename scraping issue.

**Comment by mcpierce** [comment]
> > I had imported and consolidated, I was unable to scrape them due to the import block problem, I will try again today and let you know if the problem happens again now that I am past that.
> 
> Okay, I'm guessing then that the filename scraping didn't get the full issue number since I think it's only looking for numeric characters. So it's not a consolidation issue, it's a filename scraping issue.

The buttons to pick the issue when scraping are in the table now, not under the cover image. You click there to select the issue that matches.

Regarding any bugs or issues you see in this build, please share those on the mailing list only. I prefer bugs to be only opened against proper releases.

**Comment by kingfenix** [comment]
you need to setup a discord channel so we could just chat live

________________________________

**Comment by kingfenix** [comment]
ok, the .LR and .HU issue numbering is working correctly for me now in the .11 build, I will assume that was a side affect of partial import, and you can close that ticket.

the only two issues I have with the .11 SNAPSHOT build....these are both OCD issues and not major functional problems.


  1.  Allow me to fix cover page ordering
  2.  The Cover Date seems to have two issues
     *   Sometimes Comixed has the correct cover date listed in details, meaning it matches CV, and other times it does not
     *   Regardless of letter (a) the file naming is always wrong when using the $COVERDATE variable.

Other than these two items all seems to be correct, although I may have suggestions :)

Thanks,
Doug

________________________________

**Comment by kingfenix** [comment]
This issue seems to just be due to the partial import bug which you have fixed, closing ticket, thanks for your work and attention.

**Comment by mcpierce** [comment]
On Tue, Nov 16, 2021 at 3:03 PM kingfenix ***@***.***> wrote:
> you need to setup a discord channel so we could just chat live

We have a Slack server, but there's not much traction there. I think
too many communication venues might spread the message too thin.
That's why I figured a mailing list is the easiest thing to do to
build a community. We had a FB group but I didn't want to put a lot of
requirements on people (beyond an email address) to get invovled.

Once it gets enough traction, I would love to see users engage in more
diverse discussions in a forum of some sort.

-- 
Darryl L. Pierce ***@***.***>
"Le centre du monde est partout." - Blaise Pascal
"Let's try and find some point of transcendence and leap together." -
Gord Downie
