### ISSUE TITLE
Allow users to create, maintain and share a list of blocked pages - with the reason for blocking.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#112]
As a user, I would like to be able to create, maintain and share a list of blocked page hashs, as well as the reason for blocking them.

This would be an expansion of the existing blocked page table - but would allow a user to import a list of blocked page hashes, review the reason for blocking and then chose to apply the blocks.

As part of this, a user would also be able to export their blocked list - sharing it with other CX users to enhance their own block list.

For a use case, I just need to look at the ~18k distinct duplicated pages - being able to wittle that down to a lower number by excluding pre-identified ads or scanner tags would help with review of duplication etc.

Recording the reason for blocking would help users easily identify which blocks should be applied- for example I may choose to block all adds, but leave scanner tags and memorial pages etc.

**Comment by mcpierce** [comment]
@bareheiny Great idea! I definitely like the idea of being able to share things like blocked page lists. That way you don't have to import and find them for yourself.

**Comment by bareheiny** [comment]
Even a stopped clock is right twice a day ;)

I'm currently isolating, reviewing and sorting the duplicated pages from my collection - so I can build a prototype list.

Although I think you'd need to put a bit of thought into how the data may be structured.  I was thinking a simple CSV with the hash and a text reason for the block.

There won't be any rush though...it's going to take me a while to sort through the files and then I'll be keeping relevant records anyways.

**Comment by mcpierce** [comment]
@bareheiny I think CSV's a good generic format to use and can be viewed and edited outside of the app without needing any special apps.

**Comment by bareheiny** [comment]
Looking into this more now (easier with a smaller set of comics) - can the BLOCKED_PAGE_HASHES be updated to include a "reason for block" field?

I think a CSV for import would look something like this:

HASH,BLOCKREASON
0D1E82138DFD0CF3ACD006E7D466DE4C,Scanner tag
0DE4FBE11FF2E2C9AC92F4ADD2F1103F,Scanner tag
1A1F56E68422AC9B4783CEDF8EA95147,Scanner tag
1BA3901C4328BFB5EEAF4AD7412A6BF2,Scanner tag

A process for CX to import the data could check that the first field is a hash (appropriate length and alphanumeric), and the same sort of alphanumeric check could be run on the block reason....or even a set of static block reasons could be defined, and any records that don't pass either test simply aren't imported.

Could be over-complicating it there though....maybe the hash and reason are enough, and a user should be responsible for reviewing the list prior to importing it.



**edit:**  of course, the block page would also need to be updated to allow users to record the reason for blocking, and there would need to be a way to export the list...

**Comment by mcpierce** [comment]
Sure, that's a good idea.

**Comment by bareheiny** [comment]
And the page format would been needed - the same page in jpg and webp would produce different hashes.

**Comment by mcpierce** [comment]
@bareheiny I'm going to pull this in 0.9 since it dovetails perfectly with the changes made in #154. With this ticket I'm going to add the downloading and uploading aspect of your request  to have a more complete feature set. 😄

**Comment by mcpierce** [comment]
@bareheiny I think we have a well-rounded feature set for the next release now. You'll be able to block/unblock pages, view the list of pages, download the list, upload a list that merges with your existing list, and delete entries from the list page.
