### ISSUE TITLE
Reading lists can be exported.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#113]
As a user, I would like to be able to create, maintain and share a reading list.

This would be an expansion of the reading list table - but would allow a user to import or export new lists.

It would be important for the reading list to include the reading order - especially if one were to create a list of comics involved in a particular story-arc (such as the ones Marvel are partial too....a main series, with a bunch of other comics around the edges).

I'm thinking this will be a bit more complex than it would seem - as it is entirely likely that a user may attempt to import a reading list that contains comics that are not in their library.

Can't take credit for this one - it popped up in the CR reddit thread, where a user asked aout other applications that could read / use CR reading lists).  Not sure if CX can do that (yet), but I pointed them at CX anyway.

**Comment by mcpierce** [comment]
Sharing reading lists would require a rethinking of how we build them since, right now, reading list entries are mapped by the record id for each comic in the list. We'd have to come up with a way to universally uniquely identify comics in order to put them into a shareable list.

**Comment by bareheiny** [comment]
My first thought was ComicVine id. 

But that may not always be available - especially in a list that contains unscrapped comics.

**Comment by mcpierce** [comment]
It's possible we could use some set of elements on the comic that makes it unique, such as series-volume-issue-number to create a synthetic id.

**Comment by mcpierce** [comment]
@bareheiny Trying to put a bow on the reading list features for the next release, how about we go with the final suggestion above; i.e., a reading list is composed of a name, a description, and a set of publisher/series/volume/issue-number values for the issues in the reading list?

**Comment by bareheiny** [comment]
Sorry, been busy with life.

Your suggestion sounds good as a starting point :)
