### ISSUE TITLE
Frequent "Whitelabel Error Page"

### ISSUE THREAD

**Issue by Bazzu85** [comixed/comixed#1209]
**Describe The Bug**
When navigating this error occurs often

**To Reproduce The Bug**
I simply Navigate and face the error. To fix I need to manually return to ip:7171

**Expected Behavior**
no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/7345587/161029183-f69a48a7-262f-4da4-82e6-1d00b83c4e1c.png)

**Desktop (please complete the following information):**
 - ComiXed version: 1.0.0-1
 - OS: Windows 10 pro
 - Browser name: Chrome
 - Browser version: 99.0.4844.82 

**ComiXed Build Detail:**
Build Details
The code was build from a branch named 4677bbd776bc7d6d8d5df5de9862aa164774d548
The code was built on March 27, 2022 at 1:10:23 PM GMT+2.
Code was built on a machine named fv-az133-973.
The code was marked with a Build version of 1.0.0-1.
The latest commit hash on the source branch is 4677bbd776bc7d6d8d5df5de9862aa164774d548.
This commit was created on March 27, 2022 at 1:04:30 PM GMT+2.
Commit Message
Changed the release version to 1.0.0-1 [#1178]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed;create=true
**Additional Context**

**Comment by mcpierce** [comment]
Can you share a few details with me:
1. What do you mean when you say "navigate"? Are you clicking on some part of the application? If so, what thing(s)?
1. How are you running ComiXed? Is it in a Docker container, or are you running it from the command line?
1. If you're running the application from the command line, do you see any errors in the output? (you can ignore anything that says something like "A job instance already exists and is complete for parameters={run.id=1}.")
1. When you say you need to "return to ip:7171" is the URL changed by clicking on something? Does it move away from the app?

**Comment by mcpierce** [comment]
@Bazzu85 I believe this bug report was duplicated in #1223 which is fixed on master and will get released tomorrow. Can you please, once that version (v1.0.2-1) is released, verify that it's fixed? And, if it is, please close this ticket.

**Comment by Bazzu85** [comment]
Hi, testing right now. Thx
