### ISSUE TITLE
Consolidation removes the file extension

### ISSUE THREAD

**Issue by iguyking** [comixed/comixed#1219]
**Describe The Bug**

When consolidating, the filename extension is not included in the post consolidation move.   As such after consolidation, the comic no longer loads the image.  

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Using Docker image on Windows, release version 0.11.1-1.0
1. Put a CBZ file into the /library/incoming directory tree 
1. Go to Hamburger menu, Comics, Import Comics
1. Put in the search field "/library/incoming"
1. Hit search
1. Select the comic and then click on the import button
1. Go to the All comics after processing is complete and hit "Consolidation button".  
1. See error of files not having CBZ as an extension in the /library directory.   

**Expected Behavior**
When consolidating, the full file is just moved and possibly renamed keeping the extension that it started with. 

**Desktop (please complete the following information):**
 - ComiXed version 0.11.1-1.0
 - OS:  Docker/Windows
 - Browser name: Chrome
 - Browser version: 100.0.4896.60

**ComiXed Build Detail:**
The code was build from a branch named 6061ea4ca16f37551619e91622bcba79bf8222ec
The code was built on March 12, 2022 at 11:41:44 AM GMT-6.
Code was built on a machine named fv-az177-56.
The code was marked with a Build version of 0.11.1-1.0.
The latest commit hash on the source branch is 6061ea4ca16f37551619e91622bcba79bf8222ec.
This commit was created on March 12, 2022 at 11:28:35 AM GMT-6.
Commit Message
Changed the release version to v0.11.1-1.0 [#1117]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed;create=true

**Additional Context**

**Comment by mcpierce** [comment]
@iguyking Thank you for reporting this issue. We have a new release (1.0.0-2) that's going to be available today. Can I ask that you verify that this issue still exists in that release and respond to this ticket with the result?

**Comment by iguyking** [comment]
1.0.0-2 did fix this specific issue.
