### ISSUE TITLE
OPDS Protocol Implementation Issue(s)

### ISSUE THREAD

**Issue by swallace17** [comixed/comixed#1226]
Hello,

Filing a bug report for an issue I discovered while testing ComiXed with the [Panels' iOS comic reader application](https://panels.app/). In short, I was able to use Panels to connect to ComiXed's OPDS server, and the connection was successful. Though the connection was successful, however, no comics were actually presented. 

I tested ComiXed with other reader apps, and the OPDS server seemed to work fine, so I initially thought this may be strictly an issue with Panels. I created a [bug report thread](https://community.produktstudio.com/t/comixed-opds-feed-displays-empty-inside-panels/1384) on their forum, and one of the  developers did some investigation. 

Their findings can be found [here](https://community.produktstudio.com/t/comixed-opds-feed-displays-empty-inside-panels/1384/4?u=samuel_wallace). I'm not overly familiar with the OPDS protocol to be able offer a strong technical outline of the issue, but the linked post should be helpful. Furthermore, the developer(s) have offered to collaborate on getting a fix implemented. 

I'll be posting a link to this issue back on that thread. Happy to test further, or provide any additional information as I can. Thanks!

**Comment by mcpierce** [comment]
@swallace17 I believe some of the issues are fixed in #1225, which is under review to be merged. In that PR the developer has addressed the start/subsection issue, and I believe has also fixed the thumbnail issue. Regarding the unique identifiers, we'll open a new bug to address that as well, separately.

Thank you for bringing this to our attention. And I appreciate that the Panels team was so specific in identifying issues for us.

**Comment by swallace17** [comment]
@mcpierce Awesome, glad to hear it. Thanks!

**Comment by mcpierce** [comment]
@swallace17 I've opened #1226 to address the issue with the comic IDs changing.

**Comment by fillito** [comment]
Thanks, folks! 🙌  outstanding work

**Comment by mcpierce** [comment]
@swallace17 The fixes are merged into master and will be in our next release (1.0.1-1). I'd like to fix one other issue and put that release out this coming weekend. 

If this bug is fixed with it, please feel free to close this issue as resolved.

**Comment by mcpierce** [comment]
Adding a note that this report duplicates bugs reported in #1217 and #1227.

**Comment by mcpierce** [comment]
@swallace17 There's a [new release](https://github.com/comixed/comixed/releases/tag/v1.0.1-1) available now with the fixes for OPDS. Please give this a try and, if things are better, you can close this ticket.

**Comment by mcpierce** [comment]
@swallace17 I'm going to go ahead and close this as fixed. Please feel free to reply if the issue persists.
