### ISSUE TITLE
Scraping for titles with "/" in the title provides bad results.

### ISSUE THREAD

**Issue by zourn** [comixed/comixed#1235]
Scraping for titles with "/" in the title (ie- "Batman/Superman" or "Batman/Catwoman") provides much less relevant results than replacing the "/" with a space. Specifically using ComicVine, haven't tested any other scrapers.
I think it would be good to filter this field to convert "/" (and maybe "\") to a space to provide better scraping results

**Comment by mcpierce** [comment]
@zourn Provides "much less" or "bad results"? Those are two different sets of data; i.e., the latter means wrong results, while the former just means fewer records returned but not necessarily wrong.

**Comment by zourn** [comment]
I just and did a test, and for "Batman/Catwoman" the correct result was not in the 100 returned results, and by changing the title to "Batman Catwoman" the correct result was 4th in the list. The correct title is "Batman/Catwoman" as scraped from ComicVine. I don't know if this is some quirk with the comicvine's api call or what.

**Comment by zourn** [comment]
Similar results with "Batman/Superman". Scraping with title as-is does return 100 results, but none of them a correct match. Changing the title for "Batman Superman" gives the correct match within the top 10 results.

**Comment by mcpierce** [comment]
Okay, I'll get a fix in place for the next release, which should be this weekend (24 April). 

Thanks for reporting this to us.

**Comment by mcpierce** [comment]
@zourn I tried URL encoding the series name in my call to ComicVine, producing this URL:

```https://comicvine.gamespot.com/api/search/?api_key=*****&format=json&filter=name:Batman%252FSuperman&query=Batman%252FSuperman&limit=100&resources=volume&field_list=id,name,count_of_issues,publisher,start_year,image```

And it still doesn't seem to return any series named "Batman/Superman". However, there doesn't appear to *be* a series with that name. There's a series named ["Superman/Batman"](https://comicvine.gamespot.com/supermanbatman/4050-10938/) that comes up when I search it. 

Are you sure that's the correct series name? Can you find the series you're trying to scrape in ComicVine and post the link to it here? I can work backwards from such a link if I have it.

**Comment by zourn** [comment]
There is two different volumes of Batman/Superman. 
[Volume 1](https://comicvine.gamespot.com/batmansuperman/4050-64203/)
[Volume 2](https://comicvine.gamespot.com/batmansuperman/4050-120912/)

When searching these I noticed that your call had "%252F" where the slashes should go, which I assume should be " /"  (space, slash) replacements. When changing that to either a "%25%2F" or even just "%2F" the correct results seemed much better.

You can see that by checking this call: 
`https://comicvine.gamespot.com/api/search/?api_key=*******&format=json&filter=name:Batman%2FSuperman&query=Batman%2FSuperman&limit=100&resources=volume&field_list=id,name,count_of_issues,publisher,start_year,image`

**Comment by mcpierce** [comment]
@zourn Very strange, but it seems this wasn't a problem with the / in the name. Instead, I think this issue surfaced a different bug around fetching an unlimited number of records. There was a bug where, when the limit was set to unlimited, it was stopped after only 100 records. So the entry "Batman/Superman" showed up towards the end of the result set that didn't get loaded, which is why you didn't see it.

After fixing that issue, I see Batman/Superman v2013 and v2019 now as desired. So I'll go ahead and push this fix up and we'll get a bugfix release out once it's merged.

Thank you for finding this! :smile:

**Comment by zourn** [comment]
Am I wrong in thinking that the incorrectly encoded slash in the call URL is also an issue?
Or was that URL one you did by hand and not as built from the program?

**Comment by mcpierce** [comment]
@zourn That was added as part of my initial attempt to fox the bug. I hadn't realized the series name was being url encoded in the call to CV, so the encoding got encoded a second time.

**Comment by mcpierce** [comment]
@zourn This has now been merged into master. We'll release a build on Saturday that includes this fix. After that's out, please confirm the bug is fixed and, if so, you can close this ticket as fixed.

**Comment by zourn** [comment]
Just checked this with the 1.0.2-1 update, the bug persists. Scraping for a title with a "/" in the name returns results that are not good matches. 
Looking at it closer, I scraped a title called "Batman/Catwoman" and the first page of results were exactly the same as and in the same order as the api call posted earlier with the "/" encoded with 2F instead of %2F.

This is the api call that produces the same results as the program, there is one single volume of Batman/Catwoman as the 100th result, but it is the wrong volume. 
`https://comicvine.gamespot.com/api/search/?api_key=******&format=json&filter=name:Batman%252FCatwoman&query=Batman%252FCatwoman&limit=100&resources=volume&field_list=id,name,count_of_issues,publisher,start_year,image`

Searching with this api call gave 8 different volumes of Batman/Catwoman as the first 8 results.
`https://comicvine.gamespot.com/api/search/?api_key=******&format=json&filter=name:Batman%25%2FCatwoman&query=Batman%25%2FCatwoman&limit=100&resources=volume&field_list=id,name,count_of_issues,publisher,start_year,image`

**Comment by mcpierce** [comment]
@zourn Sorry, I forgot to mention previously that you should skip the cache when scraping for the first run with this new build. By default, CX is going to look into your cached metadata (which was loaded with the bad code) before going to CV to look for data (which would use the new code). By skipping the cache for the first scrape on the issue, it'll replace that old data.

Using 1.0.2-1, I got the following URL when I searched with the following the following fields:
|Field|Value|
|-----|-----|
|Publisher|DC Comics|
|Series|Batman/Catwoman|
|Volume|2020|
|Issue|1|

I got back the following candidates:
<img width="982" alt="Screen Shot 2022-04-24 at 9 50 18 AM" src="https://user-images.githubusercontent.com/61601/164979714-342ee53a-0615-45d8-b024-31be2995e15e.png">

And CX used this URL:
```
https://comicvine.gamespot.com/api/search/?api_key=*****&format=json&filter=name:Batman%2FCatwoman&query=Batman%2FCatwoman&limit=100&resources=volume&page=7&field_list=id,name,count_of_issues,publisher,start_year,image
```

**Comment by zourn** [comment]
Ah yes, I did not notice the caching. That's my bad, I've only just started toying around with this software. It looks to be working as intended with v1.0.2-1 and using an uncached search.

Thank you.
