### ISSUE TITLE
Fatal error while importing in Docker

### ISSUE THREAD

**Issue by unfinishedh** [comixed/comixed#1243]
Hello. After installing the latest image as a container following the wiki for docker, comixed is unable to import any comicbook files. According to the logs, Java encounters a fatal error and comixed crashes. Logs are attached below.

The files are CBZ with WebP images inside. Confirmed that the standalone version from GitHub, they are imported without issues.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Set up a new comixed container following the wiki.
1. Load and select a file on the import tab.
1. Click start importing.
1. Comixed will show the import page, but it will never finish as it crashes.

**Desktop (please complete the following information):**
Host OS: Arch Linux amd64
Docker version: 20.10.14
Comixed version: comixed/comixed:latest (1.0.2-1)  

**ComiXed Build Detail:**
The code was build from a branch named a4ac0d64c684867b7a5a14ef69fb9b714be2fa15
The code was built on April 23, 2022 at 8:12:34 AM GMT+7.
Code was built on a machine named fv-az241-128.
The code was marked with a Build version of 1.0.2-1.
The latest commit hash on the source branch is a4ac0d64c684867b7a5a14ef69fb9b714be2fa15.
This commit was created on April 23, 2022 at 7:31:51 AM GMT+7.
Commit Message
Changed the release version to 1.0.2-1 [#1178]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed;create=true 

**Additional Context**
[comixed.log](https://github.com/comixed/comixed/files/8547010/comixed.log)
[docker_logs.txt](https://github.com/comixed/comixed/files/8547338/docker_logs.txt)
[hs_err_pid12.log](https://github.com/comixed/comixed/files/8547331/hs_err_pid12.log)

I believe this is the relevant part of the log:

```
2022-04-23 13:13:38.424 ERROR 12 --- [     CX-Jarvis3] o.c.adaptors.file.FileTypeAdaptor        : No loader found for type: octet-stream

#

# A fatal error has been detected by the Java Runtime Environment:

#

#  SIGSEGV (0xb) at pc=0x000000000000b8e6, pid=12, tid=92

#

# JRE version: OpenJDK Runtime Environment (11.0.14+9) (build 11.0.14+9-alpine-r0)

# Java VM: OpenJDK 64-Bit Server VM (11.0.14+9-alpine-r0, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)


# Problematic frame:

# C  0x000000000000b8e6

#

# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /app/core.12)

#

# An error report file with more information is saved as:

# /app/hs_err_pid12.log

#

# If you would like to submit a bug report, please visit:

#   https://gitlab.alpinelinux.org/alpine/aports/issues

# The crash happened outside the Java Virtual Machine in native code.

# See problematic frame for where to report the bug.

#

/app/comixed-release-1.0.2-1/bin/run.sh: line 126:    12 Aborted                 (core dumped) $JAVA ${JVMOPTIONS} "${CLASSPATH}" -jar "${COMIXED_JAR_FILE}" ${JAROPTIONS}
```

**Comment by mcpierce** [comment]
@unfinishedh Thanks for bringing this to our attention. I took a look at the logs you provided, thank you for those. I believe the situation is due to a bug in one of the pieces we depend on, [org.sejda.imageio:webp-imageio](https://github.com/sejda-pdf/webp-imageio).

I see the following in the hs_err_pid12.log:

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.luciad.imageio.webp.WebP.decode(J[BII[IZ)[I+0
j  com.luciad.imageio.webp.WebP.decode(Lcom/luciad/imageio/webp/WebPDecoderOptions;[BII[I)[I+64
j  com.luciad.imageio.webp.WebPReader.read(ILjavax/imageio/ImageReadParam;)Ljava/awt/image/BufferedImage;+53
j  javax.imageio.ImageIO.read(Ljavax/imageio/stream/ImageInputStream;)Ljava/awt/image/BufferedImage;+55 java.desktop@11.0.14
j  javax.imageio.ImageIO.read(Ljava/io/InputStream;)Ljava/awt/image/BufferedImage;+34 java.desktop@11.0.14
j  org.comixedproject.adaptors.content.ImageContentAdaptor.loadContent(Lorg/comixedproject/model/comicbooks/Comic;Ljava/lang/String;[B)V+50
j  org.comixedproject.adaptors.comicbooks.ComicBookAdaptor.load(Lorg/comixedproject/model/comicbooks/Comic;)V+166
j  org.comixedproject.batch.comicbooks.processors.LoadFileContentsProcessor.process(Lorg/comixedproject/model/comicbooks/Comic;)Lorg/comixedproject/model/comicbooks/Comic;+19
j  org.comixedproject.batch.comicbooks.processors.LoadFileContentsProcessor.process(Ljava/lang/Object;)Ljava/lang/Object;+5
```

I've opened [a bug](https://github.com/sejda-pdf/webp-imageio/issues/29) with them. Please take a look and see if they need any other details that you could provide.

I'm going to close this ticket as invalid since it's outside of our codebase, but will keep an eye so we can update when they release an update. Sorry we couldn't give you a better answer.

**Comment by mcpierce** [comment]
@unfinishedh I got a response back from the maintainer for webp-imageio, where they said:

    Most likely because the container is running on Alpine, which uses musl instead of libc.
    
    The included binary in this lib is only compiled for libc, not musl.
    
    Switching to a Ubuntu or Debian base image should work.

I'm going to look into whether we can swap out alpine for another base OS in our Docker image to see if that fixes the problem.

(edit)

I've attached a modified Dockerfile to this comment. Can you try building a container from it and seeing if it works in your environment, please?

[Dockerfile.txt](https://github.com/comixed/comixed/files/8935983/Dockerfile.txt)
