### ISSUE TITLE
An OPDS feed shows unread comics by store date

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#1271]
As a reader I would like to view unread comics grouped by the date they were released.

**Comment by grimlokason** [comment]
Hello,

Just started to look into comixed last week and was checking how to get that.

Nice feature ! :D

**Comment by mcpierce** [comment]
@grimlokason I'm planning to have this feature is our next feature release at the end of June. There's also a related feature to try and have an OPDS reader be able to update the read state of a comic, but may not make it into that release.
