### ISSUE TITLE
When scraping an comic with an issue number of 0, no data is retrieved

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#130]
**Describe the bug**
When scraping a comic, and it's issue number is 0, then scraping results consistent come back empty even though the comic exists in ComicVine.

**To Reproduce**
1. Begin scraping a comic.
1. Enter "0" for the issue number.
1. Fetch the volumes for the comic.
1. Select the correct volume from the list returned.
1. No comic is displayed.

**Expected behavior**
1. The comic should be displayed since it exists.

**Additional context**
The scraping URL generated is missing the issue number:
```
http://comicvine.gamespot.com/api/issues/?api_key=[SNIPPED]&format=json&filter=volume:43019,issue_number:&field_list=cover_date,description,id,image,issue_number,name,store_date,volume
```

**Comment by bareheiny** [comment]
Will this happen for other non-standard issue numbers as well?

0.5, -1 etc.?

**Comment by mcpierce** [comment]
@bareheiny No. It was code that removes leading "0" from issue numbers not stopping when it was a single "0". ;)
