### ISSUE TITLE
Initial import gets stucks, blocks other operations.

### ISSUE THREAD

**Issue by mugenstylus1** [comixed/comixed#1313]
**Describe The Bug**
I expected to be able to login after a restart. 

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Import comics (80)
2. let the comics import, import hung for 3 hours.
3. restart container.
4. can not log in.

**Expected Behavior**
that the comics would import and then i could scrape them.

**Screenshots**

**Desktop (please complete the following information):**
 - ComiXed version: latest docker
 - OS: unraid 6.9.2
 - Browser name firefox
 - Browser version: Gecko/20100101 Firefox/101.0 

**ComiXed Build Detail:**
can't access them now page wont load. 

**Additional Context**
[https://drive.google.com/drive/folders/10IjX0AAsoSCgds5IDCEyrlqMi_WUK8zy?usp=sharing](logs)

I having an error after restart that wont let me log in. 
I included the logs. I was importing 80 books, they were all in the unprocessed mode i left it for about 3 hours no change 
i restarted and refreshed the page. I now can not log in. 

[https://drive.google.com/drive/folders/10IjX0AAsoSCgds5IDCEyrlqMi_WUK8zy?usp=sharing](logs)

**Comment by mcpierce** [comment]
> I having an error after restart that wont let me log in. 
> 
> I included the logs. I was importing 80 books, they were all in the unprocessed mode i left it for about 3 hours no change 
> 
> i restarted and refreshed the page. I now can not log in. 
> 
> 
> 
> [https://drive.google.com/drive/folders/10IjX0AAsoSCgds5IDCEyrlqMi_WUK8zy?usp=sharing](logs)

Please copy into the bug report above the template we ask users to fill in so I can look into things properly.

**Comment by mugenstylus1** [comment]
i will also note, that i made a backup of my database, and started fresh. My guess it could be a corrupted database.

**Comment by mcpierce** [comment]
I'm seeing something similar as well on a test service. I'll start looking into this and see about getting a fix.

**Comment by mcpierce** [comment]
@mugenstylus1 I think this one is definitely a resource issue, and I have a fix in place for it that I'm testing now. Long story short, the batch process was trying to load the list of **all** comics to be processed at each stage, and if you threw a few thousand comics at it, it was loading them all into memory at once and then processing them in batches. I changed the loader to only grab one batch's worth (10 comics) and to go back to the database after each batch was processed. It seems a lot more stable now.
