### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by mugenstylus1** [comixed/comixed#1314]
**Is your feature request related to a problem? Please describe.**
Yes, I think my db was corrupted i did have to start from scratch. 

**Describe the solution you'd like**
An option to schedule or manually make a back up of the database. 

**Describe alternatives you've considered**
creating a cron job to back it up automatically daily. 

**Additional context**
N/A

**Comment by mcpierce** [comment]
I don't think creating a cron job or backing up the database is something that the project itself can do. That's more of a best practice for the library owner to take on. The default embedded DB creates external files in the user's home directory, which they can periodically backup without CX.

**Comment by mugenstylus1** [comment]
Currently for Database back up I set up a script
```
#!/bin/bash

cp /mnt/user/appdata/comixed/database/comixed.mv.db /mnt/user/appdata/comixed/database/comixed.mv.bak`date +"%Y_%m_%d"`
```

I run it daily
