### ISSUE TITLE
Skip Meta Scraping, if needing to start from scratch. 

### ISSUE THREAD

**Issue by mugenstylus1** [comixed/comixed#1315]
**Is your feature request related to a problem? Please describe.**
My database was recently corrupted and i had to start fresh. I imported all the books that were scrapped before. (about 600). Even though they have been meta scraped they still count as unscraped.  

**Describe the solution you'd like**
If the Scraping Notes has "Comic metadata scraped using ComiXed & ComiXed ComicVine Scraper." doesn't need to be scrapped again, or option to skip scraping on selected books. 

**Describe alternatives you've considered**
Just re-scraping the books to clear them or just ignore them. 

**Additional context**
This could be really helpful if someone needed to restart their database again.

**Comment by mcpierce** [comment]
I definitely like this idea. I think we could easily accomplish this by adding the metadata source and id to the ComicInfo.xml file. Then, if we see them, we set those values on the comic, which is how the system knows if the comic has been previously scraped or not.

**Comment by mugenstylus1** [comment]
I was just about to come here and suggest that. To use the Metadata Source and Id. 
-I noticed that the metadata source id option is locked when scraping am i missing an option to unlock it, encase there is trouble with a match?

**Comment by mcpierce** [comment]
It's a display-only field to show what the source ID was assigned during a lookup .

**Comment by mugenstylus1** [comment]
ah got it.
