### ISSUE TITLE
Metadata Source doesn't always load when scraping data. 

### ISSUE THREAD

**Issue by mugenstylus1** [comixed/comixed#1320]
**Describe The Bug**
When going to scrape metadata for comics, the metadata scraper doesn't always load.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1.  Select comics to scrape data.
2.  Metadata Source doesn't always load.
3.  Go to configuration -> Metadata Sources -> edit -> Save.
4.  Return to scraping comics Metadata Source Loads. 

**Expected Behavior**
Metadata Source to load when scraping comics. 

**Screenshots**

**Desktop (please complete the following information):**
 - ComiXed version: 1.0.3-1. 
 - OS: Unraid 9.6.2
 - Browser name Mozilla/5.0 
 - Browser version (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0 

**ComiXed Build Detail:**
[Screen 1](https://drive.google.com/open?id=1AcceNJxyYFii0hkHOtjBTHJN9xzcIXwe&authuser=eric%40mugenstylus.com&usp=drive_fs)
[Screen 2](https://drive.google.com/open?id=1AaZJo_rNbYGYnedsEUYV5H-23hta7DgH&authuser=eric%40mugenstylus.com&usp=drive_fs)

**Additional Context**
[logs](https://drive.google.com/open?id=18hzrJnWRMbEklDRmKl9SJIl5dIJAZXx_&authuser=eric%40mugenstylus.com&usp=drive_fs)

**Comment by mcpierce** [comment]
@mugenstylus1 If I'm reading this correctly, then this is expected behavior. If the comic has not been scraped previously, then the app doesn't show one of the metadata sources since one hadn't previously been use. So it preselects the empty entry.

There's a ticket (#1149) is open to mark one of the sources as preferred. In that case, if no scraper has been used for a comic, then the preferred one will get preselected.

Does that address the issue you're seeing? If so, please feel free to close this ticket. If no, could you add a little more detail to describe the situation?

**Comment by mugenstylus1** [comment]
Unfortunately that does not address it. Comicvine doesn't load as a metadata source and I can not select it unless i go to configuration first and save the meta source again.

**Comment by mcpierce** [comment]
Ah, okay, I understand now. So you don't see *any* sources when trying to scrape unless you first go into the configuration first? Is that only for multi-comic scraping? If you go to a single comic's details page and try to scrape it, does it have the list in that case? Do a reload on the browser before going to the details page, please.

**Comment by mugenstylus1** [comment]
If I go to a single comics details page I can scrape with no issues. Seams to happen when scraping a single comic or multiple from the Unscraped page. I have tried on a reload of the page doesn't show up. Will show up only after configuration.

**Comment by mcpierce** [comment]
@mugenstylus1 I started working on this and am unable to recreate the issue. When I login, select comics, and go to scrape them all, the metadata sources are loaded and present. I double-checked in the code to verify that the scraping component in the browser is fetching the list of sources when it's loaded.

I don't think the issue is on the server side, but something is happening in your browser. Please do this:

1. Open the Developer Tools for your browser (usually it's the **Inspect** menu item from the browser page).
1. Select the comics to do a multi-scrape.
2. Copy the content of the **Console** tab to a reply here, please.

**Comment by mugenstylus1** [comment]
I will do this the next time the error occurs. Currently it is not having that error.

**Comment by mugenstylus1** [comment]
This is the console copy

[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
[TRACE]: Processing outgoing HTTP request main.247a5491be9484dbaf84.js:1:1615599
[TRACE]: Adding authentication token to request main.247a5491be9484dbaf84.js:1:1615687
[TRACE]: Retrieving authenticatione token main.247a5491be9484dbaf84.js:1:1615080
[DEBUG]: Response received: 
Object { type: 0 }
main.247a5491be9484dbaf84.js:1:1615871
Firefox can’t establish a connection to the server at ws://comixed.lan/ws/124/gv5tz3hx/websocket. main.247a5491be9484dbaf84.js:1:338626
[ERROR]: Error response received 
Object { headers: {…}, status: 500, statusText: "OK", url: "http://comixed.lan/api/files/metadata", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://comixed.lan/api/files/metadata: 500 OK", error: {…} }
main.247a5491be9484dbaf84.js:1:1615943
[ERROR]: Service failure: 
Object { headers: {…}, status: 500, statusText: "OK", url: "http://comixed.lan/api/files/metadata", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://comixed.lan/api/files/metadata: 500 OK", error: {…} }
main.247a5491be9484dbaf84.js:1:2266998

**Comment by mcpierce** [comment]
@mugenstylus1 Can you please try reproducing this and send me a log snippet for the backup for when this error occurs?

**Comment by mugenstylus1** [comment]
So i tried recreating the error. So far I have not been able too.
