### ISSUE TITLE
Cancel Process. 

### ISSUE THREAD

**Issue by mugenstylus1** [comixed/comixed#1323]
**Is your feature request related to a problem? Please describe.**
When Importing or a process hangs

**Describe the solution you'd like**
A current process menu where you can cancel import or processing books. 

**Describe alternatives you've considered**
Moving problematic books that hang on import

**Additional context**
Over 4 hours to process 368 books

**Comment by mcpierce** [comment]
@mugenstylus1 An interesting idea, but I have questions we'd need to answer first. This is something that should be discussed on the [user mailing list](https://www.freelists.org/list/comixed) to get as many points of view as we can. Then, when we know what we want to do, we can open a feature request with those answers.
