### ISSUE TITLE
Create a page that lists duplicate (or suspected duplicate) comics.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#134]
As a user, I would like to be able to identify both duplicate and potential duplicate comics.

For this feature, the page hashes should be used to identify duplicates.  By counting the pages in a comic, and then counting the times each hash is referenced by other comics, it should be possible to come up with a percentage of duplicated pages - greater than, say 90%, could indicate a likely duplicate.

The reason for this request is as I'm reviewing duplicate pages, I'm seeing comic pages (not adds or scanner tags etc.) that are duplicated in different comic files - that have different series, volumes, numbers and comic vine ids etc.

One of the stand out features of CX is the page hashes...leverage it as much as possible :)

**Comment by mcpierce** [comment]
@bareheiny Neat idea. I would definitely see something like this giving us a more useful duplicates page; i.e., instead of just being about pages, have a tab for duplicate comics and another for duplicate pages.

It'd be pretty processor intensive (compared to other features) but the benefit is, as you point out, a great one for keeping your library tight.

**Comment by bareheiny** [comment]
It takes anywhere between 2 minutes to 2 seconds for the SQL query I created to run...so that's not too shabby.

Looking at my colleciton, I apparently have 251 comics with duplication percentage of 90+, 145 between 50-89, and 14k between 0.01-49 - I'd expect the 0.01s to be scanner pages.

Most of my library doesn't have any duplicated pages....but I'm not entirely sure how accurate that is.  I may not have enough decimals in my calculation!


While I may only use this type of feature once or twice...I can see it being immesley useful for users who may never have used a library application....I know somebody who collects, collects, collects...but doesn't keep track of what he has or where he's stored it >_<

**Comment by mcpierce** [comment]
@bareheiny What I was thinking was to have each comic decide how much of a duplicate it is. Since each one knows how many of its pages are duplicated in other comics, it's sort of built-in for them to know their percentage duplication.

**Comment by mcpierce** [comment]
@bareheiny I know it's been a while, but this feature is finally complete and will show up in the next release in March.
