### ISSUE TITLE
Add ARM and ARM64 builds on docker hub

### ISSUE THREAD

**Issue by SenorSmartyPants** [comixed/comixed#138]
Please add ARM and ARM64 builds on docker hub in addition to AMD64. Thanks

**Comment by PiDockMedia** [comment]
comixed/comixed:latest should be multi-arch now. I only tested the amd64 image but it seemed to build with no errors. Give it a try and let me know how it goes for you.

**Comment by SenorSmartyPants** [comment]
This seemed to be working earlier, but when I pulled latest there is only amd64 build now.

**Comment by crivote** [comment]
Hi, I tried to install a container in a Raspberry pi 4 using your image on dockerhub but got the error:
` exec user process caused "exec format error"` 
I think that means there are'nt still ARM builds. Do you plan to release them? Thanks!

**Comment by mcpierce** [comment]
@crivote Hi, thanks for bringing that to our attention. Do you know what exec is causing that error? We have a dependency on [webp-imageio](https://mvnrepository.com/artifact/org.sejda.imageio/webp-imageio) for handling WebP pages in a comic, which is the only part of the project that contains native code. In the JAR I see:

```
     0 Thu Apr 23 11:36:56 EDT 2020 native/
     0 Thu Apr 23 11:36:56 EDT 2020 native/win/
     0 Thu Apr 23 11:36:56 EDT 2020 native/win/32/
404992 Thu Apr 23 11:36:56 EDT 2020 native/win/32/webp-imageio.dll
     0 Thu Apr 23 11:36:56 EDT 2020 native/win/64/
504832 Thu Apr 23 11:36:56 EDT 2020 native/win/64/webp-imageio.dll
     0 Thu Apr 23 11:36:56 EDT 2020 native/mac/
     0 Thu Apr 23 11:36:56 EDT 2020 native/mac/64/
626700 Thu Apr 23 11:36:56 EDT 2020 native/mac/64/libwebp-imageio.dylib
     0 Thu Apr 23 11:36:56 EDT 2020 native/linux/
     0 Thu Apr 23 11:36:56 EDT 2020 native/linux/64/
712056 Thu Apr 23 11:36:56 EDT 2020 native/linux/64/libwebp-imageio.so
```

So is it one of those that's causing the error for you? If so, I'd recommend visiting [their Github page](https://github.com/sejda-pdf/webp-imageio) and file a bug with them, and referring back to this ticket as well.

**Comment by FrancisKunz** [comment]
Hi,

still got the same problem installing Comixed on a Raspberry Pi4 with Ubuntu server:

`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by mcpierce** [comment]
@FrancisKunz Ah, and I see that webp-imageio has had a few releases since this issue was reported (we're using 0.1.2 and right now they have 0.1.6 available).

I'm cutting a new release (0.8.0-2.0) now and, if you find that it fixes this issue, please let me know and we can mark this as fixed.

**Comment by FrancisKunz** [comment]
@mcpierce as soon as the new docker image is up, i'll update you on the status

**Comment by FrancisKunz** [comment]
bad news ...
Comixed 0.8.0-2.0
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by mcpierce** [comment]
@FrancisKunz Bugger.... Sorry to say, but it's a bug outside of our codebase. That's an error in the webp-imageio library that we're using, and we can't fix bugs like that.

Would you mind opening a bug with them and referencing this bug?

**Comment by mcpierce** [comment]
Re-opening this so we make the Docker image itself multi-arch.

**Comment by eneglan** [comment]
Thanks for re-opening this. I have no real experience with building docker images but judging from this guide https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ it should be quite straightforward for you to create a multi-arch image with buildx.

**Comment by mcpierce** [comment]
> Thanks for re-opening this. I have no real experience with building docker images but judging from this guide https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ it should be quite straightforward for you to create a multi-arch image with buildx.

Literally the link I was just reading to see what I can do to meet this request. 😄

**Comment by mcpierce** [comment]
I wonder, since we use their Github action to publish our updates to Docker, if we can't use [this feature](https://github.com/elgohr/Publish-Docker-Github-Action#platforms) to publish for ARM as well?
