### ISSUE TITLE
Issue with accented chars in file or directory on docker

### ISSUE THREAD

**Issue by an0Nym0us63** [comixed/comixed#1424]
**Describe The Bug**
A clear and concise description of what the bug is. Please include as much detail as possible.

**To Reproduce The Bug**
Install as a docker

Choose Import

Select the folder to scan

All folders with accented characters are ignored and the file dont show. All files with an accented characters but not in a folder with accented characters are shown but throws an error on import

I'm french so accented chars are often presents. I tested with the windows version and there is no issue all files are retreived. The issue is only on the docker version (i guess it's related with maybe the LANG env var which i think should be a param)

Here is the error on the case of files

Caused by: java.io.FileNotFoundException: /mediatheque/Ebooks/A traiter/Bds/My Hero Academia (2016)/My Hero Academia T22 - C201 ?? 212 [168p] (Kouhei HORIKOSHI) [Scantrads].cbr (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112) ~[na:na]
	at org.comixedproject.adaptors.file.FileTypeAdaptor.getArchiveAdaptorFor(FileTypeAdaptor.java:72) ~[comixed-adaptors-1.2.0-1.jar!/:1.2.0-1]

For folder it's the same but as the folder is considered non existing due to the chars it's content is totaly ignored

**Expected Behavior**
All files should be imported wheter they contain an accented characters or wheter they are in a folder with an accented characters. 

 - Docker image Official
 - Browser name not related to browser

**ComiXed Build Detail:**
Le code a été build depuis la branche nommée bf522ad183f411116649c0a7d46ead0e0393a478
Le code a été build le October 1, 2022 at 1:17:56 PM GMT+2.
Le code a été build sur la machine nommée fv-az173-109
Le version du code est : 1.2.0-1.
Le hash du dernier commit de la branche source est bf522ad183f411116649c0a7d46ead0e0393a478.
Le commit a été créé le October 1, 2022 at 12:50:49 AM GMT+2.
Message du commit
Changed the release version to 1.2.0-1 [#1418]
Le commit a été créé par Darryl L. Pierce <mcpierce@gmail.com>
La branche ne contient pas de modification non comité.
Cette branche suit la branche distante https://github.com/comixed/comixed
L'url de la base de données utilisée est jdbc:h2:file:~/.comixed/comixed;create=true

**Comment by mcpierce** [comment]
@sarakha63 Can you please share the filename for the comic here with the accented characters?

**Comment by an0Nym0us63** [comment]
For example create an Astérix folder and put some files in it and try to import

and other example of files would be for example My hero Academia #22  janvier à fevrier.cbz

the idea is to use comixed to map correct metadata and rename but for that the files should be imported in first place

On the windows release this works but not on the docker. I guess it can be related to LANG os environement variable

regards

**Comment by mcpierce** [comment]
@sarakha63 Thanks for the response. I was able to confirm this on my system (Mac OSX with Docker running CX 1.2.0-1). I'll start working on this straight away and see if we can get a solution together shortly.

**Comment by mcpierce** [comment]
@sarakha63 I've created a fix that works for me locally. I'm going to generate a new release, v1.2.0-2, that will contain that fix for Docker. Please test it when you can and, if things are working, please feel free to close this ticket as fixed.

**Comment by mcpierce** [comment]
@sarakha63 Following up on this, since it's been two weeks. Is this issue resolved with the latest build?
