### ISSUE TITLE
The $TITLE macro is replaced by the issue title during library consolidation.

### ISSUE THREAD

**Issue by an0Nym0us63** [comixed/comixed#1425]
**Is your feature request related to a problem? Please describe.**
It's not really a problem. In fact when i go digging in my file i would like if possible to see the title of the volume for now i sort like that 

$SERIES/$SERIES #$ISSUE(3) - $COVERDATE

**Describe the solution you'd like**
I would really like to be able to do that

$SERIES/$SERIES #$ISSUE(3) - $COVERDATE - $TITLE

With $TITLE being the title of the volume

**Comment by mcpierce** [comment]
@sarakha63 Thank you for the suggestion.

I'm not sure I follow, though. Is "the title of the volume" different from the existing $VOLUME macro? Or do you mean the title of **the issue**; i.e., Batman v2016 #128 has the title of "Failsafe: Part Four; I Am a Gun Part One"?

If the latter, one question I would have is: what do we do if the issue has multiple stories, each with a separate title? We could default to the first, I suppose.

**Comment by an0Nym0us63** [comment]
Yes the idea was to have a tag for the issue name the one found on the detail page in title field. As this would be an option for the user i think falling back to the first one in case there are more than one.

And i have another minor question can we have an option to not write the volume in the metadata when there isnt one (just like mylarr does)

For now it writes the year and sometimes it messes up in Kavita (i can open another issue for that point if needed)

**Comment by mcpierce** [comment]
@sarakha63 Yes, please, open that as a separate issue. I think we'll have some discussion around how to handle the lack of a volume.
