### ISSUE TITLE
Selecting comics doesn't honor the display filters.

### ISSUE THREAD

**Issue by Bugmaniac71** [comixed/comixed#1438]
Selection system - If I select show only CBR, then want to select all those CBR's ONLY it selects every format again.

**Comment by mcpierce** [comment]
@Bugmaniac71 Thank you for reporting this. I'll get to work on it straight away and try to have an updated release with the bug fixed within a week.

**Comment by mcpierce** [comment]
@Bugmaniac71 Sorry it took an extra week to complete. I'm going to push a new build today that includes this fix in it.

**Comment by Bugmaniac71** [comment]
No worries at all looking forward to testing it!
