### ISSUE TITLE
MySQL: Specified key length too long for recent versions of MariaDB

### ISSUE THREAD

**Issue by lordyod** [comixed/comixed#1449]
**Describe The Bug**

Starting a new instance of Comixed with the MySQL back end (using MariaDB) fails with

```
liquibase.exception.DatabaseException: Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE comixed.comics (id BIGINT NOT NULL, filename VARCHAR(1024) NOT NULL, archive_type VARCHAR(4) NOT NULL, added_date datetime NOT NULL, last_updated_date datetime NOT NULL, scan_type_id BIGINT NULL, format_id BIGINT NULL, imprint VARCHAR(64) NULL, sort_name VARCHAR(128) NULL, comic_vine_id VARCHAR(16) NULL, publisher VARCHAR(128) NULL, series VARCHAR(128) NULL, volume VARCHAR(4) NULL, issue_number VARCHAR(16) NULL, cover_date date NULL, title VARCHAR(256) NULL, summary LONGTEXT NULL, `description` LONGTEXT NULL, notes LONGTEXT NULL, CONSTRAINT PK_COMICS PRIMARY KEY (id), UNIQUE (id), UNIQUE (filename))]
```

**To Reproduce The Bug**

1. Host setups:
  - Client: Comixed 1.21.1-1 on Ubuntu 22.04
  -  Server: mysql 15.1 via Debian 10.3.36-MariaDB on Debian 10
2. Create database:

```
mysql -e "create user 'comixed'@'(clientip)' identified by (password); \
    create database comixed; \
    grant all privileges on comixed.* to 'comixed'@'(clientip)' identified by (password);
    flush privileges; "
```

3. Install comixed:

```
wget https://github.com/comixed/comixed/releases/download/v1.2.1-1/comixed-release-1.2.1-1-GA.zip
unzip comixed-release*
mv comixed-release* /opt/comixed
mkdir -p /var/lib/comixed
```

4. Start comixed as per [the docs](https://github.com/comixed/comixed/blob/2dc57db517f5fae80453f5321385d5a7b4996c14/docker/README.md):

```
/opt/comixed/bin/run.sh -j jdbc:mysql://(hostip):(hostport)/comixed -u comixed -p (password) -i /var/lib/comixed
```

**Expected Behavior**

Comixed should launch without errors.

**Additional Context**

See attached log: [comixed.log](https://github.com/comixed/comixed/files/10036201/comixed.log)

**Comment by mcpierce** [comment]
@lordyod Hrm, CX was developed using MySQL using the v8 connector and v5.5 server. I know Mariah was original forked from MySQL, but I don't see that there's a v15.1 of that (the latest I see online is v10.9.4., as of this month).  Looking at [this page](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/) I see that the version of MariahDB would need to be v5.5 to be functionally compatible. I'll update the project documentation to make sure this is called out.

Can you please verify what release and version of the server is being used? We may have some underlying compatibility issues with Mariah if it's changed from how previous MySQL worked.

**Comment by lordyod** [comment]
I don't know why it would list version 15, maybe it's a package version?

```
root@db:~# mysql --version
mysql  Ver 15.1 Distrib 10.3.36-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

This is what you get when you install mysql from the debian package repositories. Considering MySQL v5.5 reached end of life in 2018, would an update be in order?

**Comment by mcpierce** [comment]
@lordyod Yeah, that's odd. Normally I would expect packages to still use the app's version (I've maintained packages for both Fedora and Debian). Not sure why this above, which is the app itself, is reporting that version.

At any rate, yes, we'll need to upgrade our support to target more recent versions of MySQL. My only fear is that we can't change existing migrations since that would break anybody who has an existing CX server. I'll look to see if that issue is caused by the migration if, hopefully, it's a case of the MySQL connector code for v5 not working with newer versions of MySQL.

**Comment by lordyod** [comment]
I have just setup a different db server to use for this. I started with MySQL v5.5 (using MariaDB 5.5.68, which is a drop-in replacement) but ran into an error which is apparently quite common related to column size ([example here](https://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes)). The only solution I could find for this is to set the following in `/etc/my.cnf`:

```
set global innodb_large_prefix = ON
set global innodb_file_per_table = ON
set global innodb_file_format = Barracuda
set global innodb_default_row_format = 'DYNAMIC'
```

The problem is that `innodb_default_row_format` isn't available in MySQL 5.5, it's apparently added in 5.7. I switched to the corresponding MariaDB version (10.1.48 from [here](https://mariadb.org/download/?t=mariadb&o=true&p=mariadb&r=10.1.48)), set the above in `/etc/my.cnf`, and now Comixed is loading and seems to be working fine (it's a fresh install so I can't say for certain without testing).

**Comment by mcpierce** [comment]
@lordyod Very interesting. I wonder if upgrading the connector version in the CX release, though, may overcome some of those issues? I'll define include the the above configuration fixes, and appreciate that you put the time in to find out those workarounds!

I'll try to have a fix available over the weekend to see if we can work with newer version of MySQL and Mariah.

**Comment by mcpierce** [comment]
@lordyod  Unfortunately, I wasn't able to overcome the issues so far with MySQL.

**Comment by mcpierce** [comment]
@lordyod Okay, I'm going to close this ticket and, when we start on 2.0 (targeting next year), we will make sure that more modern MySQL is targeted rather than the older version.
