### ISSUE TITLE
 bdgest.com / bedetheque.com to be added as a scraper

### ISSUE THREAD

**Issue by Flyingfufu** [comixed/comixed#145]
**Is your feature request related to a problem? Please describe.**
ComicVine do find only few of my ebooks

**Describe the solution you'd like**
I would love to see bdgest.com / bedetheque.com to be added as a scrapper. It would add approx. 40.000+ series, 260.000+ albums.

**Describe alternatives you've considered**
Here seems to be a possible solution (I hope) : https://github.com/givka/bedetheque-scraper/

**Dependencies**
 * #301

**Comment by mcpierce** [comment]
@Flyingfufu Definitely a great idea. I think this is going to require a refactoring of our existing scraping code to let the user choose which scraping source to use. Though if someone would like to take a stab at it sooner I'm open to a PR.

**Comment by lbesnard** [comment]
yeah that will be absolutely amazing. Another alternative is to use https://www.bdovore.com/ as a source, however, they don't have an api, which is always tricky, but the link above from @Flyingfufu seems like the best starting point

**Comment by mcpierce** [comment]
@lbesnard We would definitely need an API to interface with for our scraping feature.

**Comment by mcpierce** [comment]
Adding the Bedetheque Scraper CR plugin here as reference.
[Bedetheque Scraper 2_v4.9.crplugin.zip](https://github.com/comixed/comixed/files/9229409/Bedetheque.Scraper.2_v4.9.crplugin.zip)

**Comment by lbesnard** [comment]
for ref, I've been working on a scraper for bedetheque. it's really an early stage, a lot of work left to do.
https://github.com/lbesnard/bdnex

**Comment by mcpierce** [comment]
@lbesnard Unfortunately, ComiXed isn't plugin compatible with CR. But, I'd love to be able to ask you questions about how you're doing things like getting the list of volumes, and how you're getting the details for a single issue. If you have an example URL for each of those requests, I can use that to knock out a Bedetheque scraper for ComiXed pretty quickly.

**Comment by lbesnard** [comment]
bedetheque is tricky. Creating a working code for it is definitely hacky. 

The first issue is to find the right bedetheque webpage for a specific album. It doesn't really matter if it's a series or a one shot. Each album has its own page in bedetheque. 
Initially, I tried searching for the right webpage with duckduckgo, and parse the results. This worked pretty well, but was quite slow. And after a few searches, the IP was temporary banned.
Then, I realised I could maybe use the sitemaps.xml files. And that's what my code is currently doing. 

It first downloads all the sitemaps files from bedetheque, which lists all the different webpage available. Each url value has enough information to hopefully match an album name with it's bedetheque url. 
To do the match, I do some fuzzysearch. This is where my code needs to be improved quite a bit. At the moment, it's only checking parsing the URL of the match with the highest levenshtein score (but it's note necessarily the right one). It then downloads the bedetheque URL, parse the needed fields, and checks that the cover coming from bedetheque is similar to the one in the CBZ/CBR

It's a massive WIP. I'd like to keep working in it. It annoys me a bit to go solo and reinvent the wheel.

Another way forward, if comixed wanted to use a REST API, could be to get a API key from amazon, and find the french comic info directly from it? But I'm not even sure if this is currently possible

**Comment by mcpierce** [comment]
@lbesnard Hi, wanted to follow up on this. Your request hasn't been forgotten. The approach we've taken for adding new metadata scrapers is to make it so that developers can start a third-party project to provide those adapters, rather than making it a core feature of the CX project.

Please see [this email](https://www.freelists.org/post/comixed/The-future-of-metadata-adaptors-for-CX) from our mailing list for more details.
