### ISSUE TITLE
Split the "Fetch Volumes" button into two buttons - one for "Fetch" the other "Fetch (Skip Cache)"

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#148]
As a user with a touch screen device, I find it cumbersome to use drop down menus for options - fat fingers can make CX niggly to navigate (especially on the main menu).

Due to the way scraping currently works, I would rather be able to press a single button to scrape an issue, rather than pressing the down arrow, then selecting "Fetch".

**Comment by mcpierce** [comment]
(updating this after responding to #152)

How about making the parent button's click do the behavior from the last time you used the page? So if you click the split button, select "skip cache", then the every subsequent time you click the button is skips the cache as well until you explicitly select to not skip the cache?

**Comment by bareheiny** [comment]
Works for me :)

**Comment by bareheiny** [comment]
Any chance this will get a milestone target?  I've found scraping on my iPhone while watching TV is nice and quick...but it would be quicker if I could press one button rather than needing to select a scraping option first ;)

**Comment by mcpierce** [comment]
@bareheiny  The implementation I describe (having the button use the last cache option) is now merged into develop. Please take a look and, if it works, please close this ticket.
