### ISSUE TITLE
Allow users to bypass the "Scrape This Issue?" confirmation screen.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#149]
As a user, I would like to be able to prevent the "Scrape This Issue?" conformation screen from being displayed, as it adds an extra (and unwanted in my case) step to the scraping process.

**Comment by mcpierce** [comment]
Sure, adding a checkbox to turn on/off prompting would be simple enough.

**Comment by bareheiny** [comment]
Any chance this will get a milestone target? I've found scraping on my iPhone while watching TV is nice and quick...but it would be quicker if I could didn't need to confirm the scraping selection ;)

**Comment by mcpierce** [comment]
@bareheiny I'm going to tweak this feature request slightly. I'm adding a toggle to the scraping toolbar, but only when scraping multiple comics, to streamline that process. And I'm going to not make it a persistent preference (for now) so admins can use it and give feedback.
