### ISSUE TITLE
Select-all/regex options

### ISSUE THREAD

**Issue by aarondunlop** [comixed/comixed#1546]
**Is your feature request related to a problem? Please describe.**
Manually selecting a series of items can be repetitive. Trying to select comics by series or publisher can take many steps and all comics makes it a manual process.

**Describe the solution you'd like**
The select-all is nice but there are situations where selecting all on a screen (all 25, 50, 100, etc) would be ideal. Maybe this could be a dropdown under the select checkbox and you can flip from all, to all on window.

Also, is it possible to add a regex filter for each tab? It *looks* like all comics are already being loaded, so simply filter down to a subset that match the filter. Simple wildcards would be wonderful.

**Comment by mcpierce** [comment]
Do you mean something like having the search bar on the page optionally treat the search as a regex rather than pure text?

**Comment by aarondunlop** [comment]
Correct. For example, maybe to the left of 'Year' you could add a text field with a dropdown that selects the criteria:

Publisher
Series Name
Volume
Issue #
Cover Date
Store Date

where the text box allows filtering. This would make it much more intuitive for users to get going and fill in any gaps until the figure out where everything sits.

![image](https://user-images.githubusercontent.com/25571790/224337453-b713820d-23e3-43b7-9eb0-1e0cf6a8a8f0.png)

**Comment by mcpierce** [comment]
Interesting idea, and pretty standard for web UXs. I'll dig into it for the next release.

**Comment by aarondunlop** [comment]
I started digging through the code. I may see if I can take a crack at this. I'd like to help out.

**Comment by mcpierce** [comment]
> I started digging through the code. I may see if I can take a crack at this. I'd like to help out.

Definitely appreciate it and welcome the help! Feel free to email me with any questions you may have.

**Comment by mcpierce** [comment]
@aarondunlop Was thinking over this feature request this weekend and had an idea and wanted to bounce it off of you:

In the next release (v1.6, at the end of this month) the old filters on the comic list page are being replaced with a popup dialog l like the following:
![image](https://github.com/comixed/comixed/assets/61601/9ca8edf1-2312-4e73-9ee6-0f134602d433)
Whatever you enter there will limit what's displayed, including the filtering text. Is that sufficient to what you're looking for to search comics, or does the searching/filtering need some additional checks?
