### ISSUE TITLE
Scraping actions should be logged.

### ISSUE THREAD

**Issue by aarondunlop** [comixed/comixed#1548]
**Is your feature request related to a problem? Please describe.**
ComicVine can be buggy, and it's possible to do Very Bad Things (Go to Publisher, select a series with a huge number of issues like Batman, fetch all issues).

**Describe the solution you'd like**
Having a dedicated log to scraping would make troubleshooting easier. Especially if these are eventually exposed in-application. Ideally things logged would be the request and response values. Optionally it would be helpful if the entire (HTTP) request and responses were logged with a 'debug' option. As this application takes off (because it is excellent) this will help users debug if it's a scraper causing issues, if they're being throttled, or if it's an application bug.

**Comment by mcpierce** [comment]
We used to have a separate audit log table for scraping that was removed in #1410.

Have you tried the command line option to turn on additional logging? If you use the **-D** option it turns on verbose logging. You would then get more detailed logging across the board for the server. Combine that with **-L** to write to a file and you can capture that output for reference.

That all said, I'm now thinking about having some additional options:
 * -D - turn on all verbose logging
 * -DM - turn on verbose logging for metadata/scraping only
 * -DW - turn on verbose loggin for web interface only

Then you could selectively turn on all, just metadata related, or just web related logging. What you think?
