### ISSUE TITLE
View the comics that a duplicate page exists in.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#155]
I may be missing it (and I'm 60% sure I've seen the functionality in CX before), but there does not appear to be a way to identify the comics that a duplicate page exists in.

Ideally, the duplicates page would allow users to see the comics (file names and primary metadata fields) that a duplicated page exists in.

This would then allow the user to determine an appropriate course of action.

**Comment by mcpierce** [comment]
@bareheiny Yes, there was a (very rough) implementation previously that showed the affected comics along with each page. I yanked it out when I refactored the view, and haven't re-implemented that page yet. But I'm putting it on the plan for 0.6 since it's a useful library management feature.

**Comment by mcpierce** [comment]
@bareheiny I'm going to close this issue as that feature was implemented in #602.
