### ISSUE TITLE
The Docker image can run as a part of LinuxServer.io

### ISSUE THREAD

**Issue by Bugmaniac71** [comixed/comixed#1556]
Could support be implemented for specific user and group id's to be passed through (same as linuxserver)?

    environment:
      - PUID=2023
      - PGID=2000
      - UMASK=002
      - TZ=Europe/London

This would make permissions so much easier to handle and aligns with how a lot of docker containers are going.

drwxr-xr-x  2 calibre       media 4096 Mar 17 10:49 calibreweb
drwxr-xr-x  4 root          root  4096 Mar 17 11:20 comixed   <-----------------------
drwxrwxr-x  2 gluetun       media 4096 Mar 15 14:11 gluetun
drwxrwxr-x  7 heimdall      media 4096 Mar 15 12:19 heimdall
drwxrwxr-x  7 homeassistant media 4096 Mar 17 10:48 homeassistant

Thanks.
C.

**Comment by mcpierce** [comment]
@Bugmaniac71  Sure, that's a great suggestion! I'll include that for our release at the end of this month.

**Comment by Bugmaniac71** [comment]
Awesome thank you!

**Comment by mcpierce** [comment]
@Bugmaniac71 To clarify, do you want the container to create a new user and use that user when running the ComiXed app? Or are you wanting to set the uid/gid in the command line when creating the container, and have that be used?

**Comment by Bugmaniac71** [comment]
Map the guid/uid of whatever is used inside the container to a specified uid/guid on the host, same as the linuxserver. Io containers do please.

**Comment by mcpierce** [comment]
@Bugmaniac71 Okay, I'll confess: I know next to nothing about linuxserver.io, having never worked with their project in past. I'm definitely going to make this happen, but it may not be before the release at the end of this month.  I need to do a little learning, unless you can point me to something or someone who can help make it happen faster?

That said, since it's a Docker image update, it shouldn't be tied to a specific release of CX, so when it's done it should go live pretty quickly.

**Comment by Bugmaniac71** [comment]
No worries at all no rush - I think first port of call would probably be their discord server https://discord.gg/YWrKVTn

Regard
Carl.

**Comment by mcpierce** [comment]
@Bugmaniac71 Wanted to let you know that this wasn't forgotten about, and that I would like to implement it for the next release at the end of this month. But I tried the Discord link shared and couldn't find any posts or forums for asking for some guidance on updating our image to work with linuxserver.

Can you point me to any other projects that participate that I could use as an example?

**Comment by Bugmaniac71** [comment]
Hiya sorry had completely forgotten about this, from what I can remember the user and groups let you map the internal container user/group within the container to external (host). Most of Linux server.io containers work this way. If I get chance to get back to my server this weekend I'll see if I can grab the list of containers I use which work this way (although off top of my head most of the arrs work that way).

**Comment by synapseattack** [comment]
@mcpierce would it be possible to add a build type of tar.gz to the assembly xml so we can get that archive type? With that I should be able to build a docker image based on linuxserver.io's alpine. I know next to nothing about java and my maven builds are failing so I'm having problems doing this part myself.

**Comment by mcpierce** [comment]
@synapseattack Would the tar.gz file contain the same contents as the existing release zip file?

Regarding your maven builds failing, can you share the failure output? I can help fix that as well.

**Comment by synapseattack** [comment]
The full trace is here: https://pastebin.com/1UYfTJXw
Be warned. I don't know jack about java and am mostly a python and docker hobbyist. So I might be doing something dumb :) 

Yes, if the tar.gz contents can be identical to the zip it would be great. tar has a bit more options for extracting things a specific way and makes working inside the container built a bit easier. At least for me.

**Comment by mcpierce** [comment]
> The full trace is here: https://pastebin.com/1UYfTJXw Be warned. I don't know jack about java and am mostly a python and docker hobbyist. So I might be doing something dumb :)

I see the issue: it's not building with JDK17, which is the minimum version required for our development branch. With v2.0 we're going to require JDK17 rather than JDK11.

> Yes, if the tar.gz contents can be identical to the zip it would be great. tar has a bit more options for extracting things a specific way and makes working inside the container built a bit easier. At least for me.

Sure, no problem. I'll do that up this weekend (#1713) and backport it to v1.6 so the update going out this weekend (v1.6.1) will include the tar.gz file.

**Comment by synapseattack** [comment]
I managed to build it. Thanks for that. I've got a new problem when the container first launch. Looks like it has a problem with the DB setup? :thinking: 

https://gist.github.com/synapseattack/ddd39c029ac35d18704f405a376f175f

**Comment by mcpierce** [comment]
@synapseattack I think the error's being caused by the H2 version being pulled in not being compatible with the current Liquibase migrations. Specifically, this part here:

```
comixed    | Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE PUBLIC.users ALTER COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY ([*]100)"; expected "START WITH, RESTART, INCREMENT, MINVALUE, MAXVALUE, CYCLE, NO, EXHAUSTED, CACHE, NOMINVALUE, NOMAXVALUE, NOCYCLE, NOCACHE, )"; SQL statement:
comixed    | ALTER TABLE PUBLIC.users ALTER COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY (100) [42001-214]
```

Which CX build is being used to create this image? Our releases are all H2 1.4.200 compatible. I've only seen this error when trying to use the migrations with H2 2.1, which we don't support yet, not till CX v2.0.

**Comment by synapseattack** [comment]
@mcpierce  I haven't made many changes just edited the docker file and pointed it to a file I build and uploaded. I created a fork with the branch lsio-docker at https://github.com/synapseattack/comixed/tree/lsio-docker/docker

**Comment by mcpierce** [comment]
> @mcpierce  I haven't made many changes just edited the docker file and pointed it to a file I build and uploaded. I created a fork with the branch lsio-docker at https://github.com/synapseattack/comixed/tree/lsio-docker/docker

Okay. I'll wager then this then was built from the master branch? I'd recommend building from the release/1.6 branch since it has migrations that should work for you.

**Comment by mcpierce** [comment]
@synapseattack ping - any traction on this? Anything I can do to help you?

**Comment by aarondunlop** [comment]
I think this is a couple of things being conflated.

1.) Base image being switched from Alpine to Debian.
2.) Running with the non-root user.
3.) Passing the UID/GID from env to env.

First, the base image - you can switch to Alpine but Linuxserver has debian too:

FROM ghcr.io/linuxserver/baseimage-debian:bullseye

The UID and GID are just numbers on the host or container. If the numbers match, permissions granted. If not, they're not. Names map to UID/GID's in /etc/passwd and /etc/groups but are mostly for us humans.

Second: set the user:

ARG UID
ARG GID
ARG UNAME
RUN groupadd -g ${GID} -o ${UNAME}
RUN useradd -m -u ${UID} -g ${GID} -o -s /bin/bash ${UNAME}

then change:

CMD ["bash", "/app/comixed-release-2.0.0-0.dev/bin/run.sh", "-L", "/library/comixed.log"]

to

CMD ["su", "-",  "${UNAME}", "-c", "/bin/bash", "/app/comixed-release-2.0.0-0.dev/bin/run.sh", "-L", "/library/comixed.log"]

Build using a flag: 

docker build --build-arg="UID=111" --build-arg="GID=111" --build-arg="UNAME=comixed" .

Note this was approximately tested - permissions probably need to be set (IE, an additional RUN chown -R ${UNAME} /app && chgrp -R ${UNAME} or something equivalent.

**Comment by mcpierce** [comment]
@synapseattack Does the above help you with what you're doing?

**Comment by mcpierce** [comment]
@synapseattack Wanted to check and see if there's any traction on this.

**Comment by mcpierce** [comment]
@synapseattack One last ping on this. Please let me know how things are and if you need any help.
