### ISSUE TITLE
Describe the bug using a single sentence, read instructions below

### ISSUE THREAD

**Issue by Bugmaniac71** [comixed/comixed#1557]
OS: Docker
Container: Latest

    volumes:
      - /opt/app_data/comixed/database:/root/.comixed
      - /opt/app_data/comixed/library:/library

Importing folder created underneath /library.

I've set everything up and seems to work ok, I can import correctly, scrape using comicvine no problem.

Now, when I come to consolidate it says that its completed successfully but has in fact not moved but deleted all the comics!

I cant see anything in the logs to indicate something has gone awry.

Anyone have any idea where to look ?

Regards
C

**Comment by Bugmaniac71** [comment]
Think I've solved it: I hadnt set 'Comic Renaming Variables', they're now showing up OK so this can me closed sorry.

**Comment by mcpierce** [comment]
> Think I've solved it: I hadnt set 'Comic Renaming Variables', they're now showing up OK so this can me closed sorry.

So, to verify, once you've setup the library renaming rules, then the library consolidation is working for you correctly; i.e., files are being moved as you expected?

I'll create a new feature request for the next release after this month to include an alert that pops up if the admin tries to consolidate the library without having the configuration set.

(edit)

I've created #1558 to track this new feature for our release in June.

**Comment by Bugmaniac71** [comment]
Yes exactly, that would be good!
C
