### ISSUE TITLE
Provide a way for CX to be gracefully closed via the web browser.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#158]
As a user, I would like to be able to exit / terminate CX via the web browser interface.

At the moment, I can log out - however this leaves my instance of CX running.  Ideally, there would be a "Exit" type menu item that logs me out, and terminates CX.

**Comment by mcpierce** [comment]
Hrm, I had thought we had a feature already for doing this. But I don't see it right now, so I'll mark this as the feature request.
