### ISSUE TITLE
Show duplicate comics

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#16]
If more than one comic has the same series, volume and issue number then they should be considered duplicates.

When viewing the list of comics, a duplicate (any comic after the first) should have an indicator on it that it's a duplicate.

**Comment by bareheiny** [comment]
Can this be tweaked a little?

In a few cases, volume numbers (essentially the year the first issue was released) can refer to a mini-series and a series.

Gen 13 for example has a five issue mini-series for 1994.  That same year, the first issue of an 80ish issue series came out.  CX is listing the entire mini-series and the first five issues of the second series as duplicates.

A possible option would be to include the Cover Date or ComicVine ID in the matching.  Maybe the cover date, in case a user didn't use CV for scraping.  While the additional field is null, the files would be considered duplicates based on the other fields.

**Comment by mcpierce** [comment]
@bareheiny I like that idea, of using the cover date in addition to the rest, for marking comics as duplicates. I'll open a new issue to capture that enhancement.
