### ISSUE TITLE
Show the ComicVine ID on the ComicVine page when viewing a single issue.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#160]
As a user, I would like to be able to easily identify weither or not an individual comic has been scrapped without having to navigate to the Overview tab.

If the ComicVine ID (or a similar flag or field) was displayed in the ComicVine tab, I could easily use the next / previous issue buttons to cycle through a series and preform a fetch on those comics that had not been scraped before.

**Comment by mcpierce** [comment]
When you say "easily identify", do you mean show the ID or an indicator somewhere on the list/grid view? Or just on the scraping tab?

**Comment by bareheiny** [comment]
Just on the scraping tab.  My preference obviously.

Essentially my work flow would be to to open a series, go to the scraping tab, then cycle through the comics via the next / previous buttons - scraping as required.  

I guess changing tabs isn't a major issue, but I'm looking to use as few actions as possible each time I'm processing comics.
