### ISSUE TITLE
Reading lists showing comics as "This comic is scheduled for processing", despite all comics fully processed.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#165]
As per subject.  A reading list with four comics is showing all four as scheduled for processing - despite all comics in the library being fully processed.

CX version:  0.5.0-0.1

1.  Start CX with no existing library and log in.

2.  Search for comics to import, select 50 and begin the import.

3.  Wait for all comics to be fully imported.

4.  Create reading list and add 4 comics to it.

5.  Open reading list - all covers displayed with spinning circle overlay, and “scheduled for processing” pop out text is displayed.

![reading lists](https://user-images.githubusercontent.com/1912425/75615943-3a13c500-5baf-11ea-9fec-910148d1f889.PNG)

Note all comics are fully processed, and the CX log shows no sign of processing (generating hashes and so forth).

Opening a comic from the reading lists shows all metadata is loaded, however selecting all and starting the scrape process displays the "Series name is required" and "Issue # is required" messages.

**Comment by mcpierce** [comment]
I'm pretty sure this is related to the comic, when it finishes processing, not causing the ReadingListEntry object related to it to be returned.

**Comment by mcpierce** [comment]
@bareheiny Can you verify if this issue still exists? And, if not, please close this issue. Thanks.

**Comment by bareheiny** [comment]
I can't figure out how to create / modify / access reading lists in the latest dev build.

**Comment by mcpierce** [comment]
I removed all of the old reading list code for listing and creating them.
I’m working on a new feature to add them from a pop up menu on the
navigation tree now. Should have it in by the weekend.

BTW, that issue is #233.

**Comment by bareheiny** [comment]
I didn't strike this issue during my load for testing 0.6, so can't confirm it's no longer an issue...but then I also can't confirm it still ist an issue.

Going to close it now - it can be re-opened if it happens again.

**Comment by mcpierce** [comment]
@bareheiny The fix for this is in rc7. The steps to verify it are:
1. start importing some comics
1. immediately go to the library page and select some of those importing comics
1. click on an already-imported comic (the context menu doesn't popup now on those still importing) to add selected comics to a reading list
1. go to that reading list and watch the imports process as expected

**Comment by bareheiny** [comment]
Right, so this is largely working - but I'm seeing some odd behavior

The pop-out menu doesn't appear for importing comics.  Deselecting it (by de-selecting all selected comics), and adding an already imported comic to a reading list results in the importing comic being added once it's imported....but not the select (and previously imported) comic.

I'll do a re-import on some larger comis to get the steps in the next day or so.

**Comment by bareheiny** [comment]
Nope, can't replicate.

Everything seems to be working as intended / expected - so closing this.
