### ISSUE TITLE
File system-incompatible characters in filenames are replaced with underscores.

### ISSUE THREAD

**Issue by asm0dey** [comixed/comixed#1659]
**Describe The Bug**
Colons in the issue names are replaced with underscores when consolidating the library.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Import comic with colon in the series name, for example, "Deadpool: Badder Blood"
2. Consolidate the library
3. The directory/file will have "Deadpool_ Badder Blood" instead of "Deadpool: Badder Blood" in it

**Expected Behavior**
I would expect all but deprecated symbols remain as is

**ComiXed Runtime Environment**

 - [ ] Windows
 - [X] Linux (any distro)
 - [ ] MacOS
 - [ ] Docker (if so, please select the host OS)

**Browser (If A Web Issue)**

 - [ ] Chrome
 - [ ] Firefox
 - [ ] Safari
 - [ ] Other (if so, please provide a name)

**ComiXed Build Detail:**

```
The code was built from a branch named 610abfc95018c50a59f919009c30f66781506a82
The code was built on 2023-06-30T20:06:41.000+00:00.
Code was built on a machine named undefined.
The code was marked with a Build version of undefined.
The latest commit hash on the source branch is undefined.
build-details.label.comit-time
Commit Message
Commit was created by undefined <undefined>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch undefined
build-details.label.jdbcUrl
```

**Additional Context**
OS: `Linux UNIT-1793 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux`
Java: 
```
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
```

**Comment by mcpierce** [comment]
@asm0dey Since characters like ":" are not ones that can be used in filenames, since they are path separators on *nix systems and disallowed in filenames on Windows, what would you recommend we use instead? The underscore character is one that's compatible across all filesystems.

**Comment by asm0dey** [comment]
On nix it works:
![image](https://github.com/comixed/comixed/assets/1297282/1fb5b108-4da9-44de-9a46-bcbcd7107e45)

On Windows, I suggest giving users an option on how to replace it. It would be helpful for *nix users, too, because for *nix, we have the same issue for `/` character, as in `Batman/Catwoman: The Gotham War.`

**Comment by asm0dey** [comment]
Sorry, I was wrong, on Linux `/` in file names works too

**Comment by mcpierce** [comment]
@asm0dey Okay, I'll take this into consideration and see when we can work it into a release. It's not really a bug since it's intentionally replacing those characters with underscores on all platforms. Generally we try to avoid having one-off behaviors for a platform since that can introduce inconsistent behavior, but there may be a cross-platform solution for setting the filenames for comics.

**Comment by asm0dey** [comment]
JFYI, there is an excellent (but maybe little bit i/o heavy?) way to understand if given filename is valid on the given fs: https://www.baeldung.com/java-validate-filename#using-nio2-api

**Comment by asm0dey** [comment]
Sorry for marking it a bug — I didn't know it was an intended behaviour; I thought it might be a faulty library.

**Comment by mcpierce** [comment]
> Sorry for marking it a bug — I didn't know it was an intended behaviour; I thought it might be a faulty library.

No problem, it's all good. 😄

**Comment by asm0dey** [comment]
It was so shocking that I could use a slash in a filename that now I'm sitting in jshell and trying to create such a file from Java. No luck so far. But it definitely can understand such file names, so it should be possible from Java.

```
jshell> Files.list(Paths.get(".")).forEach(it->System.out.println(it.getFileName()))
dd⁄xx.txt
```
