### ISSUE TITLE
On initial run, the admin user account is created through the web application.

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#1700]
As an admin, I would like to have control over creating the initial user accounts to prevent potentially exposing my instance to uninvited users through default accounts.

To do this, when the application is installed, it should **not** create any user accounts. And the first person to connect to it would enter their information and be made site administrator by default.

**Comment by aarondunlop** [comment]
Can an optional workflow be to reset credentials manually? IE, an admin user can manage other accounts passwords. Currently you can lock yourself out. Fixable, but beyond the range of most users.

**Comment by mcpierce** [comment]
@aarondunlop That would definitely be a good additional feature to add. I'll create a ticket for that now.
