### ISSUE TITLE
Admins can clear the image cache

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#176]
As a library owner, I would like to clear all entries from the image cache without having to manually delete the directory or access the backend server.

**Comment by bareheiny** [comment]
Could this be split into two processes:

1.  Delete everything
2.  Delete everything except covers

I like the responsiveness from having the covers cached, but don't want my covers directory filled up with the other pages in a comic - especially if I open a 500 page trade.

**Comment by mcpierce** [comment]
@bareheiny Potentially, but we'd need to somehow indicate in the cache that a file is a cover vs a story page to do that. Maybe as a follow on enhancement to this ticket.
