### ISSUE TITLE
Saving custom scraping rules fails

### ISSUE THREAD

**Issue by aarondunlop** [comixed/comixed#1790]
**Describe The Bug**
Modifying a scraping rule, then clicking save will revert the scraping rule to the previous (default?) rule.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Navigate to the scraping page.
2. Modify a rule. I set mine to: ^([\w[_][,-]]+)_([0-9]{1,5})_+\(([0-9]{4})\).*$
3. Click save.
4. The H2 database entry reverts back to the default, and the UI shows the default rule as well.
5.) Ordering saves as expected.

**Expected Behavior**
Ordering to save as expected, but also the scraping rule.

**ComiXed Runtime Environment**

Docker

**Browser (If A Web Issue)**

**ComiXed Build Detail:**

The code was built from a branch named 9021b376e384bc29db95283be67538a026b3d665
The code was built on 2023-10-28T20:36:49.000+00:00.
Code was built on a machine named undefined.
The code was marked with a Build version of undefined.
The latest commit hash on the source branch is undefined.
build-details.label.comit-time
Commit Message
Commit was created by undefined <undefined>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch undefined
build-details.label.jdbcUrl

**Comment by mcpierce** [comment]
@aarondunlop I've found and fixed the bug, and will put it out in this weekend's update. Please do us a favor and verify the fix works and, if so, you can close this ticket. And thanks for reporting it!

**Comment by aarondunlop** [comment]
Looks good! Appreciate the awesome work :)
