### ISSUE TITLE
Physically removed comics should prompt a 'deleted' workflow.

### ISSUE THREAD

**Issue by aarondunlop** [comixed/comixed#1798]
**Is your feature request related to a problem? Please describe.**
When a comic is deleted on the filesystem it fills the logs with spam. From the UI it is non-obvious that it has been removed, just that there isn't a page. This workflow could be similar for malformed or zero-byte comics.

**Describe the solution you'd like**
Comics missing, or malformed should trigger a workflow for removal or correction. 

**Describe alternatives you've considered**
This could be as simple as an automatic mark for deletion - though a more optimal workflow would be a triage page similar to the deleted column.

**Comment by mcpierce** [comment]
@aarondunlop Definitely a useful page to add to the app, one that shows all comics whose missing flag is set to true. Then the admin could mark them explicitly for removal. 
I wouldn't want to have the server automatically mark comics for removal, since that could go wrong easily.

**Comment by aarondunlop** [comment]
Agreed.

I don't know if this is tangential, but a deleted file can be blocking - trying to remove a comic that was physically removed simply fails.

**Comment by mcpierce** [comment]
> I don't know if this is tangential, but a deleted file can be blocking - trying to remove a comic that was physically removed simply fails.

What do you mean? You should be able to remove a comicbook and its related records from the database even if the physical file doesn't exist, since I don't believe the server checks for its existence: it should only do a cascading delete from comic_books -> comic_details -> comic_pages -> comic_tags.

**Comment by mcpierce** [comment]
@aarondunlop The v2.1 release will include an initial addition for this to call out in any comic view missing comic files. I'm still not sure what the best path would be to have the server respond to missing comic files, but am working on some ideas. I think this might be something where we'd want to have a plugin (or set of plugins) written that can offer different responses to missing comics.
