### ISSUE TITLE
CX appears to be loading each page in an archive looking for a cover during the "select for import" stage.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#180]
As per subject.

In the log (attached courtesy of @dukeofradish), you can see the entries for a WebP archive being loaded...page four is showing four times, page five five times etc.

This goes hand in hand with the "cleaning archive" messages - each time CX goes through a loading entry stage, a new "cleaning archive" is shown. 

Here's a snippit:

o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00004.webp size=620398
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00004.webp size=904036
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00004.webp size=847552
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00004.webp size=809560
org.comixed.utils.FileTypeIdentifier     : Attempting to detect mime type for stream
org.comixed.utils.FileTypeIdentifier     : result=image/webp
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00005.webp size=620398
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00005.webp size=904036
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00005.webp size=847552
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00005.webp size=809560
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=P00005.webp size=655882
org.comixed.utils.FileTypeIdentifier     : Attempting to detect mime type for stream
o.c.adaptors.archive.ZipArchiveAdaptor   : Loading entry: name=ComicInfo.xml size=2086609
org.comixed.utils.FileTypeIdentifier     : result=image/webp

Here's the log:  [jpgwebimport.txt](https://github.com/comixed/comixed/files/4332398/jpgwebimport.txt)

**Comment by mcpierce** [comment]
@bareheiny Okay, I'll look into this when I can. 

As was mentioned on the mailing list, the cleaning up message is the underlying Apache Compress code writing to stderr whenever it cleans up a dangling resource. There's not much that can done about that at the application level.

**Comment by bareheiny** [comment]
@mcpierce the cleaning up message is a non-issue now that I understand where it's coming from...but at the moment if you have a 200+ page WebP archive on the import page, you'll get 200+ of the messages.


Possibly related to this issue - CX doesn't show covers on the import page for WebP files.  The "comic cover" icon / image is shown....but it seems that happens only after every image in the archive has been checked.

![Capture](https://user-images.githubusercontent.com/1912425/76689841-e6b97080-669e-11ea-9a17-bb7e6a8ace6a.PNG)

**Comment by mcpierce** [comment]
@bareheiny This issue just hit me while working on #137 and is blocking that feature from being completed. So I think I need to revert the changes from #173 and try a different approach to fixing it.

**Comment by bareheiny** [comment]
Closing as no longer appears to be an issue with the latest pre-release.
