### ISSUE TITLE
Gravatar image is rendering larger than the container in the browser

### ISSUE THREAD

**Issue by bulletproof2k** [comixed/comixed#1800]
![2023-11-14_21-04-38](https://github.com/comixed/comixed/assets/1818579/4bc96794-fa97-4d93-a052-1163b9254ed1)

**Comment by mcpierce** [comment]
@bulletproof2k Thanks for bringing this to my attention. I've got a fix in place that appears to address the issue, and will include it in our next release in about 10 days. Once it's released, if you could verify the fix works, please close this issue.
