### ISSUE TITLE
Admin --> Users, New User screen not rendering properly.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#182]
The New Users screen in the Admin / Users section is not rendering properly, making it unusable.

See the screen shots below:

RC:

![0 5RC](https://user-images.githubusercontent.com/1912425/76690815-19686680-66a9-11ea-84eb-ae99c3b94ad3.PNG)

Dev:

![0 6dev](https://user-images.githubusercontent.com/1912425/76690829-2a18dc80-66a9-11ea-98c5-ec7a47bc25f7.PNG)

Once in this section (on the dev build), none of the menu actions appear to be usable - so the only course of action is to refresh the browser, which takes you out of the "add user" area.

**Comment by mcpierce** [comment]
@bareheiny Hrm, there must be an error occurring while it's rendering to make it do that. I'll take a look at it straight away.

**Comment by mcpierce** [comment]
@bareheiny I've pushed a fix for this, please give it a try and, if it works, could you close this ticket? Thanks.

**Comment by bareheiny** [comment]
Looks good on current dev build, closing ticket.
