### ISSUE TITLE
When converting comics, the admin can choose to delete the original comic

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#184]
When converting comics, the admin can check a box to tell the backend to delete the original comic once the conversion completes successfully.

# Acceptance Criteria
1. Any reading list in which the original comic was a member will have the new comic as well.

**Comment by BRUCELLA2** [comment]
When we delete the original comic, if the original comic was in reading lists, the new comic converted must also be in reading lists ?

**Comment by mcpierce** [comment]
@BRUCELLA2 Good point. And if the original isn't deleted then both comics should be put into the reading list, yeah?

**Comment by BRUCELLA2** [comment]
> @BRUCELLA2 Good point. And if the original isn't deleted then both comics should be put into the reading list, yeah?

Yes we can do that.
