### ISSUE TITLE
Reading Lists page not honoring sort/page size.

### ISSUE THREAD

**Issue by Cducharme84** [comixed/comixed#1848]
**Describe The Bug**
The reading lists page does not respect sorting by column or page size for items displayed.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Fill reading list so there's items to sort
2. Try to sort, example given in https://www.reddit.com/r/comixed/comments/196p30w/comment/khvileq/ is cover date column.
3. If more than 10 items added shows all of them anyway.

**Expected Behavior**
Sorting to order by the value of the column in ascending or descending order.

**ComiXed Runtime Environment**

 - [ ] Windows
 - [X] Linux (any distro)
 - [ ] MacOS
 - [X] Docker (if so, please select the host OS)

**Browser (If A Web Issue)**

 - [X] Chrome
 - [X] Firefox
 - [X] Safari
 - [ ] Other (if so, please provide a name)

**ComiXed Build Detail:**

The code was built from a branch named 802ee7afdf79a796a8889935bef3d5c0b93c5aca
The code was built on 2023-12-26T02:46:57.000+00:00.
Code was built on a machine named fv-az849-702.
The code was marked with a Build version of 1.6.7-1.
The latest commit hash on the source branch is 802ee7afdf79a796a8889935bef3d5c0b93c5aca.
This commit was created on 2023-12-24T19:02:02.000+00:00.
Commit Message
Changed the release version to 1.6.7-1 [#1682]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed

**Additional Context**
Originally happened and tested with import running, not sure if this was determined when you looked today as a factor or was coincidental so including for completeness sake of bug report.

**Comment by mcpierce** [comment]
@Cducharme84 Thanks for pointing this out. I've got a fix in place for this and will put it out this coming weekend. Once you've verified it works as expected, please close this ticket as finished.
