### ISSUE TITLE
When converting comics, deleted pages can be filtered out of the destination comic.

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#185]
A new option will be added to the convert comic dialog to select whether or not to remove deleted pages from the destination comic archive during conversion.

**Comment by bareheiny** [comment]
And blocked pages (to be honest I haven't looked at page blocking / deletion just yet...so I don't actually know if blocked pages get flagged for deletion)?

This leads to another discussion I think - should there be a way to remove deleted pages from an archive, or is the only viable option to remove the pages via a convert action?

**Comment by mcpierce** [comment]
@bareheiny When I was thinking of deleted pages I included blocked pages as well (in my head at least). A blocked page is one that's automatically considered deleted, while deleted pages are ones that you've explicitly marked as such; i.e., all blocked pages are deleted, but not all deleted pages are blocked.

One of the goals of conversion was the remove unwanted pages while performing the conversion. So maybe the term "convert" is misleading? Maybe we need to use a different term for it, since you can "convert" from CBZ to CBZ and toss all of the unwanted pages and update the ComicInfo.xml file.

How about "render" or "harden"? The idea is that this process is going to do any of the following actions:
1. remove unwanted pages,
1. update the ComicInfo.xml file,
1. use a new archive type, and/or
1. rename the pages in the comic.

Render kind of has a ring to it for me since it's what you do when you slow cook meat to draw out the fat.

**Comment by bareheiny** [comment]
Yeah, this one's tricky!

"Convert" makes me think of changing not only the container format (rar vs. zip), but image conversion (jpg to webp etc.).

Not that fussed on "render' and "harden" myself - I think it needs a word that captures both container format conversion as well as the removal of files.
