### ISSUE TITLE
Comics can be marked as read from the details > overview tab.

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#19]
As a comic reader, I'd like to know when I've already read a comic.

## Acceptance Criteria
1. If a comic has not been previously read by the user, then no styling changes are shown.
1. In the comic list view, if a comic has been read by the user, then the comic's row is styled differently.
1. In the comic detail view, an indicator shows the comic has already been read.

**Comment by bareheiny** [comment]
Question on this:  as CX does not have a native reader, how would the read status be recorded?

**Comment by mcpierce** [comment]
Ultimate CX will let readers call a REST API to mark a comic as read for a user. Also, the OPDS interface will ultimately let users filter the comics listed by their read state.

**Comment by bareheiny** [comment]
Any chance we could get a tickbox or something in the Overview page?

At the moment, the only way I can flag a comic as being read is by inserting a date read via SQL.

As Windows doesn't have any OPDS readers (that I've been able to find), and most existing readers likely won't be updated to make use of rest apis, the web interface may be the only way to mark comics as have been read.

**Comment by mcpierce** [comment]
@bareheiny Sure thing, we can add something to the overview tab to let you mark a comic as read.
