### ISSUE TITLE
Outdated build details for docker latest image

### ISSUE THREAD

**Issue by oscruise** [comixed/comixed#1909]
**Describe The Bug**
When pulling the latest image for docker, build details says it´s version 1.6.6 when it´s actually 2.0.0

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Create a docker container
2. Image Comixed/Comixed:latest
3. When container starts, see build details.
1. See error

**Expected Behavior**
Build details should say version is 2.0

**ComiXed Runtime Environment**

 - [ ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [ x] Docker (if so, please select the host OS)

**Browser (If A Web Issue)**

 - [x ] Chrome
 - [ ] Firefox
 - [ ] Safari
 - [ ] Other (if so, please provide a name)

**Comment by mcpierce** [comment]
@oscruise  v2.0.1-1 should have this issue fixed. Please verify it and, if it's working as expected, you can close this bug. And thanks again for reporting it to us!

**Comment by oscruise** [comment]
Fixed, thanks!
