### ISSUE TITLE
When scraping, comics from Imprints having primary Publisher recorded in PUBLISHER table.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#205]
Publishers and imprints are causing primary key violations when scraping.

Depending on the order of scraping, Wildstorm is being recorded as DC Comics and Icon Comics is being recorded as Marvel.

This causes primary key violations when attempting to scrape either a true DC or Marvel comic.

**Comment by mcpierce** [comment]
@bareheiny Yep, identified the issue. When the CV scraper sees the publisher is one of the know the imprints it's replacing the name with the parent publisher's name, which is causing the error.

Fixing it now.

**Comment by mcpierce** [comment]
@bareheiny  I've pushed a [PR](https://github.com/comixed/comixed/pull/206) that should fix this issue. When the prerelease is created, please test it and if it works you can close this ticket.

**Comment by bareheiny** [comment]
Looks good to me.

It does raise a question about correcting ComicVine data once a comic has been scrapped - but for now, I'm just going to modify the record via SQL.

**Comment by mcpierce** [comment]
@bareheiny If there's a change in the CV data, rescraping the comic replaces/overwrites the old data.
