### ISSUE TITLE
Imprint should take priority over Publisher when using the Publisher Collections item.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#207]
As per subject.

When using the Publisher item in Collections to view comics, I would prefer to see Imprints instead of Publishers where appropriate.

For example currently, Wildstorm is an imprint of DC Comics - however when using the Publishers collection view, I only see DC Comics - with the Wildstorm comics included.

Maybe it would be more appropriate to concatenate publisher and imprint, displaying items like this:  

DC Comics
DC Comics (Wildstorm)
DC Comics (Vertigo)

**Comment by mcpierce** [comment]
Fair idea, I don't see a reason not to include it in the next drop.

**Comment by bareheiny** [comment]
When viewing comics in a List view, the publisher is shown as:

Wildstorm (DC Comics)
Vertigo (DC Comics)
Icon Comics (Marvel)
Marvel
etc.

For consistency, the Publisher item in the Collections (and probably everywhere else Publisher is used - such as the donut chart) should be displayed in the same way.

**Comment by mcpierce** [comment]
@bareheiny A new PR was just merged that addresses this issue. Please take a look and, if it fixes the display issue with imprints, please feel free to close this ticket.

**Comment by bareheiny** [comment]
@mcpierce where should I be seeing this change?

I'm not seeing it in the Publisher collections list.

**Comment by mcpierce** [comment]
Ah, my bad. I ended up fixing how the publisher is displayed in the details view for a comic, and adding the ability to edit the imprint there as well. Nothing changed in the collection view.

**Comment by mcpierce** [comment]
@bareheiny Okay, this should be doing what you're describing.

**Comment by bareheiny** [comment]
Unfortunately this is a mixed bag :(

Good news...the Publisher collections list look good.

But...the Publisher display differs to that in the Comic Overview pane - Collections = Vertigo, Overview = DC Comics (Vertigo).  And if I click on the Publisher link in the Overview window, I get taken to DC Comics (which does not include the imprint comics).

And even worse news...if I open a comic via a specific Publisher (say "Astro City: aftermaths", Vertigo), that's the only comic page that opens - even if I try to open something completely unrelated (Immortal Hulk), I get taken to the "Astro City: aftermaths: page.

**Comment by mcpierce** [comment]
@bareheiny Can we verify if this bug is still present or if it can be closed?

**Comment by bareheiny** [comment]
Unfortunately it looks the same as the last time I checked.

**Comment by bareheiny** [comment]
Fleshing this out with steps to reproduce.

Steps to reproduce:

1.  Select a comic (any comic will do) for scraping.
2.  Change the Series, Volume and Issue # to:  "100 Bullets", "1999", "1".
3.  Fetch (with or without cache).
4.  Enter "100 Bullets" in the search box.
5.  Select the record that matches Start Year = 1999, Series = 100 Bullets, Issues = 100, Publisher = Vertigo.
6.  Press "Select" to and confirm the scraping action.
7.  Navigate to the Comics page, and expand the "Library Contents" menu.
8.  Note that "Vertigo" is listed as a publisher.
9.  Search for "100 Bullets" via the filter, or navigate via the "Vertigo" publisher list.
10.  Select the entry for "100 Bullets v1999".
11.  Open the comic that was scraped above.
12.  Note the Publisher is "DC Comics (Vertigo)"
13.  Note The breadcrumb trail is "Comics > DC Comics > 100 Bullets > v1999 > Issue #1
14.  Click on the Publisher hyperlink.
15.  Note you are taken to DC Comics, and the breadcrumb trail is "Comics > Publishers > DC Comics"
16.  Note that "100 Bullets" is not included in the list of comics.
17.  Return to the "Comics" page (doesn't appear to matter how).
18.  Select another comic, and open it.
19.  Note that the "100 Bullets" comic scraped earlier is still displayed.


So I'm not sure what's going on with steps 17. onwards - it doesn't seem to be related to the imprint issue, as I'm striking it with other comics as well.

**Comment by mcpierce** [comment]
@bareheiny Was able to reproduce this. I think this should be fairly easy to fix.

As for steps 17 forward, you filed a bug on this previously (#259). It's related to the browser caching the previous comic's images and showing them until the selected comic is loaded.

**Comment by mcpierce** [comment]
@bareheiny This should now be fixed on develop and will show up in the next release candidate (rc7).

**Comment by bareheiny** [comment]
Looks good :)

**Comment by bareheiny** [comment]
Uhh...it's now working in rc6...

**Describe the bug**
When creating reading lists, it appears that the name is case sensitive - which allows for users to create reading lists with the same name.  For example, "Test reading list" and "test reading list".

**To Reproduce**
Steps to reproduce the behavior:
1. Go to the Comics page (Menu / Comics
2. Click on 'Create a new reading list...'
3. Create a reading list called "Test" and confirm it's creation.
4. Check the reading list list (Show Library Contents menu.  Note reading list may not appear immediately).
5.  Create another reading list (via right-click on the reading list section, or via the 'Create a new reading list' menu on the Comics page.  Name this one "test".
6.  Note that the reading list was created.
7.  Repeat step 4, and note that both "Test" and "test" exist.

**Expected behavior**
I would expect that the second reading list would fail, as "Test" and "test" should be considered the same text.


**Desktop (please complete the following information):**
 - ComiXed version 0.6.0-0.rc6
 - OS: Windows 10
 - Browser name Edge (chromium)
 - Browser version 83.0.478.45

** ComiXed Build Detail **

Source Branch | 79bca8b32567a135f30bf66e8a474358b91cb5a9
-- | --
Build Hostname | fv-az50
Built On | Jun 6, 2020, 5:46:20 PM
**Version | 0.6.0-0.rc6**
Commit Hash | 79bca8b32567a135f30bf66e8a474358b91cb5a9
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jun 6, 2020, 5:26:52 PM
Commit Message | Changed the select reading list dialog to close after adding comics [#315]
Built From Uncommitted Code? | true
Remote Origin | https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@bareheiny It wasn't included in rc6: it was included in rc7.

![Screen Shot 2020-06-07 at 7 54 22 AM](https://user-images.githubusercontent.com/61601/83968015-1ccc5200-a894-11ea-870a-db4628157b3c.png)
