### ISSUE TITLE
Scraping comic with a "/" in the title fails.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#208]
Attempting to scrape "Batman/Planetary: Deluxe Edition" causes a "Failed to get volumes for this comic." toaster to pop up.

Removing the "/" prior to scraping results in the correct issue being returned by the scraper.

**Comment by mcpierce** [comment]
Effective we just need to encode or filter out characters like that when scraping a comic.

**Comment by mcpierce** [comment]
@bareheiny This is suffering from the same problem that #219; i.e., the "/" in the series name is affecting the URL for the request.

**Comment by mcpierce** [comment]
@bareheiny This should now be fixed. Please checkout the latest build and, if this is no longer an issue, please close this ticket out.

**Comment by bareheiny** [comment]
Looks good - the issue in question scraped successfully.
