### ISSUE TITLE
The cover preview in the scraping results window retains the image of the previous comic momentarily.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#209]
As per title.

Steps:

1.  Scrape a comic, and observe the preview cover image the scraping results page.
2.  Scrape another comic, and observe that the preview image from #1 is still shown for a few seconds.

**Comment by mcpierce** [comment]
This isn't a bug: this is a symptom of how the browser is caching images. It's going to show the last image until it retrieves the next image.
