### ISSUE TITLE
"Show details" button - the pane that shows publisher information should return no, or a generic warning, if the publisher information does not exist.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#210]
I have a Publisher called "To be scrapped" as a stop-gap way of identifying which comics are to be scrapped with CX.

After I have veiwed the publisher information (Collections --> Publishers --> DC, click "Show details button) for a real publisher, this information is then displayed when I view the details for a made-up publisher.

Ideally, there should be a generic default used where the publisher information does not exist.

**Comment by bareheiny** [comment]
Doesn't seem to be an issue anymore...is that by design or some weird accident?

**Comment by mcpierce** [comment]
With the new code for navigating the library, that publisher details panel isn't present now. But it's not gone: I just haven't figured out where the best place is to display it. So this bug is in the code, just not evident right now.

**Comment by mcpierce** [comment]
CLosing this as no longer applicable: this issue was against the old pre-0.8 interface.
