### ISSUE TITLE
Scraping - Issue count is one higher than expected in some cases.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#211]
Seems to be related to TPBs.

Steps to replicate:

1.  Scrape a TPB (such as Black Widow: S.H.I.E.L.D.'s Most Wanted)
2.  When the results are returned, observe that the Issues value is 2
3.  Check the ComicVine page for the comic (https://comicvine.gamespot.com/black-widow-shields-most-wanted/4050-95202)
4.  Observe that the issue count is 1.

**Comment by bareheiny** [comment]
Not just TPBs.  The Immortal Hulk is showing 34 in the Issues field, despite issue 33 only coming out in the last week.

**Comment by mcpierce** [comment]
I wonder if this is because CV has fixed an old issue with their APIs where they were underreporting the number of comics in a series? Our CV scraper code adds 1 based on what i read in Cory Banack's CV scraper for CR. 

So if CV has fixed things, then we can remove this addition as well.

**Comment by mcpierce** [comment]
@bareheiny There's now a build with this fix available. Please check it when you have a chance and, if the issue is resolved, please close this ticket.

**Comment by bareheiny** [comment]
Closing - issue counts now look correct (matching against Comic Vine).
