### ISSUE TITLE
When scraping, allow users to move through pages in the cover preview pane.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#212]
At the moment, when scraping the first image in an archive is shown in the preview pane (see image).

I would like to be able to display the next page, as in cases where the first image is not a cover it's difficult to visually confirm the scraping match is correct.

![image](https://user-images.githubusercontent.com/1912425/77862328-2f645280-7277-11ea-8f49-4321af03f5ba.png)

**Comment by mcpierce** [comment]
Nice idea!
