### ISSUE TITLE
Move the search icon (magnifying glass) a fraction to the left of the search text box.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#213]
Minor issue, I believe the magnifying glass is too close to the search box, and should be moved to the left a bit more.

See image:

![image](https://user-images.githubusercontent.com/1912425/77862403-a994d700-7277-11ea-9a99-7ee549d9612f.png)

**Comment by mcpierce** [comment]
@bareheiny I reworked this so that the magnifying glass is a part of the input field. Please check it out and, if it's good, close out this ticket.

**Comment by bareheiny** [comment]
Looks good :)
