### ISSUE TITLE
Administrators can batch scrape comics.

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#2133]
As an administrator, if I have comics that are already associated with a metadata source, then I would like to be able to batch scrape those comics. To do this, I would select the comics to be scraped and then, from the context menu, select a batch scrape menu item. Then the comics would scrape in the background without any further user interaction.

**Comment by cjil** [comment]
I have used Comictagger in the past, which has an "auto tag" feature. The  auto tag will search for the comic using the series, volume and issue information that exists in the tags/filename and then compare the cover image with that on the metadata source (e.g. ComicVine)

This would be extremely helpful with scraping hundreds, or even thousands, of comics. Even if it was only able to search 50 per hour automatically, that still is 1200 per day with no interaction from the user.

Any that are unable to be automatically scraped could then go into a secondary group for manual scraping.

**Comment by mcpierce** [comment]
@cjil There's an existing feature, to scrape a comic series, where CX will use the metadata adaptor to get the metadata for each issue in the library that match the selected series publisher, name, and volume. Is this along the lines of what you're thinking, except to be across all selected comics?

How would you anticipate handling cases where more than one entry comes back for a publisher/name/volume set of data? For example, I've it a lot of issue 1 where ComicVine returned multiple candidates (an issue, a trade paperback, and a second series that all started the same year). Would we leave them as is and let admins manually scrape those?

**Comment by cjil** [comment]
I would suggest that if it returns multiple matches (against comparing covers as well) then it would need to be matched manually by the admin.

I personally have about 30K with varying levels of data quality that currently need to be fixed,. As you can imagine, doing this all manually will take a considerable amount of time (at my current rate of doing it when I have the time, it will take me over a year) even with the series scraping capability (unfortunately, many of the ones I have use the volume number, not the volume year as per CX)

Even if automating this would only find 80% of the metadata, that would then reduce the manual task down to 6K, which is much more manageable.

Additionally, I just used the Series scraping function, and from what I can tell it did nothing.
* The number of unscraped issues did not reduce
* The details in each of the issues did were not changed in any way

I am not sure what it is supposed to do, but it doesn't appear to update any of the issues within the series
