### ISSUE TITLE
Collections breadcrumb not updating

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#214]
The Collections breadcrumb does not appear to update when changing the collections view.

See images.  The first is viewing the Characters collection, the second is viewing the Publisher collection after viewing the Characters one.

Additionally, the clicking on the Collections" item does not appear to do anything - possibly by design?

![image](https://user-images.githubusercontent.com/1912425/77862642-5cb20000-7279-11ea-8bce-bd54482adb0b.png)

![image](https://user-images.githubusercontent.com/1912425/77862662-72272a00-7279-11ea-94f1-64c2fca41023.png)

**Comment by bareheiny** [comment]
Collections has been replaced, I'm not seeing this as an issue any more - can I close this bug?

**Comment by mcpierce** [comment]
@bareheiny Yes.
