### ISSUE TITLE
Collections - Null publishers shown, but not selectable.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#216]
See image.  Comics imported with no publisher information (in my case, there is no xml file in the archive) are showing with a blank publisher in the Publisher Collections screen.

This is accurate - however there is no way to navigate to the comics.

If a publisher exists, a user can simply click on the link - if a publisher does not exist, there is no way to navigate to the set of comics via the Collections menu.

![image](https://user-images.githubusercontent.com/1912425/77863374-668a3200-727e-11ea-917a-c7cacccb4904.png)

**Comment by mcpierce** [comment]
Yeah, we can modify that to show "UNKNOWN" so you can click on it.

**Comment by mcpierce** [comment]
Closing this since the collections component is going to go away.
