### ISSUE TITLE
How to Know When Comic Has A Metadata Source ID?

### ISSUE THREAD

**Issue by dylan-k** [comixed/comixed#2168]
I have a question about a passage in the comixed wiki, "[If The Comic Has A Metadata Source ID](https://github.com/comixed/comixed/wiki/Scraping-Comics#if-the-comic-has-a-metadata-source-id)"

Where does Comixed expect the ID to be located? If I'm bringing comics over from another system, this would help to know so I can prepare them for what Comixed expects to see

**Comment by mcpierce** [comment]
This is a good question for the mailing list.
