### ISSUE TITLE
Collections - sort by field value

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#217]
I'm not sure what the sort order is at the moment, but ideally the items in the Collections lists would be sorted by their value.

Unsorted, the items are difficult to navigate - especially when a library contains a number of values in the relevant field.

Currently, Publisher is sorted as follows:

To be scrapped 
DC Comics
IDW Publishing
Marvel
Arcana Studio
Dark Horse Comics
Avatar Press
Image
Homage Comics

Ideally it would be sorted:

Arcana Studio
Avatar Press
Dark Horse Comics
DC Comics
IDW Publishing
Image
Marvel
To be scrapped 

I can't think of any instances where a user would want to change the sort order, so I don't believe there is any need for dynamic sorting of any kind.

**Comment by mcpierce** [comment]
We can update the collections tables with a sort icon so you can control the sorting by name or comic count.

**Comment by mcpierce** [comment]
Closing this ticket since we no longer have a collections list page.
