### ISSUE TITLE
Cannot select multiple comics in any view: "Failed to select comic book... ERROR"

### ISSUE THREAD

**Issue by Armandur** [comixed/comixed#2173]
**Describe The Bug**
Selecting multiple comic shows comics being selected, but the error `"Failed to select comic book..."` shows every time. No "For selected comics" options are available in the menu.

Using the select all box only shows the error` "Failed to select comic book**s**..."`, but no boxes are shown as selected, except for the select all box.

In the log, nothing is logged when selecting a box, but when de-selecting logs like this:
```
2024-10-12T21:13:32.588+02:00  INFO 14 --- [ComiXed] [nio-7171-exec-2] o.c.r.c.ComicBookSelectionController     : Removing comic selection:comic book id=1
```

For using the select all box, this is logged:
```
2024-10-12T21:14:25.685+02:00  INFO 14 --- [ComiXed] [nio-7171-exec-5] o.c.r.c.ComicBookSelectionController     : Updating multiple comic books selection: MultipleComicBooksSelectionRequest{coverYear=null, coverMonth=null, archiveType=null, comicType=null, comicState=null, unscrapedState=false, searchText='null', selected=false}
2024-10-12T21:14:28.316+02:00  INFO 14 --- [ComiXed] [nio-7171-exec-7] o.c.r.c.ComicBookSelectionController     : Updating multiple comic books selection: MultipleComicBooksSelectionRequest{coverYear=null, coverMonth=null, archiveType=null, comicType=null, comicState=null, unscrapedState=false, searchText='null', selected=true}
```
**To Reproduce The Bug**
Select multiple comics or select the select all box.

**Expected Behavior**
Multiple comics being selected and being able to use menu options for multiple comics.

**ComiXed Runtime Environment**

 - [ ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [X] Docker (if so, please select the host OS) **UnRaid**

**Browser (If A Web Issue)**

 - [ ] Chrome
 - [X] Firefox
 - [ ] Safari
 - [ ] Other (if so, please provide a name)

**ComiXed Build Detail:**

> The code was built from a branch named 226a1a62f0fdda96774d0be48f02498e03acb423
> The code was built on October 12, 2024 at 5:58:48 PM GMT+2.
> Code was built on a machine named fv-az738-464.
> The code was marked with a Build version of 2.2.0-1.
> The latest commit hash on the source branch is 226a1a62f0fdda96774d0be48f02498e03acb423.
> This commit was created on October 12, 2024 at 5:54:38 PM GMT+2.
> Commit Message
> Changed the release version to v2.2.0-1 [#2157]
> Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
> The branch does not contain uncommitted changes.
> This branch is tracking the remote branch https://github.com/comixed/comixed
> The database URL being used is jdbc:h2:file:~/.comixed/comixed
> Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v6.1.106-Unraid (amd64) 

**Screenshots**

**Additional Context**

**Comment by Armandur** [comment]
Loading any page that is supposed to load comics (as well as the home page) also displays the error message:
`Failed to load current comic book selections...`

**Comment by mcpierce** [comment]
@Armandur Hrm, is your database one with an existing library or is this a new setup? And how many comics do you have in your library?

**Comment by Armandur** [comment]
Existing library, though I started it today, currently about 600 comics, though maybe half of that processed with scraped metadata.

**Comment by Armandur** [comment]
I tried pointing the docker image to another config directory and it seems to work with a fresh database, so it might've been borked during updating the docker or something. It isn't a great loss to me to start over.

**Comment by Armandur** [comment]
I'll keep the database if you'd like too look at it.

**Comment by mcpierce** [comment]
@Armandur If you open the DevTools for your browser, what do you see in the Network tab and in the Console tab when you try to select comics? Please do this:
1. In DevTools, please go to Network and clear the context.
2. In the browser, click the select checkbox.

You *should* have an entry that looks like this:
<img width="888" alt="image" src="https://github.com/user-attachments/assets/aec12b0d-c4ef-4432-bce5-997e18c79d03">

<img width="859" alt="image" src="https://github.com/user-attachments/assets/512fcc2b-704d-413d-a8fb-d22255e4a495">

Then go to the Console and see if there are any errors posted there that mention network requests? You can ignore any that look like this:
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/ec1a18b5-5c66-4953-aaf9-770f04666a63">

**Comment by Armandur** [comment]
Huh, having switched back to the old app-config again it now works again... All polyfills succeed according to the network tab.

**Comment by mcpierce** [comment]
@Armandur So is the bug not reproducible?

**Comment by Armandur** [comment]
Not currently. My gut-feeling now is that this might've been a folder/user/permissions thing pertaining to UnRaid.

**Comment by mcpierce** [comment]
@Armandur Okay. If you want, you can close this for now and, if it comes up again or someone else hits the issue, we can reopen it.

**Comment by Armandur** [comment]
Do so :)

**Comment by Armandur** [comment]
Fine by me :) (Didn't realise until now that that was an option available to me here on github)
