### ISSUE TITLE
If pressing the "Find files to import..." while rows of found comics are already listed every second row is drawn above the modal/form

### ISSUE THREAD

**Issue by Armandur** [comixed/comixed#2174]
**Describe The Bug**
If pressing the "Find files to import..." button again while having previous results in the list, every other row is drawn above the modal/form where you select the directory and amount of files.

**To Reproduce The Bug**
1. Press "Find files to import..." and search for enough files to approximately pass the middle of the screen.
1. Press it again

**Expected Behavior**
The form should be drawn over all rows.

**ComiXed Runtime Environment**

 - [ ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [X] Docker (if so, please select the host OS) **UnRaid**

**Browser (If A Web Issue)**

 - [ ] Chrome
 - [X] Firefox
 - [ ] Safari
 - [ ] Other (if so, please provide a name)

**ComiXed Build Detail:**
> The code was built from a branch named 226a1a62f0fdda96774d0be48f02498e03acb423
> The code was built on 2024-10-12T15:58:48.000+00:00.
> Code was built on a machine named fv-az738-464.
> The code was marked with a Build version of 2.2.0-1.
> The latest commit hash on the source branch is 226a1a62f0fdda96774d0be48f02498e03acb423.
> This commit was created on 2024-10-12T15:54:38.000+00:00.
> Commit Message
> Changed the release version to v2.2.0-1 [#2157]
> Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
> The branch does not contain uncommitted changes.
> This branch is tracking the remote branch https://github.com/comixed/comixed
> The database URL being used is jdbc:h2:file:~/.comixed/comixed
> Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v6.1.106-Unraid (amd64)

**Screenshots**
![bild](https://github.com/user-attachments/assets/16d19bc6-9e22-48d6-b5fd-edb08537260c)

**Additional Context**

**Comment by mcpierce** [comment]
@Armandur I was able to immediately reproduce this one. I'll get to working on it straight away.

**Comment by mcpierce** [comment]
@Armandur  I've opened #2175 with a fix to address this issue. I'll put out an update in about a week with it and any other bugfixes.
