### ISSUE TITLE
New docker update completely broke the docker 

### ISSUE THREAD

**Issue by Uplinkpro** [comixed/comixed#2179]
**Describe The Bug**

After updating to recent docker, on boot receive:

bash: /app/comixed-release-2.2.1-1/bin/run.sh: No such file or directory 

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:

1. Create docker
2. Attempt to boot docker

**Expected Behavior**

Docker boots up, then creates appdata files for docker to run.

**ComiXed Runtime Environment**

 - [ ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [ x] Docker - Unraid

**ComiXed Build Detail:**
comixed-release-2.2.1-1

**Comment by mcpierce** [comment]
I've put up a fix for this [here](https://github.com/comixed/comixed/pull/2180) and will put out a docker release shortly. If that fixes the issue, please close this issue. And thanks for reporting the bug!
