### ISSUE TITLE
The ability to write metadata without using HTML text tags

### ISSUE THREAD

**Issue by fanzines** [comixed/comixed#2183]
Currently I used Komga to read my comics managed by Comixed. It currently does not have the ability to handle html text tags and has said it will never in the future. So I would like the ability to write metadata (specifically the summary section) without using these tags. It would be beneficial for Komga users and potentially other applications that don't process html tags. Either writing the metadata similar to comictagger (so doing the formatting in the metadata without html tags) or just writing it as a block of text with no formatting at all would work. Obviously the first option would be preferable but if not possible the second as a option would work.

Here is an example of how the text currently looks when being read through applications that don't handle html tags.

![image](https://github.com/user-attachments/assets/0bb33c15-a9d7-476a-a343-2f61d6a36167)

**Comment by mcpierce** [comment]
@fanzines This is a great idea. I'll include it for the next version.

**Comment by mcpierce** [comment]
@fanzines This feature is now completed and will be in the next major release (v2.3) which is planned for the end of December.
