### ISSUE TITLE
When using the Docker version page ordering will not save

### ISSUE THREAD

**Issue by fanzines** [comixed/comixed#2184]
**Describe The Bug**
Right now after changing the order of pages and hitting save the order will immediately revert back to how it originally was. If you have the page renaming rule set up it won't rename them either. The only way to rename them is through rebuilding the archive. This though still won't save the page order.

**To Reproduce The Bug**
1. Go to the pages section of a comic and move pages in some new order
2. Attempt to save the page order using the save page ordering button
3. Most of the time you will immediately see the order snap back to the original order. Sometimes it will happen once you click off the comic and then reenter the entry again

**Expected Behavior**
Expected it to rename and save the pages in the order I had moved them in. 

**ComiXed Runtime Environment**

 - [ ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [X] Docker through DSM on a Synology NAS

**ComiXed Build Detail:**

The code was built from a branch named ab9f23175db635cc904afcc5c09caf7200f95d7b
The code was built on 2024-10-22T11:50:54.000+00:00.
Code was built on a machine named fv-az1144-789.
The code was marked with a Build version of 2.2.1-2.
The latest commit hash on the source branch is ab9f23175db635cc904afcc5c09caf7200f95d7b.
This commit was created on 2024-10-22T11:38:32.000+00:00.
Commit Message
Changed the release version to v2.2.1-2 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed
Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v4.4.302+ (amd64)

**Additional Context**
I checked both the console and log as well for any additional info. Only thing I noticed in the log related was this line 2024-11-03T23:25:26.416Z  INFO 14 --- [ComiXed] [http-nio-7171-exec-8] o.c.rest.comicbooks.ComicBookController  : Updating page order: comic id=1

**Comment by mcpierce** [comment]
@fanzines This is now merged and will be a part of the next release. Please feel free to close this once you've verified it's working for you.
