### ISSUE TITLE
Using the filter in "Unscraped Comics" returns all comics that match filter regardless of scraped status

### ISSUE THREAD

**Issue by cjil** [comixed/comixed#2186]
**Describe The Bug**
While in the "Unscraped Comics" section of the application, using the filter and searching for a series name it returns all series that match the name whether they have been previously scraped or not

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Go to "Unscraped Comics"
2. Click the filter
3. Enter a series name that has issues that have previously been scraped

**Expected Behavior**
The filter only returns comics that have not been scraped.

**ComiXed Runtime Environment**

 - [ ] Windows
 - [ ] Linux (any distro)
 - [ ] MacOS
 - [X] Docker (Synology NAS)

**Browser (If A Web Issue)**

 - [ ] Chrome
 - [ ] Firefox
 - [ ] Safari
 - [X] Other (Floorp)

**ComiXed Build Detail:**

The code was built from a branch named ab9f23175db635cc904afcc5c09caf7200f95d7b
The code was built on 2024-10-22T00:50:54.000+00:00.
Code was built on a machine named fv-az1144-789.
The code was marked with a Build version of 2.2.1-2.
The latest commit hash on the source branch is ab9f23175db635cc904afcc5c09caf7200f95d7b.
This commit was created on 2024-10-22T00:38:32.000+00:00.
Commit Message
Changed the release version to v2.2.1-2 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:postgresql://db:5432/comixed
Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v4.4.302+ (amd64)

**Screenshots**
![image](https://github.com/user-attachments/assets/f98d6fea-55b9-4433-961d-93a964c73ae0)
(note that the issues shown that have a "Cover Date" have previously been scraped and will not show in the unscraped list normally; only when using the filter)

**Comment by mcpierce** [comment]
@cjil  There's a fix for this and it will be included in the next release. Please check that things are working and, if so, you can close this bug as fixed.
