### ISSUE TITLE
Option to have comics with the character ' have that character removed instead of being replaced with _

### ISSUE THREAD

**Issue by fanzines** [comixed/comixed#2187]
Currently when organizing files comixed will handle any files  or series with the character ' by replacing it with _. This is perfectly fine but personally I would prefer the option to just remove the ' all together. Example I had the comic New York World's Fair Comic. When organzing and renaming comixed made the series folder and the file into New York World_s Fair Comic. I would just like the option to have it save as New York Worlds Fair Comic instead. Its a small thing but for my organizing purposes it fits better. I know some operating systems would accept the ' but I feel the better universal change is to just have the option to remove it all together.

**Comment by mcpierce** [comment]
Interesting idea. Do you think it would work to have the feature be an on/off switch that removes characters that are otherwise replaced? So it would *either* replace the character with an underscore (off mode) or delete the character from the filename entirely (on mode)?

**Comment by fanzines** [comment]
Yeah I think that would probably be the simplest solution. Its very minor but aesthetically just deleting those characters instead of replacing them would look better. So giving people the option seems like a great idea

**Comment by mcpierce** [comment]
@fanzines In looking at this, I honestly can't think of a reason to not just go ahead and remove the single or double quote from the filename. I know that we can escape them but I'd rather keep the code simple. So I'm skipping the configuration option and just making it the default behavior to remove those characters.

This will be included in the next release at the end of the month.
