### ISSUE TITLE
Unable to scrape ½ issue.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#219]
Steps to replicate:

1.  Scrape a comic with a ½ issue number.
2.  Observe that, while the series is found, no issue cover is shown and the "select" and "back" buttons are not shown either.

Second attempt:

1.  Change the issue number to 0.5
2.  Observe that issue 5 is returned.

Third attempt:

1.  Change the issue number 1/2
2.  Observe that, while the series is found, no issue cover is shown and the "select" and "back" buttons are not shown either.
3.  Observe that a "Failed to get issue" toaster is displayed.

**Comment by mcpierce** [comment]
Thanks for the report! I'll dig into it for this release.

**Comment by mcpierce** [comment]
@bareheiny So the problem is that the issue number is part of the REST API endpoint for the backend request. So when you put "1/2" in as the issue number the REST API treats it as two parts of the request rather than as a single unit of data.

So we need to either pull the issue number out of the REST API and put it into the request body, or else find a way to encode it so the slash doesn't confuse the backend.

**Comment by mcpierce** [comment]
I was able to get this to work by using "½" as the issue number rather than "1/2". Ugh, it's going to be an extreme edge case to try and support this.

**Comment by mcpierce** [comment]
@bareheiny This code is merged. The issue number, due to the way things are encoded on the ComicVine side, will need to be the "½" character for now. We might be able to come up with a better solution but this appears to work for me.

Please try it and, if it works, feel free to close this issue.

**Comment by bareheiny** [comment]
That works great for me - so closing.

The only problem I can foresee is that it's not always easy to get special characters into the number field.  Such as "½" or "∞" (yeah...so Malibu had a few issues numbered this way).

I doubt that this is a big enough problem to warrant spending large amounts of time on.  Is it possible to add special characters to a drop-down list somehow that could be used to populate the number field if necessary?
