### ISSUE TITLE
Option to exclude a list of publishers from scraping results

### ISSUE THREAD

**Issue by cjil** [comixed/comixed#2194]
**Is your feature request related to a problem? Please describe.**
Whenever I am scraping, I am often frustrated by certain publishers appearing in the results, despite that publisher not being part of either the query or my library (quite often this is Panini)

**Describe the solution you'd like**
I would like a configurable list of publishers that can be excluded from the results.This would also make scraping quicker and easier as it would not have as many clashes, with an option to turn on/off the filter from the scraping page.

**Comment by mcpierce** [comment]
@cjil I would have to verify it, but I don't think it would speed up the scraping process at least with regards to fetching results. The online sources like ComicVine don't provide for ignoring records that match the query, at least as far as I'm aware. 

The server could definitely filter the results after retrieving them, though.

**Comment by cjil** [comment]
@mcpierce I should clarify. I didn't expect it to speed up the collecting of the results, but in the verification process as there are unlikely to be as many clashes (e.g. Marvel & Panini), which would also enable the automatic selection of a single match to activate more frequently.

**Comment by mcpierce** [comment]
@cjil Would it fulfill this request if, rather than filtering out specific publishers, the backend instead only returned entries where the publisher rougly matches what was entered on the scraping page?

IOW, if I put "Marvel" as the publisher, then if that filter checkbox is set only include entries where the publisher has the word "Marvel" in its name.

**Comment by mcpierce** [comment]
@cjil Also, this sounds likes a great topic to bring up on the mailing list. I'd love to get some ideas on how users would want to do this feature, as I think it's a great idea. Would you mind starting a thread about it on the comixed@freelists.org mailing list, please?

**Comment by cjil** [comment]
Not a problem at all. I have just sent it out.
