### ISSUE TITLE
Loading of page hashes stops and does not recover upon restarting the application

### ISSUE THREAD

**Issue by cjil** [comixed/comixed#2201]
**Describe The Bug**
When restarting the application, the batch process for loading page hashes remains but no longer appears to update. Checking the database I cannot see any evidence of the process progressing

**To Reproduce The Bug**
1. Import a group of comics
2. While the load page hash batch process is running, stop the application
3. Restart the application
4. Go to the "Comic Processing Status" page; there are no processes running
5. Logged into the database, and ran ```select * from batch_step_execution;``` Ran this SQL a few times and did not see any change in the output indicating that the process was indeed running.

**Expected Behavior**
The load page hash process continues to run and output progress to the "Comic Processing Status" page after restarting the application

**ComiXed Runtime Environment**

 - [ ] Windows
 - [X] Linux (any distro)
 - [ ] MacOS
 - [X] Docker (if so, please select the host OS)

**Browser (If A Web Issue)**

 - [ ] Chrome
 - [ ] Firefox
 - [ ] Safari
 - [X] Other (Zen Browser)

**ComiXed Build Detail:**

The code was built from a branch named 6a388a7644f82f27f3ebe71241e7aad626e70a5d
The code was built on 2024-11-09T11:04:49.000+00:00.
Code was built on a machine named fv-az700-429.
The code was marked with a Build version of 2.2.2-1.
The latest commit hash on the source branch is 6a388a7644f82f27f3ebe71241e7aad626e70a5d.
This commit was created on 2024-11-09T11:00:43.000+00:00.
Commit Message
Changed the release version to v2.2.2-1 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:postgresql://db:5432/comixed
Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v4.4.302+ (amd64)

**Additional Context**
I was able to trigger a restart the process by removing the previous record from the database (note there may be a syntax error or two in the below, as I have written it to be, hopefully, reusable. The actual query I ran hardcoded the job_execution_id and step_execution_id.)
```
begin;
delete from batch_step_execution_context where step_execution_id in (select step_execution_id from batch_step_execution where
job_execution_id in (select job_execution_id from batch_job_execution where job_instance_id in (select job_instance_id from batch_job_instance where job_name='loadPageHashesJob' )));
delete from batch_step_execution where job_execution_id in (select job_execution_id from batch_job_execution where job_instance_id in (select job_instance_id from batch_job_instance where job_name='loadPageHashesJob' ));
delete from batch_job_execution_params where job_execution_id in (select job_execution_id from batch_job_execution where job_instance_id in (select job_instance_id from batch_job_instance where job_name='loadPageHashesJob' ));
delete from batch_job_execution_context where job_execution_id in (select job_execution_id from batch_job_execution where job_instance_id in (select job_instance_id from batch_job_instance where job_name='loadPageHashesJob' ));
delete from batch_job_execution where job_instance_id in (select job_instance_id from batch_job_instance where job_name='loadPageHashesJob' );
commit;

```

EDIT: I just had to rerun the SQL commands this morning because the docker container restarted overnight for some reason, and can confirm that the command above has no syntax errors.

**Comment by mcpierce** [comment]
@cjil I've added a fix for this and will release it in this week's bugfix update. Please feel free to close this ticket when the bug is verified as fixed.

**Comment by cjil** [comment]
The last couple of days I have not needed to run the SQL to kick it off again, so I assume that it is working as intended.
Thank you.
