### ISSUE TITLE
Unable to scrape issues with a negative number

### ISSUE THREAD

**Issue by cjil** [comixed/comixed#2206]
**Describe The Bug**
Issues that have a negative number are unable to be retrieved using scraping

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Open an issue that has a negative number (e.g. Spider-Man (1990) #-1
2. Ensure the details are correct for scraping
3. Scrape the data
4. The record that is returned is for issue number 1, not -1

**Expected Behavior**
The record that is returned is that for issue number -1

**ComiXed Runtime Environment**

 - [ ] Windows
 - [X] Linux (any distro)
 - [ ] MacOS
 - [X] Docker (if so, please select the host OS)

**Browser (If A Web Issue)**

 - [ ] Chrome
 - [ ] Firefox
 - [ ] Safari
 - [X] Other (Zen)

**ComiXed Build Detail:**

The code was built from a branch named 6a388a7644f82f27f3ebe71241e7aad626e70a5d
The code was built on 2024-11-09T11:04:49.000+00:00.
Code was built on a machine named fv-az700-429.
The code was marked with a Build version of 2.2.2-1.
The latest commit hash on the source branch is 6a388a7644f82f27f3ebe71241e7aad626e70a5d.
This commit was created on 2024-11-09T11:00:43.000+00:00.
Commit Message
Changed the release version to v2.2.2-1 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:postgresql://db:5432/comixed
Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v4.4.302+ (amd64)

**Comment by mcpierce** [comment]
@cjil I've created a fix for this and will include it in this week's bugfix release. If it solves the problem, please feel free to close this ticket.

**Comment by cjil** [comment]
@mcpierce still does not bring back the issue. It keeps trying to change it to issue 1.

Series: Spider-Man
Volume: 1990
Issue: -1

**Comment by mcpierce** [comment]
![image](https://github.com/user-attachments/assets/3e801b4e-53b2-4347-ba4b-a7c475ccc160)

Please verify that you're using the latest release. I just tested on my instance of the latest release by scraping a comic as Spider-Man -1 and got the above screen shot, which is the mini one issue.

**Comment by cjil** [comment]
The code was built from a branch named b7713d706118d5a4c7edb6c23b06d07cc8950b74
The code was built on 2024-11-24T10:51:14.000+00:00.
Code was built on a machine named fv-az985-168.
The code was marked with a Build version of 2.2.3-1.
The latest commit hash on the source branch is b7713d706118d5a4c7edb6c23b06d07cc8950b74.
This commit was created on 2024-11-24T10:29:17.000+00:00.
Commit Message
Changed the release version to v2.2.3-1 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:postgresql://db:5432/comixed
Using Java 17.0.2+8-86 (Oracle Corporation) running on Linux v4.4.302+ (amd64)

![Screenshot From 2024-11-25 14-46-29](https://github.com/user-attachments/assets/7b76d9b5-00de-4a76-b1dc-e83457953fcc)

**Comment by mcpierce** [comment]
Is it possible your browser's holding onto previously cached data? 

My results in trying to recreate this locally:

I put in the following values when scraping:
<img width="2373" alt="image" src="https://github.com/user-attachments/assets/8ab9b297-188a-4cd9-a5a5-e248cc233b4f">

The results returned:
<img width="2342" alt="image" src="https://github.com/user-attachments/assets/87a86e78-7882-41fb-ad5d-7393bf287556">

The detail request from the browser developer toolkit when I click on the first volume returned shows it's requesting issue "-1" from volume "4421" from comic vine:
<img width="850" alt="image" src="https://github.com/user-attachments/assets/1fa514e9-6fd4-434f-94f3-fefdf12a83e7">

And the link for the image it retrieves is:
<img width="635" alt="image" src="https://github.com/user-attachments/assets/c3a259d7-2a32-4a42-947f-ff0c4e2fd225">

[link](https://comicvine.gamespot.com/a/uploads/scale_medium/0/4/51583-4421-68477-1-spider-man.jpg)

When I go to ComicVine I get this link for the issue:

https://comicvine.gamespot.com/spider-man--1/4000-68477/

You can see that the issue id (68477) matches the issue id in the cover link above. And, clicking on the volume link on this page, it goes to:

https://comicvine.gamespot.com/spider-man/4050-4421/

which is volume 4421, from the browser link above.

Build details:
```

The code was built from a branch named release/2.2
The code was built on 2024-11-24T21:33:02.000+00:00.
Code was built on a machine named mcpiercebookpro.lan.
The code was marked with a Build version of 2.2.3-1.
The latest commit hash on the source branch is b7713d706118d5a4c7edb6c23b06d07cc8950b74.
This commit was created on 2024-11-24T21:29:17.000+00:00.
Commit Message
Changed the release version to v2.2.3-1 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch git@github.com:comixed/comixed.git
The database URL being used is jdbc:postgresql://localhost:5432/comixed
Using Java 17.0.10+11-LTS-240 (Oracle Corporation) running on Windows 10 v10.0 (amd64)
```

**Comment by mcpierce** [comment]
I just realized that the build I'm using to verify is not the official one but a local build of that same code.  So I just installed the official release:

```

The code was built from a branch named b7713d706118d5a4c7edb6c23b06d07cc8950b74
The code was built on 2024-11-25T02:51:14.000+00:00.
Code was built on a machine named fv-az985-168.
The code was marked with a Build version of 2.2.3-1.
The latest commit hash on the source branch is b7713d706118d5a4c7edb6c23b06d07cc8950b74.
This commit was created on 2024-11-25T02:29:17.000+00:00.
Commit Message
Changed the release version to v2.2.3-1 [#2157]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:postgresql://localhost:5432/comixed
Using Java 17.0.10+11-LTS-240 (Oracle Corporation) running on Windows 10 v10.0 (amd64)
```

I then cleared my browser cache and rescraped that comic with the same details. Results were the same as above: I got Spider-man volume 1990 issue number -1 as the candidate.

**Comment by cjil** [comment]
I cleared the browser cache, even used a different browser that I have never used for comixed before and it had the same result.

I then disabled the scraping cache, and then it brought back the correct issue. Thank you.
