### ISSUE TITLE
Multiple SLF4j JARs in build

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#238]
The following was reported on the developer mailing list:

```
SLF4J: Class path contains multiple SLF4J bindings.

SLF4J: Found binding in [jar:file:/D:/.scripts/comixed-app-pre-release.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: Found binding in [jar:file:/D:/.scripts/comixed-app-pre-release.jar!/BOOT-INF/lib/log4j-slf4j-impl-2.11.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

**Comment by BRUCELLA2** [comment]
I've been looking at this issue. If we remove the dependency to spring-boot-starter-log4j2 in the comixed main pom, there is no longer a multiple SLF4J bindings

**Comment by mcpierce** [comment]
@BRUCELLA2 Will that remove the ability to use the @Log4j2 annotations in the Java code?

**Comment by BRUCELLA2** [comment]
I don't see any problem. The annotation seems to work. 
To be sure, we can rather add exclusion of spring-boot-starter-logging on spring-boot-starter-web and let spring-boot-starter-log4j2.

**Comment by mcpierce** [comment]
@BRUCELLA2 I'm happy with either solution.
