### ISSUE TITLE
Progress or processing indicator for library re-scan.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#239]
As a user, I would like a visual queue indicating that a library re-scan is underway.

At the moment, it appears the only way to verify that a re-scan is happening is by watching the output log.

**Comment by mcpierce** [comment]
In the status bar there's a counter that tells you how many comics remain to be processed:

![Screen Shot 2020-04-13 at 9 13 17 AM](https://user-images.githubusercontent.com/61601/79122960-065bbb80-7d67-11ea-9980-199e15696a4c.png)

It should output the number of comics in the task queue waiting to be processed.

**Comment by bareheiny** [comment]
Luckly I didn't close this.

The Processing count is not changing - it's still 0, even though I initiated a re-scan, and the CMD window is showing a mix of "getting task adaptor=RESCAN_COMIC", "Rescaning comic: id=" and "Updating page metrics: " messages.

**Comment by mcpierce** [comment]
I'm going to close this as I've re-implemented the status bar and put a new spin on this output. If, after 0.9 is released, there are problems we can open a new ticket.
