### ISSUE TITLE
Rescan and Export library button text no longer fits within the button image.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#241]
Apologies, they're not buttons...but I'm not sure what they're called.

I suspect that this has happened since the consolidation option was added - but the action text no longer fits in the action image.

See below:

![Comixed - Admin - Library](https://user-images.githubusercontent.com/1912425/79091795-c87c8880-7da2-11ea-875e-c98027928b3f.PNG)

**Comment by mcpierce** [comment]
Yeah, I'm planning to rework the admin page to be more visually appealing.

**Comment by mcpierce** [comment]
This is now merged. Please checkout the latest build and, if all is well, close out this ticket.

**Comment by bareheiny** [comment]
I'm not seeing any changes these areas.

**Comment by mcpierce** [comment]
Looks like the build failed to run. I'm re-running it now.

**Comment by mcpierce** [comment]
The re-run build completed and should have the fix now.

**Comment by bareheiny** [comment]
Looks good.  Closing.
