### ISSUE TITLE
Attempting to log in while a re-scan is occuring is delayed.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#243]
I have a library re-scan running, and opened the web interface to log in and check something.

On pressing the "log in " button, there was a significant delay in the log in occuring...as there is no indication that the log in is occuring, it is easy for a user to assume the button click did not work, or that the log in is not being attempted.

Not sure how this could be handled - maybe greying out the log in buttons once clicked, and only restoring them if the log in attempt failed?

**Comment by bareheiny** [comment]
Note - on a subsequent log in attempt, the log in was almost instantaneous.

The delay may have been a one-off, but I'm sure I've seen this behavour before.

**Comment by mcpierce** [comment]
It's possible to disable the login button while the login request is being processed.

**Comment by mcpierce** [comment]
@bareheiny I'm going to close this since it applied to the old UI codebase. If we see the same behavior happen with the new frontend we can open a new ticket.
