### ISSUE TITLE
Edge tab title is "library-page.title"

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#252]
As per subject.

Only appears once I navigate to the "Library \ Comics" section.

**Comment by mcpierce** [comment]
@bareheiny Is this a reproducible bug or did it happen once? I'm not able to reproduce it locally, working off of the develop branch.

**Comment by bareheiny** [comment]
@mcpierce yup - I've been seeing it for a while, and it's consistent.  

I just checked my other machine, and it's showing the same tab title - is happening in both Edge (the new shiny, chromium version) and Chrome.

Edge:
![image](https://user-images.githubusercontent.com/1912425/80648418-42f81880-8ac4-11ea-8796-4dc527023c29.png)

Chrome:
![image](https://user-images.githubusercontent.com/1912425/80648368-2eb41b80-8ac4-11ea-9fe1-8a664776d25c.png)

**Comment by mcpierce** [comment]
Oh that’s the browser title. I was looking in the page itself.
-- 
Sent from Gmail Mobile

**Comment by mcpierce** [comment]
@bareheiny Okay, this should be fixed now. Please take a look and, if all is well, you can close this ticket.

**Comment by bareheiny** [comment]
Looks good now :)

**Comment by bareheiny** [comment]
Seeing this again.

The admin page has a title of "library-admin-page.title".

**Comment by mcpierce** [comment]
@bareheiny Okay, this should be fixed now as well.

**Comment by bareheiny** [comment]
Looks good - closing again.
