### ISSUE TITLE
Using invalid credentials to log in returns a "Successfully logged out" toaster message.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#270]
As per title.

I attempted to log into CX using an invalid user / password combination, and noted the "Successfully logged out" message was displayed, rather than the expected red (unsure of exact message) toaster.

**Comment by BRUCELLA2** [comment]
I took a quick look at this bug.
It seems that when the username/password combination is invalid, the back returns a 401 error.
The 401 error is processed in hrx.interceptor and calls the startLogout method of the authenticationAdaptor.

I think we can call a new method (authenticationFailed) when error 401 is returned. This method can then dispatch the AuthLoginFailed action and we need to add the @Effect for authentication that fails.

**Comment by mcpierce** [comment]
@BRUCELLA2 I think you're spot on with that. Would you be able to provide a PR to do that?

**Comment by BRUCELLA2** [comment]
@mcpierce i think i can provide a PR, yes.

**Comment by mcpierce** [comment]
@bareheiny A fix was provided by @BRUCELLA2 -- can you verify on the next build that this bug is fixed and close the ticket? Thanks.

**Comment by bareheiny** [comment]
Looks good, closing.
