### ISSUE TITLE
Filter to show comics marked for deletion.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#284]
As a user, I would like to be able to easily access a list of comics that are marked for deletion.

This list should include functionaly to un-mark comics for deletion - and should (if possible) refresh once a comic has been un-marked.

Ideally, this list would also be referenced when a user beings a library consolidation (especially with "Delete The Physical Comic Files" ticked).

**Comment by mcpierce** [comment]
@bareheiny This is now integrated into the develop branch.
