### ISSUE TITLE
Duplicate pages - "Succesfully marked for deletion" toaster showing incorrect page count.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#287]
Actions:

1.  Navigate to Duplicate Pages page.
2.  Select any single image, and mark it for deletion (noting the number of pages to be deleted)
3.  Note the confirmation toaster indicates every duplicate page is to be deleted.
4.  Hover over duplicate pages that were not selected for deletion, and note that they have not been marked for deletion.

Expected result:

The confirmation toaster should only indicate that the selected pages are to be deleted.

This also applies for unmarking.  The steps are essentially the same, but select a page that was marked for deletion - the confirmation toaster will indicate that all duplicate pages were succesfully unmarked.

**Comment by mcpierce** [comment]
The issue is that the toaster is showing the number of duplicate pages in the system rather than the number of pages just marked as deleted. So if there are nine duplicate pages, and you mark one that shows up 100 times in your library, the toaster will say that it marked nine pages for deletion.

**Comment by bareheiny** [comment]
I had a different experience.

I have ~222 duplicate pages, not sure of the distinct count.  I marked one page (that appeared three times) for deletion.  The toaster said that ~222 pages were marked for deletion (or unmarked depending on what I was doing).

**Comment by mcpierce** [comment]
@bareheiny Yeah, that 222 is the number of uniquely duplicate (there's an oxymoron) pages in your library. That popup is using that number instead of the number of times the page you just marked occurs.

**Comment by mcpierce** [comment]
@bareheiny This is fixed on develop and will show up in the next 0.6 release. Please close this when you have a chance to verify things.

**Comment by bareheiny** [comment]
Just confirming that the change removes the reference to the page count?  So now the toaster only says something like "pages successfully marked for deletion", rather than "x pages were successfully marked for deletion"?

**Comment by mcpierce** [comment]
@bareheiny That's correct. Since the request is marking more than one page hash as deleted (and the same for the blocking code), and the response is the list of all duplicate pages, there's no easy way right now for it to decide how many of those pages were changed.

**Comment by bareheiny** [comment]
All good.

Closing now :)
