### ISSUE TITLE
Main menu pop-out cannot be dismissed.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#297]
May be a browser issue - if so, can be closed.

I've noticed that whenever I click the main menu (it pop-outs the Library / Admin / Account / Help and Logout options), I cannot dismiss it.

The only course of action is to use one of the options - usually Library / Comics.

**Comment by mcpierce** [comment]
I hit that too and have been meaning to look into it. We'll fix it for the 0.6 release.

**Comment by mcpierce** [comment]
@bareheiny There's now a fix for this on develop and will show up in the 0.6.0-0.rc5 release this weekend. Please close after you've had a chance to verify it.

**Comment by bareheiny** [comment]
Took me a few seconds to figure it out, but I can now close the pop-out menu if I need to.

Probably worth noting the closure method somewhere in a help file or user guide.
