### ISSUE TITLE
Admin / Users page not showing correct label text

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#307]
For example the new user button is showing "ADMIN.USER-EDITOR.LABEL.NEW-USER".

Account preferences (Details) menu is doing the same thing.

**Comment by mcpierce** [comment]
@bareheiny This is now fixed on develop and will show up in the next release candidate (rc7).

**Comment by bareheiny** [comment]
Admin page looks good on rc7, but the Preferences items on Account \ Details shows the following:


comicvine.api-key | 
import.directory | 
library_display_cover_size | 136
library_display_rows | 50
library_display_same_height | 1
library_display_sort_field | sortableIssueNumber
library.consolidate.delete-physical-file

**Comment by mcpierce** [comment]
@bareheiny That's expected -- the left hand side are the settings keys for all of your user preferences. They don't get translated.

**Comment by bareheiny** [comment]
@mcpierce - all good then, closing this.
