### ISSUE TITLE
Logging out of CX does not return the user to the main page, and menu becomes unresponsive.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#308]
As per subject.

When I logged out of CX (via the Logout menu option), the browser page remained on the screen displayed when I logged out.  Additionally I am unable to access the menu to attempt to log back in.

I would expect CX to return me to the main page (displays a "Login to view library" message) , at which point I could log back in as required.

**Comment by mcpierce** [comment]
@bareheiny This is now fixed on develop and will show up in the next release candidate (rc7).

**Comment by bareheiny** [comment]
Looks good.
