### ISSUE TITLE
Filter comics by whether or not they have been scraped. 

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#31]
Provide a means for showing comics that have no been scraped; i.e., those without a ComicVine ID.

**Comment by bareheiny** [comment]
Smart reading lists would address this.

I don’t think there’s any need to code for this specifically, if a user can create a smart reading list.

I suspect most CR users use smart lists for their processing flow.

**Comment by mcpierce** [comment]
This feature isn't meant to be a smart list, per se. I'm looking at this as a way of, within any list of comics, to be able to display only those comics that have no been scraped so one can select issues in order to scrape them.
