### ISSUE TITLE
The comics import button doesn't seem to work correctly.

### ISSUE THREAD

**Issue by BRUCELLA2** [comixed/comixed#317]
**Describe the bug**
When I want to import comics files, I select the comics and then I click on the horizontal arrow button (see screenshot) to import the selected comics. Nothing happens. As a user I feel like there's a bug.

In order to make the import work, I have to click on the vertical arrow button next to the import button and select one of the two options (with or without metadata).

**To Reproduce**
1. connect with admin account
2. go in the import section
3. select some comics files
4. clic on the import button (horizontal arrow) => nothing happens.

**Expected behavior**
I think that when I click on the import button, I should either have a default behavior (import with metadata for example) or I should directly have the options menu displayed.

**Screenshots**
![import the selected comics](https://user-images.githubusercontent.com/30931629/83964139-e9e18880-a8aa-11ea-9ba6-8f3af1881471.png)
![import the selected comics 2](https://user-images.githubusercontent.com/30931629/83964143-ecdc7900-a8aa-11ea-96fc-6716c2ef1d59.png)

**Desktop (please complete the following information):**
 - ComiXed version : 0.7.0-0
 - OS: Windows 10 and Linux Mint 19.3 Tricia
 - Browser name : Brave Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit) and firefox 76.0 (64 bits)

 **ComiXed Build Detail** 

Source Branch | 87b8f687fe928cac74032311b1914924001a89c3
Build Hostname | fv-az68
Built On | Jun 6, 2020, 5:29:15 PM
Version | 0.7.0-0
Commit Hash | 87b8f687fe928cac74032311b1914924001a89c3
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jun 6, 2020, 5:03:17 PM
Commit Message | Changed the select reading list dialog to close after adding comics [#315]
Built From Uncommitted Code? | false
Remote Origin | https://github.com/comixed/comixed

**Additional context**
--

**Comment by bareheiny** [comment]
Currently working as intended.

But I did ask for the number of actions (button presses) to begin an import be reduced in #152

**Comment by BRUCELLA2** [comment]
Oups i don't see the #152 .

**Comment by mcpierce** [comment]
@BRUCELLA2 Given that we have #152 to streamline the import behavior, would you mind if we close this issue?

**Comment by BRUCELLA2** [comment]
Yes, we can close this issue.
