### ISSUE TITLE
Reading list names are case sensitive.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#318]
**Describe the bug**
When creating reading lists, it appears that the name is case sensitive - which allows for users to create reading lists with the same name.  For example, "Test reading list" and "test reading list".

**To Reproduce**
1. Go to the Comics page (Menu / Comics
2. Click on 'Create a new reading list...'
3. Create a reading list called "Test" and confirm it's creation.
4. Check the reading list list (Show Library Contents menu.  Note reading list may not appear immediately).
5.  Create another reading list (via right-click on the reading list section, or via the 'Create a new reading list' menu on the Comics page.  Name this one "test".
6.  Note that the reading list was created.
7.  Repeat step 4, and note that both "Test" and "test" exist.

**Expected behavior**
I would expect that the second reading list would fail, as "Test" and "test" should be considered the same text.

**Desktop (please complete the following information):**
 - ComiXed version 0.6.0-0.rc6
 - OS: Windows 10
 - Browser name Edge (chromium)
 - Browser version 83.0.478.45

** ComiXed Build Detail **

Source Branch | 79bca8b32567a135f30bf66e8a474358b91cb5a9
-- | --
Build Hostname | fv-az50
Built On | Jun 6, 2020, 5:46:20 PM
Version | 0.6.0-0.rc6
Commit Hash | 79bca8b32567a135f30bf66e8a474358b91cb5a9
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jun 6, 2020, 5:26:52 PM
Commit Message | Changed the select reading list dialog to close after adding comics [#315]
Built From Uncommitted Code? | true
Remote Origin | https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@bareheiny Hrm, this is an interesting one. Is it a bug? I know it seems counter-intuitive, but I'm not sure this is a bug.

**Comment by bareheiny** [comment]
Maybe not so much a bug, but more of an unexpected behaviour.

I'd rather that CX treats "Test" and "test" (and any variation of case use) as the same - for sure I don't want to create a list called "Venom's greatest hits" and accidentally create another called "venom's greatest Hits".

**Comment by mcpierce** [comment]
Now that #673 is merged, this issue is no longer a problem: reading list names are always uppercase.
