### ISSUE TITLE
The Reading List Details pop up can only be closed via Cancel or Save - not with the X button.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#319]
**Describe the bug**
The Reading List Details pop up can only be closed via Cancel or Save - not with the X button on the top left corner of the pop up.

**To Reproduce**
1. Create (or edit) a reading list
2. Press the X in the top left corner of the pop up.
3. Note that nothing happens
4. Press the Cancel button
5. Note that the pop up is closed

**Expected behavior**
I would expect the X to function the same way as the Cancel button does - it should close the pop up.

**Desktop (please complete the following information):**
 - ComiXed version  0.6.0-0.rc6
 - OS: Windows 10
 - Browser name Edge (chromium)
 - Browser version 83.0.478.45

** ComiXed Build Detail **

Source Branch | 79bca8b
-- | --
Build Hostname | fv-az50
Built On | Jun 6, 2020, 5:46:20 PM
Version | 0.6.0-0.rc6
Commit Hash | 79bca8b
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jun 6, 2020, 5:26:52 PM
Commit Message | Changed the select reading list dialog to close after adding comics [#315]
Built From Uncommitted Code? | true
Remote Origin | https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@bareheiny Marking this as a duplicate of #315 (the fix in included in rc7). Could you verify that and close this ticket after?

**Comment by bareheiny** [comment]
The X button isn't closing the dialog box.

Version:  0.6.0-0.rc9

**Comment by mcpierce** [comment]
@bareheiny Okay. I'll promote it to a bug then.

**Comment by mcpierce** [comment]
@bareheiny A fix has been merged into develop. Can you verify it and, if it works, please close this ticket?

**Comment by bareheiny** [comment]
This looks good, so closing.

@mcpierce, reading lists in the latest development build may not be working correctly.  I likely won't get a chance to create an issue for a few days - but it may be worth just creating a new reading list and trying to add a comic to the list.  Checking the pop-out when adding to a comic to a list, and checking the reading list was created successfully via the Library navigation menu.

**Comment by mcpierce** [comment]
@bareheiny I'll look into it. I'd like to avoid opening bugs against development issues, though, since we could end up with tons of development (rather than release) issues which could get overwhelming. Could you instead shoot an email to the dev list about it?
