### ISSUE TITLE
The sorting of the "Start Year" and "Issues" column does not work on fetch volumes table

### ISSUE THREAD

**Issue by BRUCELLA2** [comixed/comixed#325]
**Describe the bug**
When fetching the volumes, the sorting of the "Start Year" and "Issues" columns does not work.

**To Reproduce**
1. Connect with admin account
2. Go to Comics section
3. Select some comics
4. Clic on Scrape selected Comics button
5. Clic on Fetch volumes button
6. Clic on "Start Year" or "Issues" to sort the table => don't work

**Expected behavior**
Sort table by "Start Year" or "Issues"

**Screenshots**
![2020-06-09 - 10:26:00](https://user-images.githubusercontent.com/30931629/84125546-f85fa980-aa3c-11ea-8069-0c7496a4b90e.png)
![2020-06-09 - 10:26:49](https://user-images.githubusercontent.com/30931629/84125554-fac20380-aa3c-11ea-8a69-75d9251ffd28.png)

**Desktop (please complete the following information):**
 - ComiXed version : 0.6.0-0.rc7
 - OS: Windows 10 and Linux Mint 19.3 Tricia
 - Linux Browser name : Brave Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit) and firefox 77.0.1 (64 bits)
 - Windows Browser name : Brave Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit) and Chrome 83.0.4103.97 (Official Build) (64-bit)

** ComiXed Build Detail **
Source Branch	c6993d1ba48cb1df9ab9619b85e151d21e546909
Build Hostname	fv-az129
Built On	Jun 7, 2020, 12:20:01 AM
Version	0.6.0-0.rc7
Commit Hash	c6993d1ba48cb1df9ab9619b85e151d21e546909
Committer Name	Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit	Jun 7, 2020, 12:13:51 AM
Commit Message	Added tags for v0.6.0-0.rc7 [#303]
Built From Uncommitted Code?	true
Remote Origin	https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@BRUCELLA2 This is now fixed on develop and will be included in RC8 when it's released. Please verify it when you can and close this ticket if it's fixed.

**Comment by BRUCELLA2** [comment]
@mcpierce  
For me it's ok. I close the issue.
