### ISSUE TITLE
"Add to list" action not available when right-clicking on an un-selected comic.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#339]
**Describe the bug**
The "Add to list" action is greyed out when right-clicking on an un-selected comic (note. no comics are selected in this scenario).

**To Reproduce**
1. Go to the Comic library view'
2. Ensure no comics are selected
3. Right-click on a comic
4. Note the only actions available are "Select all", "Open comic..." and "Delete comic..."

**Expected behavior**
I would expect that the "Add to list", "conver comic..." and *maybe* the "Scrape selections" actions would be available.  Note the "Scrape selections" would need a more generic name if the action could be performed on a non-selected comic.

**Desktop (please complete the following information):**
 - ComiXed version 0.6.0-0.rc7
 - OS: Windows 10
 - Browser name Edge (chromium)
 - Browser version 83.0.478.45

** ComiXed Build Detail **

Source Branch | c6993d1ba48cb1df9ab9619b85e151d21e546909
-- | --
Build Hostname | fv-az129
Built On | Jun 7, 2020, 12:20:01 AM
Version | 0.6.0-0.rc7
Commit Hash | c6993d1ba48cb1df9ab9619b85e151d21e546909
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jun 7, 2020, 12:13:51 AM
Commit Message | Added tags for v0.6.0-0.rc7 [#303]
Built From Uncommitted Code? | true
Remote Origin | https://github.com/comixed/comixed

**Additional context**
Unrelated, why do open, delete and convert have "..." after them?

**Comment by mcpierce** [comment]
@bareheiny This is intentional -- adding to the list is only for comics in a selection. Though I suppose we can remove the menu item when there's no selection set rather than disabling it.

**Comment by mcpierce** [comment]
@bareheiny This change is now merged into the develop branch, and will be added to the rc8 release as well. Please verify it's working and then you can close this ticket. Thanks. :smile:

**Comment by bareheiny** [comment]
Changed as outlined above.

Does it make any sense to hide the menu item, as it was disabled without at least one comic selected?  It's now inconsistent with the other disabled actions.

**Comment by mcpierce** [comment]
I personally think hiding them is the better option. That way we don't waste any screen space on options that can't be accessed.

**Comment by bareheiny** [comment]
Fair enough - may make sense to apply the same logic to all menu items then.

Closing this ticket.
