### ISSUE TITLE
When fetching ComicVine data, allow the user to restrict the number of results returned.

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#34]
As a user, I would like to be able to restrict the number of results returned when using the fetch function to query ComicVine.

Currently, the ComicVine API returns data for series titles that contain any of the words in a search string, which can cause delays in returning results.

For example searching for "Black Widow" returns "Black Ant" and "Widow: Progeny"...as well as "Black Widow".

As the API orders the data returned by best match, the odds are pretty good that issue searched for is in the top 100 results. If a user could set the number of issues (pre-defined ranges is more than acceptable), the time taken to scrape issues could be minimized.

**Comment by bareheiny** [comment]
Just a bit more information on this (now that I'm scraping stuff).

Scraping "Absolution:  Rubicon" returned 13 volumes in a few seconds..."All New Ultimates" returned 3,934 volumes after a much longer time.

In both cases, the issue I was scraping was the first on the list.
