### ISSUE TITLE
Reading list pop-out is not large enough to list multiple reading lists

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#340]
**Describe the bug**
The reading list pop-out drop down list is not large enough to allow for multiple reading lists to be displayed.

**To Reproduce**
1. Create at least four reading lists
2. Navigate to the comics library page
3. Select a comic, right-click and select "Ad to list..."
4. Press the down arrow to expand the drop-down list
5.  Note that not all of the created lists are shown - in my case, only one is.

**Expected behavior**
Multiple lists would should be shown.

**Screenshots**

**Desktop (please complete the following information):**
 - ComiXed version 0.6.0-0.rc7
 - OS: Windows 10
 - Browser name Edge (chromium)
 - Browser version 83.0.478.45

** ComiXed Build Detail **

Source Branch | c6993d1ba48cb1df9ab9619b85e151d21e546909
-- | --
Build Hostname | fv-az129
Built On | Jun 7, 2020, 12:20:01 AM
Version | 0.6.0-0.rc7
Commit Hash | c6993d1ba48cb1df9ab9619b85e151d21e546909
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jun 7, 2020, 12:13:51 AM
Commit Message | Added tags for v0.6.0-0.rc7 [#303]
Built From Uncommitted Code? | true
Remote Origin | https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@bareheiny This is fixed on develop now and will be included in RC8. Please check out the build and, if it's fixed, you can close this ticket.

**Comment by bareheiny** [comment]
Looks good, closing.

**Comment by bareheiny** [comment]
Closing again.

**Comment by bareheiny** [comment]
Trying to close for the third time.

**Comment by bareheiny** [comment]
Trying to close on another browser.

**Comment by mcpierce** [comment]
@bareheiny Is this bug still present? I see it was re-opened a few hours ago.

**Comment by bareheiny** [comment]
Sorry, reopened accidentally.  Thought I’d close it again.
