### ISSUE TITLE
"Logged in as" text barely visible, and text too close to the language menu.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#359]
**Describe the bug**
Due to the color of the "Logged in as xxx" text (black) and the color of the menu stripe (also black), it is not discernable without closer inspection.

**To Reproduce**
1.  Log into CX
2.  Note that the "Logged in as xxx" text next to the language selection menu blends in with the background.
3.  Note that the "Logged in as xxx" text is so close to the language selection menu that it appears to run into the menu.

**Desktop (please complete the following information):**

ComiXed version 0.7.0-0
OS: Windows 10 Pro, 64 bit
Browser name Edge (chromium)
Browser version 83.0.478.45

**ComiXed Build Detail** 
Source Branch | 1238a3d90f9d83f9ec8513133b9121565879dc37
-- | --
Build Hostname | fv-az121
Built On | Jun 17, 2020, 8:20:07 PM
Version | 0.7.0-0
Commit Hash | 1238a3d90f9d83f9ec8513133b9121565879dc37
Committer Name | Darryl L. Pierce (mcpierce@users.noreply.github.com)
Time Of Last Commit | Jun 17, 2020, 8:09:58 PM
Commit Message | Changed Java requirements note.
Built From Uncommitted Code? | false
Remote Origin | https://github.com/comixed/comixed

**Comment by BRUCELLA2** [comment]
what do you think if we have something like this : 
![login as](https://user-images.githubusercontent.com/30931629/85711833-f7d73c00-b6e7-11ea-9d8e-46acb36205d8.png)

**Comment by mcpierce** [comment]
@BRUCELLA2 Definitely need to have the styling changed on the text.

**Comment by BRUCELLA2** [comment]
Another proposition. I think the expression "Logged in as:" is not necessary if we use an icon. What do you think of this : 
![login as 2](https://user-images.githubusercontent.com/30931629/85715515-d4ae8b80-b6eb-11ea-9e0e-fa9c11e774c5.png)

**Comment by mcpierce** [comment]
@BRUCELLA2 I like it. Can we change the text then to also be a link to the user's details view?

**Comment by BRUCELLA2** [comment]
I'll look to add a link to the user's details view

**Comment by mcpierce** [comment]
@bareheiny This is now fixed on develop. When you can, please verify the changes and then close this, please.

**Comment by bareheiny** [comment]
Looks good, closing.
