### ISSUE TITLE
Prompt the user for confirmation before logging out

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#376]
When the user selects the logout button, the system should prompt to confirm they really want to log out.

**Comment by bareheiny** [comment]
Is it all feasible to allow users to disable confirmation prompts (maybe for everything except irreversible actions such as deleting comics etc.)?

Personally, I'll find myself more annoyed by a "are you sure" prompt than an accidental log-out (or comic scrape commit).

**Comment by mcpierce** [comment]
It's possible. We'd have to add it as a separate feature request, but it's not out of the question.
