### ISSUE TITLE
CX should extract, and re-size, cover images for caching during the comic import process.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#381]
**Note:**  This feature request relates to _extracted images only_ - it is not intended (or wanted) for any manipulation to occur to images within the comic archive.

**Is your feature request related to a problem? Please describe.**
As a user, I would like CX to have already extracted the cover images for display in the library sections, so I do not have to wait for them to be loaded as I navigate through each page.  I would also like it if CX re-sized the images in order to increase the load speed (smaller files = less data to transfer to my browser for display) and decrease the disk space used.

**Describe the solution you'd like**
Ideally, as part of the comic import process - as soon as a comic has been fully loaded and all pages have had hash values calculated, the first image (or whichever CX determines to use as a cover image) should be extracted from the archive, re-sized to a maximum pixel height (400 seems to be maximum for the cover size slider) and then stored in the /cover/ directory using the current directory and file name convention (i.e. three directories made up of the first, second and third 8 characters of the hash, and the file name being the final 8 characters).

**Describe alternatives you've considered**
Currently, I have a mix of SQL, bat commands and Excel VBA to identify, extract, rename and move the file images.  I can likely automate it more, and removing a number of steps...but I feel this is a nice feature for CX to have natively.

**Additional context**
This process should also be able to run on command - for cases where a user has removed all cached images, and wants to re-populate the cover cache.

I'm not sure this fits nicely with CX functionality, but converting the extracted cover images to JPG (where they are in another format) would be nice - but situationally dependent.  For users such as myself, where the comic collection is in webp format, and CX is occasionally accessed via iOS - having the extracted covers in webp format is of no use due to iOS Safari (and other iOS browsers) not being compatible with web images.  As this is more of a fringe case, it may be better to leave it up to the user to decide if format conversion is required.

**Comment by mcpierce** [comment]
@bareheiny I'm going to close this ticket since the image cache is really a transient thing; i.e., they're pulled the first time the image is requested and is deleted when the cache is purged. So pre-pulling them only to have purged later seems needless to me.

If you'd like to re-examine the feature, please start a thread in the user mailing list and we can get some feedback on it.
