### ISSUE TITLE
Browser tab for the CX main page (once logged in) displays main-page.title

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#382]
**Describe the bug**
Browser tab for the CX main page (once logged in) displays main-page.title

**To Reproduce**
1. Login to CX using your browser
2. Note that the browser tab title is "main-page.title"

**Expected behavior**
The browser tab title should not be "main-page.title" (I forget what the title used to be).

**Desktop (please complete the following information):**
 - ComiXed version 0.7.0-0
 - OS: Windows 10 Pro, 64bit
 - Browser name Edge (chromium)
 - Browser version Version 83.0.478.56 (Official build) (64-bit)

 **ComiXed Build Detail** 

Source Branch | 7e933a98f7d66773c51109bd31d614e676bd669e
Build Hostname | fv-az139
Built On | Jun 27, 2020, 9:34:09 PM
Version | 0.7.0-0
Commit Hash | 7e933a98f7d66773c51109bd31d614e676bd669e
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jun 27, 2020, 9:20:59 PM
Commit Message | Fixed a bug in loading the plugin languages [#26]
Built From Uncommitted Code? | false
Remote Origin | https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@bareheiny Does this also still happen on the release? If so, let's move this bug there and we can prepare a new release to address it.

**Comment by mcpierce** [comment]
@bareheiny A fix for this has been merged into develop. Can you verify it as working and, if so, please close this?

**Comment by bareheiny** [comment]
Looks good.
