### ISSUE TITLE
Add a limit to the number of comics to find during import

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#4]
**Is your feature request related to a problem? Please describe.**
When importing comics, I would like to set a limit on the number of comics to find before returning the set of results.

**Comment by bareheiny** [comment]
Duplicate of #34 (or vice versa)?

**Comment by mcpierce** [comment]
@bareheiny No, this issue is about limiting the number of results returned when importing comics. #34 is about limiting the number of results returned from ComicVine during scraping.
