### ISSUE TITLE
Newly created reading list not showing in Library Contents pane without browser refresh.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#401]
**Note**:  typo here: **NOTE: If this involves a pre-**releae** version of ComiXed and not a release, then please send an email to the mailing list rather than creating an issue here.**

**Describe the bug**
When adding a new reading list, it is not shown in the Library Contents pane without forcing a browser refresh.  There also seems to be a delay in it being shown in the "Add 1 Comic To A Reading List" pane, but that refreshes after a small amount of time.

**To Reproduce**
1. Navigate to the Comics page
2. Add a new reading list
3. Expand the Library Contents pane
4. Scroll to, and expand, reading lists - note that the newly created list does not appear

**Expected behavior**
A newly created reading list should be shown in the Library Contents pane shortly after being created.

**Screenshots**
List created:
![Reading list](https://user-images.githubusercontent.com/1912425/87011351-e596eb00-c21b-11ea-85db-cd40e79682ca.PNG)

List not showing:
![Missing reading list](https://user-images.githubusercontent.com/1912425/87011348-e3cd2780-c21b-11ea-84cb-925e9d3f1445.PNG)

**Desktop (please complete the following information):**
 - ComiXed version 0.6.1
 - OS: Windows 10 Pro, 64bit
 - Browser name Edge (chromium)
 - Browser version [Version 83.0.478.58 (Official build) (64-bit)

** ComiXed Build Detail **

Source Branch | 6d46e00d6faa1f8ed106cb246d822b115603404c
-- | --
Build Hostname | fv-az51
Built On | Jul 7, 2020, 5:10:04 PM
Version | 0.6.1
Commit Hash | 6d46e00d6faa1f8ed106cb246d822b115603404c
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jul 7, 2020, 3:11:47 PM
Commit Message | Added a github_changelog_generator configuration file [#303]
Built From Uncommitted Code? | true
Remote Origin | https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@bareheiny A release is coming out shorting with this fix in it. Please verify it's fixed in 0.6.2 and close this ticket.

**Comment by bareheiny** [comment]
Looks good, closing.
