### ISSUE TITLE
Blank line at the top of the "Add Comic To A Reading List" popout

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#402]
**Describe the bug**
When adding a comic to a reading list, there is a blank line that is not the same size as one with a reading list at the top of the menu.

**To Reproduce**
1. Navigate to the Comics page
2. Select a comic
3. Right click and select "Add to list"
4. Note that there is what appears to be a blank line at the top of the list, approximately half the size of a line with a reading list name.

**Expected behavior**
Only reading lists would be displayed, with no blank line showing.

**Screenshots**
See blue line (this is selected).
![Reading list](https://user-images.githubusercontent.com/1912425/87011351-e596eb00-c21b-11ea-85db-cd40e79682ca.PNG)

**Desktop (please complete the following information):**
 - ComiXed version 0.6.1
 - OS: Windows 10 Pro, 64bit
 - Browser name Edge (chromium)
 - Browser version [Version 83.0.478.58 (Official build) (64-bit)

** ComiXed Build Detail **

Source Branch | 6d46e00d6faa1f8ed106cb246d822b115603404c
-- | --
Build Hostname | fv-az51
Built On | Jul 7, 2020, 5:10:04 PM
Version | 0.6.1
Commit Hash | 6d46e00d6faa1f8ed106cb246d822b115603404c
Committer Name | Darryl L. Pierce (mcpierce@gmail.com)
Time Of Last Commit | Jul 7, 2020, 3:11:47 PM
Commit Message | Added a github_changelog_generator configuration file [#303]
Built From Uncommitted Code? | true
Remote Origin | https://github.com/comixed/comixed

**Comment by mcpierce** [comment]
@bareheiny I'm pushing 0.6.2 now. Could you verify that this bug is fixed and close the ticket if so? Thanks.

**Comment by bareheiny** [comment]
Looks good, closing.
