### ISSUE TITLE
Consistency with capitalization  of menu, title and description text

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#403]
Minor request - but I'd like to see consistent capitalization used in all text used in CX menus etc.

For example the title for the adding a comic to a reading list pop-out is "Add One Comic To A Reading List", with the subtitle "Select A Reading List".

The text in the comic action menu is "Select a list...".

I'm not sure if there's a UI interface standard, but the capitalization of the first letter in every word doesn't sit right with me....ideally the text would be "Add one comic to a reading list" and "Select a reading list"...or possibly more appropriately, "Add One Comic to a Reading List".

**Comment by mcpierce** [comment]
Closing this in lieu of specific tickets for fixing things. Right now we have styling rules that should be standardizing headers across the app.
