### ISSUE TITLE
Include database path and name via the Help section.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#408]
As a user, I would like to easily be able to confirm the location of the CX database being accessed.

This should be a simple field showing the path, and name such as "D:\comixed\comixed.mv.db" or (if I was running a development build against a different database) "D:\comixed\comixed_dev.mv.db".

**Comment by mcpierce** [comment]
I think the best we can do is to output the JDBC URL on the build details page. CX doesn't know the filename, only the URL it's using to connect to it.

**Comment by bareheiny** [comment]
Good enough for me - I'm just wanting something that will easily allow me to check which connection string is being used.
