### ISSUE TITLE
Functionality to apply multiple filters in the "Library Contents" pane.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#409]
As a user, I would like to be able to apply multiple filters in the "Library Contents" pane, including text entered in the search pane.

For example, I may want to find a comic, or comics, that has an Undefined Publisher with Catwoman in the series - or a 1992 Volume (feature request #410 ) for Batman.

**Comment by mcpierce** [comment]
Closing this since it applies to the old UX.
