### ISSUE TITLE
Provide a scraper that supports the Marvel database

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#412]
As a user I would like to be able to scrape my Marvel comics using Marvel as a data source.

https://developer.marvel.com/

**Comment by theotocopulitos** [comment]
I am not so sure how many hits are allowed at the time. When this first came out, I tried a little script in python for this for comicrack, but the number of API hits was too low for a functional scraper.

Also, how difficult would it be to have an open scraping engine that could be fed by different plugins from different sources?

**Comment by mcpierce** [comment]
@theotocopulitos From what I saw yesterday they limit your interactions to 3000/day. But I haven't read too deeply into their terms for usage.

**Comment by mcpierce** [comment]
Closing this ticket since the work will now be done in this project: comixed/comixed-metadata-marvel#1
