### ISSUE TITLE
iOS - allow long presses to open context menu

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#421]
Currently in iOS (at least on an` iPhone), long presses on images (such a as comic cover thumbnails) present the user with a save / share type menu, rather than the CX context menu.

When accessing CX via Mobile Safari (or other iOS based browsers), a long screen press should open the appropriate context menu.

Currently, there does not appear to be a workaround.

**Comment by mcpierce** [comment]
That's a browser function, not something CX can do. The browser would have to translate that sort of press and forward it to the CX as a right-click/context click for us to respond to it.

**Comment by bareheiny** [comment]
I'd read something that indicated this could be handled via coding (listening for the long press)...but further reading lead to more issues as well as iOS vs Android behaviours.

While it means CX won't be able to be fully used in iOS, it doesn't seem like an easy issue to address.
