### ISSUE TITLE
Change how the Credits, Characters and similar information is displayed.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#446]
See the attached screenshots.

On my screen (Surface Pro), the Credit and Character information sets run into each other - more so the character information.

My view is that this sort of information would be best presented in a grid or table format.  In the case of the credits, grouped by type such as inker, letterer, writer etc.

This likely applies to the presentation of similar data - I haven't checked, but I suspect location and teams would fall into this group.

![Story page](https://user-images.githubusercontent.com/1912425/88497801-83a8f480-d015-11ea-9d84-ad8206e1c5ef.PNG)
![Credits](https://user-images.githubusercontent.com/1912425/88497804-84da2180-d015-11ea-84f8-2170070135e1.PNG)

**Comment by mcpierce** [comment]
@bareheiny The long-term plan here is to show these as individual baseball cards with a picture, a name, etc. That's going to be applied to characters, teams, locations, stories and credits.

**Comment by bareheiny** [comment]
@mcpierce and of course now you've mentioned, I recall you've mentioned it before!

Closing.
