### ISSUE TITLE
Enable extracting the series, volume and issue from the filename during comic scraping

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#46]
As a library owner, it would be convenient for me to be able to automate getting the series, volume and/or issue number when scraping a comic that has no metadata.

To achieve this, while scraping a comic, a button is added to the scraping page that will pull whatever information is available in the comic's filename in order to get the series, volume and issue number details from the comic.

**Comment by bareheiny** [comment]
Wouldn't this require someway for the user to specify the naming convention used, and also assume that convention is used for all comics being imported this way?

If you're looking at the file name, would you also need to consider the file path?

For example I general go with "Publisher\Imprint (if relevant)\Series [Year]\Series Vol. Issue# (issue date).cbz " format, however I have seen others reference grouping by primary character or story arc.

**Comment by mcpierce** [comment]
On the backend, during the import process, there's a filename extractor that uses a few different filename rules to try and find this data. What I was thinking of doing with this feature was to have the frontend send a request to the backend to run just the current comic's filename (no path) against that ruleset to try and rescrape the details.
