### ISSUE TITLE
Allow users to turn off moving / renaming of comic file during library consolidation.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#508]
As a user, I would like to be able to choose whether or not my comic files are re-organized during library consolidation.

This could be done by adding a checkbox (similar to the delete physical files one) near the renaming rules section.  If the checkbox was not ticked / selected, CX would not re-organize the files during consolidation.

If the checkbox was ticked / selected, CX would then re-organize files during consolidation.

**Comment by mcpierce** [comment]
So for this we would add a checkbox above the move details that says "Move comic library".
1. If the checkbox is set, then:
   1. a target directory must be entered, and 
   1. an optional renaming rule entered.
If no renaming rules are entered then the comics are moved and their current filename left intact.

**Comment by mcpierce** [comment]
@bareheiny I'm not sure, now that consolidation is completed, this feature request makes sense. Consolidation is the act of moving the files managed by CX into a single directory tree (the target directory) and then applying a renaming rule to all comics. I'm not sure that we can turn any part of that off.

If you don't mind, could you close this feature request and start a conversation in the users mailing list? Then we can get other ideas and see what comes up.

**Comment by bareheiny** [comment]
So now that I’m using Mylar, I likely won’t need to use a renaming feature anyways :)
