### ISSUE TITLE
Change the Import button to function in a similar manner as the scraping one.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#509]
That is, have the import button remember the last choice a user made for importing - with or without metdata.

This means that if a user selected to imported without metdata via the dropdown list, for the next import simply pressing the import button would being the import without metdata immediately, rather than requiring the user to select from the drop down box.

**Comment by mcpierce** [comment]
@bareheiny Closing this since the import page has a separate button for toggling metadata.
