### ISSUE TITLE
Create a log file from the startup scripts.

### ISSUE THREAD

**Issue by Dunuin** [comixed/comixed#515]
Hi,

I installed ComiXed to a VM running Debian 10.5. First I just tried to run the run.sh without any parameters directly using ssh. That way dozens of lines per second were posted to the console. They looked like the logs in previous installations with lots of "Info" tags. 

Next I created a simple systemd-service to autostart ComiXed at boot by running "bash /home/comixed/comixed/bin/run.sh > /dev/null 2>&1". I thought that piping might remove all the output but I still found messages in the syslog.

Finally I edited the run.sh and changed the last line to this "$JAVA ${JVMOPTIONS} -jar ${COMIXED_JAR_FILE} ${JAROPTIONS} > /dev/null 2>&1" (pipe added here too) and now finally the output is completly removed.

Is it wanted that ComiXed will output all the logs by default, even if it isn't started in debug mode nor with logging enabled? As long as ComiXed outputs them the are also logged by syslog even if no logs are wanted.

I really would like to store logs in a seperate log file but only the important stuff (errors and so on). I've read that I can start comixed with "--logging.file=comixed.log" to write the logs to a file but I didn't found what to do if I just want log lines with a log level of "error" or higher.

**Comment by mcpierce** [comment]
ComiXed uses Log4J2 as its logging library. The release candidate builds are released with logging set to DEBUG for CX-related code and INFO for everything else to make it easier to nail down any bugs that are discovered during the release testing process. Then, when the official release is made it'll come out with the logging set to INFO for everything to reduce the amount of logging displayed.

> I really would like to store logs in a seperate log file but only the important stuff (errors and so on). I've read that I can start comixed with "--logging.file=comixed.log" to write the logs to a file but I didn't found what to do if I just want log lines with a log level of "error" or higher. Though I see now that's deprecated and the logging library recommends using --logging.file-name=comixed.log instead. So I've fixed the file.

In the same section of the QUICKSTART.md file that talks about logging to file it also tells you how to increase the amount of logging. However, as I mentioned above, right now during the release phase the logging level is already set to DEBUG for CX-specific code.

I'm also making this report into a feature request to add a startup script option to create a log file. That way you won't need to do extra steps outside of the startup script to generate logs.

**Comment by mcpierce** [comment]
This is now fixed on the develop branch and has be merged into the 0.7 release as well. You can close this ticket after downloading and verifying it on either the 0.8 development build or the 0.7 release candidate, the latter of which will be made this weekend.

**Comment by mcpierce** [comment]
@Dunuin I've included this in the 0.7.0-rc4 release, which will hopefully be promoted to a GA release now. Could you please verify that this works and close this ticket? Thanks.

**Comment by mcpierce** [comment]
@Dunuin This fix is included in 0.7.0-1. If the issue persists, please feel free to re-open this ticket.
