### ISSUE TITLE
Comic metdata editing - placeholder text for volume in Title field.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#519]
The placeholder text Volume appears in the Title field when editing issue metadata (via the open comic / Overview pane).

The Title field appears to be limited to 10 characters - consistent with a dd/mm/yyyy formatted value.

The placeholder text could be refined to "First year of publication" or similar - may need to be shortened to 10 characters.

**Comment by bareheiny** [comment]
Ah...just noticed the placeholder text appears to be used in Title, Volume and Issue.

**Comment by mcpierce** [comment]
@bareheiny Closing this since we've not re-implemented this code with the new Angular UI.
