### ISSUE TITLE
Question:  How to connect to access the comixed H2 database via a SQL client

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#52]
It's been a few months since I've accessed the CX database directly via SQL, and it's not working anymore.

Has something about the connection required changed, or am I just missing something?

**Comment by mcpierce** [comment]
No, nothing's changed. You just need to download the [H2 client](https://www.h2database.com/html/download.html) and run the client in that (without CX running) to access the tables.

**Comment by bareheiny** [comment]
Hmmm.  Must be me then.

I'll keep on trying.

**Comment by bareheiny** [comment]
Looks like my CX DB was corrupted or something - it worked with CX (eventually), but not with H2.

A freshly created (and empty) DB opened with no issues.
