### ISSUE TITLE
Stories not in Library Contents, but in Story Arc

### ISSUE THREAD

**Issue by omgthegreenranger** [comixed/comixed#522]
In both the current 0.7.0-1 and 0.8.0 snapshot, Stories on the Library Contents page are being listed as "undefined."

It is also not being shown when selecting the story from a comic's info page - the /comics/stories URL doesn't provide anything.

**Expected behavior**
I'd like to be able to see all comics with a certain story arc in one place. Order isn't vital, grouping is. I do recall this working at one point in the past (I just started playing with CX again after a long wait.

**Screenshots**

Library Contents: 
![image](https://user-images.githubusercontent.com/582084/96073333-3a2db000-0e74-11eb-9ed6-f9531329a414.png)

Book's story arcs page
![image](https://user-images.githubusercontent.com/582084/96073405-63e6d700-0e74-11eb-9fc3-11cec18315a4.png)

Stories URL
![image](https://user-images.githubusercontent.com/582084/96073429-706b2f80-0e74-11eb-9679-fa544966f67e.png)

**Desktop (please complete the following information):**
0.8.0-SNAPSHOT and 0.7.0-1

 - OS: Arch Linux
 - Firefox 81.0.2

** ComiXed Build Detail **

Source Branch | 23d1a2633799740e2deaa93de18e4bf8b9601fe9
-- | --
Build Hostname | fv-az32
Built On | Oct 12, 2020, 12:05:43 AM
Version | 0.8.0-SNAPSHOT
Commit Hash | 23d1a2633799740e2deaa93de18e4bf8b9601fe9
Committer Name | Darryl L. Pierce ()
Time Of Last Commit | Oct 12, 2020, 11:54:55 AM
Commit Message | Changed Karma to not show console output during tests [#465]
Built From Uncommitted Code? | false
Remote Origin |  
JDBC Connection URL | jdbc:h2:file:~/.comixed/comixed;create=true

**Additional context**

**Comment by mcpierce** [comment]
@omgthegreenranger Thank you for the bug report! I'll take a look at it and see about getting a fix out for it soon.

**Comment by mcpierce** [comment]
@omgthegreenranger I've fixed this issue and will be including the update in 0.7.0-2, which should be ready shortly. If you could, please verify the bug is fixed and then close this issue if you're satisfied.

And thanks again for identifying the bug!

**Comment by mcpierce** [comment]
@omgthegreenranger I'm going to close this issue. If it comes up again, please feel free to open a new ticket and reference this one.
