### ISSUE TITLE
Removing comics from a reading list - action confirmation toaster showing placeholder text.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#534]
As per title.  I removed a number of comics from a reading list, and the action confirmation toaster showed place holder text.  Unfortunately I was not quick enough to grab a screen capture.

Build details:

Source Branch | f57c46da8896b205a7aa1f45fb160a05be7009c7
-- | --
Build Hostname | fv-az50
Built On | Oct 2, 2020, 5:16:58 PM
Version | 0.7.0-rc4
Commit Hash | f57c46da8896b205a7aa1f45fb160a05be7009c7
Committer Name | Darryl L. Pierce ()
Time Of Last Commit | Oct 2, 2020, 5:10:13 PM
Commit Message | Changed the release version to 0.7.0-rc4 [#496]
Built From Uncommitted Code? | true
Remote Origin |  
JDBC Connection URL | jdbc:h2:D:\Comics\.comixedDB\comixed

**Comment by mcpierce** [comment]
@BRUCELLA2 @theotocopulitos  @jmcrfp  I added you as additional assignees. Could you each please provide translations for the new entries? Thanks.
