### ISSUE TITLE
When selecting multiple comics for removal from a reading list and then removing them, the selection does not appear to be cleared.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#535]
As per title.

Open a reading list, select two comics for removal and remove them.  Select another comic for removal and remove them - note that the confirmation screen will say that three comics are selected for removal from the reading list.

Build details:

Source Branch | f57c46da8896b205a7aa1f45fb160a05be7009c7
-- | --
Build Hostname | fv-az50
Built On | Oct 2, 2020, 5:16:58 PM
Version | 0.7.0-rc4
Commit Hash | f57c46da8896b205a7aa1f45fb160a05be7009c7
Committer Name | Darryl L. Pierce ()
Time Of Last Commit | Oct 2, 2020, 5:10:13 PM
Commit Message | Changed the release version to 0.7.0-rc4 [#496]
Built From Uncommitted Code? | true
Remote Origin |  
JDBC Connection URL | jdbc:h2:D:\Comics\.comixedDB\comixed

**Comment by mcpierce** [comment]
@bareheiny I'm going to close this since, with the new user interface, we're rewriting the reading lists frontend from the ground up.
