### ISSUE TITLE
ComicVineGetIssueDetailsAction not mapping ComicVine "Name".

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#542]
The comic title (returned as "Name" by the ComicVine API) is not getting mapped into the database.

The ComicVineGetIssueDetailsAction class is only mapping publisher, series, volume, issue number, cover date, description, characters, teams, locations, stories and credits.

**Comment by mcpierce** [comment]
@bareheiny This is now merged into develop and will also be in the 0.7.0-4 release that'll be built later today. If you would be so kind, please verify the bug is fixed and, if so, close this ticket. Thanks. 😄

**Comment by bareheiny** [comment]
Just tested, and everything looks good.
