### ISSUE TITLE
When scraping from ComicVine, the summary details are placed into the description of the comic and not the summary.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#544]
When scraping a comic via ComicVine, the summary information is written to the description field.

**To Reproduce**
1. Scrape a comic that has no metadata
2. Once scraped, open the comic and check the "Story" tab
3. Note that Summary is empty, but Description is populated
4. Open a comic that has ComicInfo from another application (such as ComicRack), and check the "Story" tab
5.  Note that this comic a Summary, but no Description populated.

**Expected behavior**
The summary text scraped from ComicVine should be mapped to the Summary field in the COMICS table.

**Desktop (please complete the following information):**
 - ComiXed version 0.7.0-rc4
 - OS: Windows 10
 - Browser name Edge Chromium
 - Browser version 87.0.664.47

** ComiXed Build Detail **

Source Branch | f57c46da8896b205a7aa1f45fb160a05be7009c7
-- | --
Build Hostname | fv-az50
Built On | Oct 2, 2020, 5:16:58 PM
Version | 0.7.0-rc4
Commit Hash | f57c46da8896b205a7aa1f45fb160a05be7009c7
Committer Name | Darryl L. Pierce ()
Time Of Last Commit | Oct 2, 2020, 5:10:13 PM
Commit Message | Changed the release version to 0.7.0-rc4 [#496]
Built From Uncommitted Code? | true
Remote Origin |  
JDBC Connection URL | jdbc:h2:D:\Comics\CX_testing\db_etc\comixed

**Comment by mcpierce** [comment]
@bareheiny Looking into the scraping action, I see that ComicVine doesn't have a field named "summary" but instead calls it "description", which is what CX does as well. I think it may just be a difference in terminology between CX and other apps, and CX having an additional field named "summary" heightens that.

**Comment by bareheiny** [comment]
Oy vey!

Making this one slightly messier, CX doesn't accept a ComicInfo tag of <Description>....nor does that tag exist in CR generated ComicInfo.

Removing the Summary field from CX would mean mapping the <Summary> field to Description on import...and then what happens when CX can generate complete ComicInfo xml?  Would a <Description> tag be created....but then it would need to be able to parsed for import as well.

**Comment by bareheiny** [comment]
Follow up question - what effect will removing the summary have on comics where that field is populated in the CX database?

**Comment by mcpierce** [comment]
The migration is going to drop the column from the database, and the code is now going to map the ComicInfo summary tag into the description column.

**Comment by mcpierce** [comment]
> Oy vey!
> 
> Making this one slightly messier, CX doesn't accept a ComicInfo tag of ....nor does that tag exist in CR generated ComicInfo.
> 
> Removing the Summary field from CX would mean mapping the
> field to Description on import...and then what happens when CX can generate complete ComicInfo xml? Would a tag be created....but then it would need to be able to parsed for import as well.

I don't understand what's being said in this comment.

**Comment by bareheiny** [comment]
Fair enough!

ComicInfo.xml files don't have a <Description> tag - they have a <Summary> tag.
So on import, CX would need to read the <Summary> tag, and map it to the DESCRIPTION field in the COMICS table.

But when CX has the functionality to write complete ComicInfo.xml tags - what tag will be used for the description / summary information?

Additionally, if a xml file contains a <Description> tag, CX ignores it anyway.

**Comment by mcpierce** [comment]
@bareheiny I think the problem in your comment is that you're putting a tag in the text which the browser is trying to render rather than show a text. Please drop the greater-than/less-than symbol or something so they show up properly.

**Comment by bareheiny** [comment]
Of ffs...sorry, I didn't read my original comment properly, so failed to notice the tags weren't showing up.

Right, so ComicInfo files have a Summary tag that contains the ComicVine description info.  When importing a comic that has a pre-existing xml file, the Summary information is being imported into the SUMMARY field.  With the removal of the SUMMARY field, I'm going to assume that CX will parse the Summary tag, and populate the DESCRIPTION field.

When scraping CV, CX populates the DESCRIPTION field in the database.

When CX has the functionality to generate complete xml files, will it generate a Summary or Description tag?  I ask as CX currently doesn't accept a Description tag....

**Comment by mcpierce** [comment]
@bareheiny  I'm closing this ticket since we're preparing for the 0.8 release. If there are still issues surrounding scraping after that release is made, please open a new ticket.
