### ISSUE TITLE
When importing comics, the "Path to comics..." field is not being populated with the previously used value

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#566]
When importing comics, the "Path to comics..." field is not being populated with the previously used value.

Steps to replicate:

1. Navigate to the Import page
2. Enter the "Path to comics..." 
3. Scan for, and select, a comic or comics to import
4. Import the comics (with or without metadata)
5. Once the import has completed, navigate to another page (build details for example)
6. Navigate to the Import page
7. Note that the "Path to comics..." value used earlier has not been retained

Edge Chromium, Windows Pro 64bit.

Source Branch | 8dda5b0baccc7661921006e654ff78d96bdf4c00
-- | --
Build Hostname | fv-az176-875
Built On | Dec 19, 2020, 1:40:36 PM
Version | 0.7.1-2
Commit Hash | 8dda5b0baccc7661921006e654ff78d96bdf4c00
Committer Name | Darryl L. Pierce ()
Time Of Last Commit | Dec 18, 2020, 10:29:25 PM
Commit Message | Changed the release version to 0.7.1-2 [#496]
Built From Uncommitted Code? | false
Remote Origin |  
JDBC Connection URL | jdbc:h2:D:\Comics\.comixedDB\comixed

**Comment by mcpierce** [comment]
@bareheiny With 0.8 is this still an issue, or can we close this as fixed?

**Comment by bareheiny** [comment]
Closing as fixed in 0.8.
