### ISSUE TITLE
Will the dockerhub account change to comixed/comixed?

### ISSUE THREAD

**Issue by PiDockMedia** [comixed/comixed#59]
To be consistent with the github change? Also, is there a forum where it is easier to ask questions or should I just keep opening issues?

**Comment by mcpierce** [comment]
I suppose we could open a Docker Hub for the project.

For questions and discussions, I've opened the two maiing lists (comixed@freelists.org and comixed-dev@freelists.org) for these sorts of questions and discussions.

**Comment by PiDockMedia** [comment]
I feel a unified comixed/comixed for dockerhub would be less confusing.

**Comment by mcpierce** [comment]
I tried creating a new one named comixed/comixed but it got rejected. I think we'd have to create a new Docker account to create one, unless there's some other method to create a new hub account. Any ideas?

**Comment by PiDockMedia** [comment]
I think you need a comixed docker account to create a comixed/comixed repository. You can also stick with mcpierce/comixed. I’ll likely update the image this weekend regardless.

**Comment by mcpierce** [comment]
I created the organization this morning, and invited you to be a member of it. 

https://hub.docker.com/orgs/comixed

**Comment by PiDockMedia** [comment]
The binary releases all seem to have disappeared. I was pulling this url:

https://api.github.com/repos/comixed/comixed/releases/latest

Parsing the path of the zip file, downloading the zip file, then loading up the .jer from the zip. The releases all seem to be tarballs and zipballs of source files with no binaries now.

**Comment by mcpierce** [comment]
@PiDockMedia I didn't push anything to the hub, I only created the repository.

The automated releases are now done using Github Actions, which have the zip file:

<img width="519" alt="Screen Shot 2019-12-03 at 8 56 36 AM" src="https://user-images.githubusercontent.com/61601/70057312-eb07c500-15aa-11ea-88c0-91c6a2b2ff4a.png">

The releases are available at a link like this:

https://github.com/comixed/comixed/archive/v0.5.0-PRERELEASE-20191201155851.zip

**Comment by bareheiny** [comment]
The zip (and I assume .gz) file doesn't contain the compiled .jar files...

![CX content](https://user-images.githubusercontent.com/1912425/70106566-df022d00-16a8-11ea-85f1-8d223fcc83e2.PNG)

**Comment by PiDockMedia** [comment]
It has changed as before I could pull the latest release with the url above and the following line could be parsed to get the link.

browser_download_url | "https://github.com/comixed/comixed/releases/download/0.4.9-SNAPSHOT-20191123165510/comixed-app-0.4.9-SNAPSHOT-20191123165424.zip"
-- | --

It still responds but with an older version that was deleted. I am not saying I can't work with it and grab/hardcode the link every time.  But as bareheiny says the zip and tgz files don't seem to have anything but source.

**Comment by mcpierce** [comment]
@PiDockMedia @bareheiny I see what you're saying. Crap, I didn't realize that zip file *wasn't* the binary artifact being created by the build. I'm going to fix that straight away. So sorry for the error.

**Comment by mcpierce** [comment]
@PiDockMedia I believe this is now fixed. Can you check the releases and see if there's a proper ZIP file available? If so, please feel free to close this ticket. And thanks for finding that issue.

**Comment by PiDockMedia** [comment]
I do see a zip file. In the dockerhub team I believe you need to create a repository and give me permissions to be able to push to it. I joined the team but there is no repository to be pushed to. Alternatively you can give me permissions to create repositories and I'll handle it. I think if I have Public create privs it will work. https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization

**Comment by mcpierce** [comment]
Okay, repository is created and members have read/write permission to it on hub.docker.com.

**Comment by Dunuin** [comment]
I'm a little bit confused. What are finally the URLs and naming scemes so I can fetch and extract the latest JAR for my FreeBSD update script?

Should I use "https://github.com/comixed/comixed/" or "https://github.com/mcpierce/comixed/"?

And are tag names and release file names now finally for the develop branch?

Timestamp: "[X].[Y].[Z]-PRERELEASE-YYYYMMDDHHMMSS"
Asset: "comixed-app-[X].[Y].[Z]-PRERELEASE-[TIMESTAMP].zip"

Whats about the RC and stable/master tag names and asset file names?

**Comment by mcpierce** [comment]
@Dunuin Use the http://git.com/comixed/comixed releases for Docker. The other one's now just for me to do my development.

We're going to follow [semantic versioning](https://semver.org/) standards for tagging on develop, release/* and master.

When a feature's merged into the develop branch, we've got a Github action that automatically tags it with:

```$MAJOR.$MINOR.$PATH-PRERELEASE-$BUILDDATE```

When the release candidates start getting pushed out, I'll create a release branch named:

```release/$MAJOR.$MINOR```

Bug fixes, etc. will get cherry-picked onto it as. When we have a release candidate, I'll tag that with:

```$MAJOR.$MINOR.$PATCH-RC$BUILDNUMBER```

When we have a stable release, that'll get tagged with:

```$MAJOR.$MINOR.$PATCH```

and be merged into master.

**Comment by PiDockMedia** [comment]
Alright, the latest 5.0 pre-release is dockerized and up as a versioned prerelease, the release, and the latest images. The original issue is done so I am going to close this.
