### ISSUE TITLE
Deploy the release artifacts

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#60]
I can't seem to locate anything other than zipped source code.

Unfortunately attempting to clone and build on my machine is failing now as well...and I'm not overly inclined to go down that rabbit hole.

**Comment by mcpierce** [comment]
We're fixing the CI environment now that things are moved. Travis stopped working (again) on us. The code itself should build just the same (nothing's changed on that level), but we'll get it posting again this weekend.

**Comment by mcpierce** [comment]
Also, questions like this would be perfect for the user mailing list rather than in issues.

**Comment by mcpierce** [comment]
Issues are now being deployed again here on the shared project.

**Comment by mcpierce** [comment]
This is the logfile when attempting to deploy the project.

[deploy.log](https://github.com/comixed/comixed/files/5378825/deploy.log)

**Comment by mcpierce** [comment]
@bareheiny Closing this ticket as outdated.
