### ISSUE TITLE
HELP HOW OPDS

### ISSUE THREAD

**Issue by gibbe211** [comixed/comixed#616]
**NOTE: If this involves a pre-release version of ComiXed and not a release, then please send an email to the mailing list rather than creating an issue here. All such bug reports will be closed.**
Hi I just downloaded the latest master version but how does one connect a opds reading app for example chunky 

Is it just the device ip/opds cause im not able to connect to server so for sure im doing something wrong 

if any could help me setting up opds would be more than happy 

 - Latest master version
 - Ios Unsinn Chucky or planels

**Comment by mcpierce** [comment]
@gibbe211 Good question!

The answer is in our QUICKSTART.md file. What you'll do is add a new server in Chunky (that's what I use) and use:

> **Hostname:** http://$IPADDRESS:7171/opds-comics
> **Username:** [the username for your login]
> **Password:** [the password for your login]

Then you should be able to navigate your library.

If that answers your question, please feel free to close this ticket. For any other questions on using the app, please consider subscribing to the [mailing list](https://www.freelists.org/list/comixed).

**Comment by mcpierce** [comment]
Closing this ticket, since it's neither a bug not a feature request. Please join the mailing list for any further questions.
