### ISSUE TITLE
Docker Compose issue

### ISSUE THREAD

**Issue by mjd515** [comixed/comixed#66]
Hey there i managed to get Comixed working in docker compose, the issue i have is when reverse proxy with traefik it send me to an error page saying user not found. if i point to the IP and port url i get the home screen and can get in. any idea what i should use to fix this?

so i killed the container and reloaded and it worked idk what i did to make it work but im in now.

**Comment by mcpierce** [comment]
@mjd515 Were you able to fix the issue? Is it something we should track?

**Comment by mjd515** [comment]
i think it had to do with when i set up the container i used the builtin password function with Treafik and it messed with the user login for the program after i took it out and rebuilt the container it worked no prob.
