### ISSUE TITLE
Webpage Login Details

### ISSUE THREAD

**Issue by ajhorvath20** [comixed/comixed#694]
Hi, when I visit the page `192.168.1.138:7171` I get this screen
![image](https://user-images.githubusercontent.com/65309559/113662764-a7423580-96a0-11eb-9ea6-2f9aaa43e367.png)]

But I don't see what to put it in there
![image](https://user-images.githubusercontent.com/65309559/113662803-b88b4200-96a0-11eb-83c0-bd1b8a1986d1.png)

I am definitely missing something.

Thanks

**Comment by mcpierce** [comment]
@ajhorvath20 There are very good questions for the [user list](https://www.freelists.org/list/comixed). The answers you're looking for can be found in the [Quickstart Guide](https://github.com/comixed/comixed/blob/develop/QUICKSTART.md).

If that helps, please feel free to close this ticket.

**Comment by ajhorvath20** [comment]
> @ajhorvath20 There are very good questions for the [user list](https://www.freelists.org/list/comixed). The answers you're looking for can be found in the [Quickstart Guide](https://github.com/comixed/comixed/blob/develop/QUICKSTART.md).
> 
> If that helps, please feel free to close this ticket.

Oops sorry I looked everywhere but definitely not properly. Thank you so much

**Comment by mcpierce** [comment]
@ajhorvath20 My pleasure.
