### ISSUE TITLE
Library deleted after update to 8.0.2 on docker 

### ISSUE THREAD

**Issue by oscruise** [comixed/comixed#700]
After migrating from 7.1.1 to latest, my library disapeared and I’m not able to config users or languague anymore, using docker container in a SynologyDSM918. Maybe needs to point a config folder outside the container to avoid this? As the comic_data does.

**Comment by mcpierce** [comment]
@oscruise Can you tell me how you setup the Docker image? The H2 database used by default isn't inside of the Docker container but is external. In the Docker README.md file it says to use the following command line:

```
docker run -it -p 7171:7171/tcp -v /PATH/TO/COMICS:/comic_dir -v /PATH/TO/COMIXDB:/root/.comixed comixed/comixed:latest
```

So your database should be in whatever directory you specified.

**Comment by oscruise** [comment]
Yes, that was it.... missed to map comixdb... I just saw the read me for docker.
However, maybe some other config can also be mapped outside, to keep it after updates, such as users or plug ins.
Thanks a lot, love the project!

**Comment by mcpierce** [comment]
@oscruise The directory that contains the database should also contain the plugins, image cache, etc. Also, users are stored in the database, so they'll be protected as well. Sorry if there was some confusion with the documentation.

And thanks for the positive feedback. 😄 

If you're good with things, please feel free to close this ticket.
