### ISSUE TITLE
[BUG] No Account link visible at top of library page

### ISSUE THREAD

**Issue by scampsi** [comixed/comixed#709]
The QUICKSTART.md file contains instructions for how to change the default account passwords.  And includes a screenshot of the expected links at the top of the library page including the account link.  On a new install (Windows 10 Professional 64-bit) the account link (and everything apart from a logout icon) is missing when compared to the quickstart screenshot.

Steps to repro:
1. Install from release build windows installer
2. Run from cmd with "java -jar <path-to-jar-file>"
3. Navigate to http://localhost:7171 in Firefox, Chrome, or Edge
4. Login using either the admin or reader credentials from the quickstart

![Comixed Links Missing](https://user-images.githubusercontent.com/5270438/114870442-167dff00-9df0-11eb-8cff-222bab94d0f6.png)

 - ComiXed version: 0.8.0-2.0
 - OS: Win 10 64-bit (OS Build 19041.928)
 - Firefox 87.0 64-bit (also repros on Chrome 90.0.4430.72 64-bit and Edge 89.0.774.77 64-bit)

Build Details
The code was build from a branch named 34eba1a5fc52142e14fa3a636fd91bba9cfb3538
The code was built on April 7, 2021 at 12:26:48 AM GMT+1.
Code was built on a machine named fv-az206-236.
The code was marked with a Build version of 0.8.0-2.0.
The latest commit hash on the source branch is 34eba1a5fc52142e14fa3a636fd91bba9cfb3538.
This commit was created on April 7, 2021 at 12:05:16 AM GMT+1.
Commit Message
Changed the release version to 0.8.0-2.0 [#605]
Commit was created by Darryl L. Pierce <mcpierce@gmail.com>
The branch does not contain uncommitted changes.
This branch is tracking the remote branch https://github.com/comixed/comixed
The database URL being used is jdbc:h2:file:~/.comixed/comixed;create=true

**Comment by mcpierce** [comment]
@scampsi Thanks for bringing this to my attention. In switching from the old UI to the new one the account update page isn't accessible. I'll fix this and put up a new build within a few days.

**Comment by mcpierce** [comment]
@scampsi I've updated things to include the new edit account page and have generated a new build from it: [v0.8.1-1.0](https://github.com/comixed/comixed/releases/tag/v0.8.1-1.0)

If this adds the functionality you're looking for, please close this ticket as fixed. And thank you!

**Comment by scampsi** [comment]
@mcpierce Thanks for the quick response.

It's fixed in v0.8.1-1.0 for the admin account but still broken for the reader account.  Is that expected?

**Comment by mcpierce** [comment]
@scampsi No, it ought to work for any logged in account. What behavior are you seeing for the non-admin account?

(edit)

Ah, I see, it was the issue. I've fixed it and verified it should work for both reader and admin accounts now. Sorry for that. The fix is now in [0.8.1-1.1](https://github.com/comixed/comixed/releases/tag/v0.8.1-1.1). Same as before, if this fixes things, please feel free to close this ticket.

**Comment by scampsi** [comment]
@mcpierce The text "Logged in: comixedreader@localhost" is a valid hyperlink to the /account page.  The first time I click it after loading/refreshing the /library page I get the following:
<img width="1262" alt="Comixed non-admin console" src="https://user-images.githubusercontent.com/5270438/115126371-6f06f500-9fc6-11eb-8527-ed03c4fff95f.png">

And I end up back at the /library page.

If I manually paste "localhost:7171/account" in the address bar I see the same behaviour.

(edit)
Just saw your edit.  Thanks.  I'll check the new build once the artifacts are available.

**Comment by scampsi** [comment]
Closed fixed.  Thanks.
