### ISSUE TITLE
realpath is not available on stock Mac OS.

### ISSUE THREAD

**Issue by SinisterStairs** [comixed/comixed#747]
**Describe The Bug**
macOS cannot run the release's `run.sh` as-is because `realpath` doesn't exist.  (I've tested on 10.14 (Mojave) and 11.4 (Big Sur))

**To Reproduce The Bug**
To fix the problem with Mojave, I installed GNU `readlink`.

Using Homebrew I did `brew install coreutils`.  Personally, I `cp /usr/local/bin/readlink $HOME/bin/` then uninstalled coreutils.

Then I edited  `run.sh` and changed the references of `realpath -s` to `readlink -c`

I'm not sure if this is so much a bug w/ workaround, or some helpful information to document.  Note:  I verified that the release's `run.sh` doesn't work in either Mojave or Big Sur, but my workaround is specifically for Mojave.

Big Sur does have readlink already installed, but it is not GNU's.  Installing GNU readlink in addition to macOS's could have side effects, although by default Homebrew will install to /opt/Homebrew/bin and not override the OS.  But the user's PATH will need to have Homebrew over /usr/bin

**Comment by mcpierce** [comment]
@SinisterStairs Thanks for bringing this to our attention!

I think I've found a reasonable workaround for requiring users to install Homebrew and coreutils, and would appreciate if you could take a look and see if it works for you. If so, I'll add it to the code and push an update.

(edit)

[Here](https://github.com/comixed/comixed/pull/748) is the link to the PR. If you could provide feedback on the solution I'll merge it and put out a new 0.8 release with it.

**Comment by SinisterStairs** [comment]
Well duh!  I should have thought of that myself!  Perfect solution!  (I already had readlink installed for other reasons, so I was looking at it with a blindspot of what was "needed.")

This works on my personal Macbook Pro (Mojave), but not my work Mac (Big Sur).  I'll provide details in the PR.

**Comment by mcpierce** [comment]
@SinisterStairs When you're happy with the resolution, please feel free to close this ticket.

**Comment by SinisterStairs** [comment]
Orirginal problem fixed, thanks!

Note to self: A corner case (for all *nix) exists when the filepath contains special characters, such as spaces.

EDIT: Fixed in pull request #758
