### ISSUE TITLE
[BUG] Add support for Mac OS Big Sur

### ISSUE THREAD

**Issue by rohan-gt** [comixed/comixed#767]
The JAR file doesn't open on Mac OS Big Sur so please consider making a Mac App for ComiXed

**Comment by mcpierce** [comment]
@rohan-gt Can you please provide more details?

**Comment by rohan-gt** [comment]
I downloaded the latest release zip and tried opening the .jar file but nothing opens up so I'm guessing there's a Java issue with Big Sur. If I'm doing something wrong could you add installation instructions for Mac OS in the Readme?

**Comment by mcpierce** [comment]
@rohan-gt Can you give the exact command lines you're using, please? Which release file is it you're trying open?

The release artifacts are zip files that contains the following files:

```
mcpierce@mcpiercemini ~/Downloads $ unzip -l comixed-release-0.8.2-1.2-RELEASE.zip
Archive:  comixed-release-0.8.2-1.2-RELEASE.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  06-09-2021 12:42   comixed-release-0.8.2-1.2/
        0  06-09-2021 12:42   comixed-release-0.8.2-1.2/bin/
        0  06-09-2021 12:42   comixed-release-0.8.2-1.2/lib/
     5631  06-09-2021 12:31   comixed-release-0.8.2-1.2/README.md
      268  06-09-2021 12:31   comixed-release-0.8.2-1.2/CHANGELOG.md
      425  06-09-2021 12:31   comixed-release-0.8.2-1.2/CONTRIBUTORS.md
     9084  06-09-2021 12:31   comixed-release-0.8.2-1.2/QUICKSTART.md
    35141  06-09-2021 12:31   comixed-release-0.8.2-1.2/LICENSE
     3340  06-09-2021 12:31   comixed-release-0.8.2-1.2/bin/run.bat
     2969  06-09-2021 12:31   comixed-release-0.8.2-1.2/bin/run.sh
308014023  06-09-2021 12:42   comixed-release-0.8.2-1.2/bin/comixed-app-0.8.2-1.2.jar
---------                     -------
308070881                     11 files
```

Are you saying you can't open the file **comixed-release-0.8.2-1.2-RELEASE.zip** (or one of the other releases)? Or are you saying you can't open the **comixed-app-*.jar** file contained in the release?

As for starting the app, the QUICKSTART.md file contains steps for launching the app.

**Comment by rohan-gt** [comment]
I can't open the comixed-app-*.jar file through terminal or by double clicking

**Comment by mcpierce** [comment]
@rohan-gt What is the command line you're using? What are you typing and what is the output you're seeing? Can you please cut and paste the output, including your command line, from where you tried to view the contents? Which release of ComiXed did you download? And, what version of Java are you using?
