### ISSUE TITLE
Exclude comics from scraping, and "unscraped" lists.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#77]
As a user, I would like to be able to flag a comic to exclude it from scraping requests, and appearing on any list of un-scrapped lists.

I can see a couple of use cases for this:

1.  A specific series / issue does not appear in the ComicVine database.  For example, for the longest time the three issue mini-series "Automaton" was not in the CV database.  I had to manually load the metadata.

2.  I consolodate a number of issues into a new file (see my recent merge request).  This merged comic would not appear in the CV database.

In these cases, I would not want these files included in any list of comics to be scraped, or an any bulk scraping exercise.

**Comment by mcpierce** [comment]
So this would be a flag on the comic in the library that marks it as never to be scraped? I would lean more towards the library owner taking responsibility for not trying to scrape issues like that. Or, if they accidentally include it in a scraping exercise, clicking the **Skip** button (we had a ticket for this feature on the old repo but I don't think I copied it over to here) to just bypass that comic.

**Comment by bareheiny** [comment]
Yes - I was thinking of some sort of flag.

I can see it being very useful when doing something like a full library scrape - especially if there's automatic matching involved (say via a pre-existing CV id or smart title matching).

**Comment by mcpierce** [comment]
@bareheiny Okay, in that light I can see a definite use for such a flag.

**Comment by mcpierce** [comment]
@bareheiny I'm going to close this feature request, if you don't mind, since scraping is an opt-in process.
