### ISSUE TITLE
Maintain a list of blocked / blacklisted pages

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#78]
As a user, I would like to maintain a list of blocked or blacklisted pages.

These would (most likely) be pages that frequently appear - such as scanner tags.  Even if the page has been deleted from a comic file, the hash should be retained for use in flagging the same page in comic files that are added to the library at a later date.

**Comment by mcpierce** [comment]
We have this feature currently, being able to mark a page as blocked.

<img width="686" alt="Screen Shot 2019-12-01 at 1 22 15 PM" src="https://user-images.githubusercontent.com/61601/69918229-a579b980-143d-11ea-9a62-f6c7c7a816d2.png">

Right now you can go to a comic, find such a page, and mark it as blocked. That stores the hash for that image file in the **blocked_page_hashes** table. When you import comics, you can tell it to mark blocked pages as delete. Then, when the library consolidation ticket (#20) is implemented, pages that are marked as deleted will get removed from the comics.

Does this match what you're wanting to see?

**Comment by bareheiny** [comment]
Well now...that's exactly what I was wanting.  And here I was thinking I was being smart and coming up with a new feature >_<

Out of curiosity, when the page is deleted, will the hash remain in the blocked_page_hashes table?

**Comment by mcpierce** [comment]
@bareheiny Yes, the hashes are kept.

**Comment by bareheiny** [comment]
Magic.  Closing this request then.
