### ISSUE TITLE
Meta not saving/fetching

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - ComiXed version [from **Help** -> **Build Details**]
 - Browser name [e.g. chrome, safari]
 - Browser version [e.g. 22]

** ComiXed Build Detail **
Copy and past the details from **Help** -> **Build Details**

**Additional context**

**Comment by bareheiny** [comment]
o.O 

This is a weird bug report!  Also, I can't say I've seen any issues with saving scrapped metadata.

**Comment by mcpierce** [comment]
@bareheiny Can you edit the issue, please?

**Comment by bareheiny** [comment]
@mcpierce, for sure I can edit my comment...but not your issue report.

**Comment by mcpierce** [comment]
@bareheiny No, I mean the original post that's just the template without any information. Or if you can't edit it, please close this and open a proper one? Thank

**Comment by bareheiny** [comment]
My first comment was being somewhat facetious.

My second one not so much...you may want to check who opened the bug 😛

**Comment by mcpierce** [comment]
@bareheiny LOL! OMG, I thought you opened this! I opened this back in the fall? I don't even remember... 😄 Closing this now.
