### ISSUE TITLE
Unable to scrape comic information for some comics from library.

### ISSUE THREAD

**Issue by CountZeroOr** [comixed/comixed#850]
**Describe The Bug**
Unable to scrape comic information for some comics from library.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Selected 3 issues of Dengeki G's
2. Select the button to scrape that comic.
3. Confirmed ComicVine API information was present
4. Confirmed magazine name, number
5. Pressed scrape button
6. Selected issue off of list of options.
1. See error

**Expected Behavior**
I expected it to pop up the relevant issue on the other side of the screen and give a thumbs up or thumbs down for that issue, information.

**Screenshots**
![Screenshot 2021-08-19 192215](https://user-images.githubusercontent.com/42648006/130169167-23db88dc-26a7-40c6-94ce-ceab4f65b86c.png)

**Desktop (please complete the following information):**
 - ComiXed version 0.9.0-3.0.
 - OS: Windows 10
 - Browser name: Chrome
 - Browser version Version 92.0.4515.159 (Official Build) (64-bit)

**ComiXed Build Detail:**
Copy and past the details from **Build Details** menu option.

**Additional Context**
Error message from CMD Prompt log window:
2021-08-19 19:19:08.136  WARN 14408 --- [io-7171-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]

**Comment by mcpierce** [comment]
@CountZeroOr Can you provide the series name, volume and issue number for the issue(s) you were trying to scrape?

**Comment by CountZeroOr** [comment]
Dengeki G's Magazine #22. Volume would probably be (going by the year) 1999. The files in question are also CBR files, which may be part of the problem.

**Comment by mcpierce** [comment]
@CountZeroOr Are you able to find the issue on ComicVine's website? Can you post the link here? I'm testing the scraping here but can't be sure what is the right answer. I'm able to load some issues, but I don't know which is correct.

**Comment by CountZeroOr** [comment]
I did some further checking, and I can't find the correct issue either.

I converted over most of my library to CBZ, so what I'm going to try to do is clear and re-scan the library with the CBZ files and see if the issue is fixed.

**Comment by mcpierce** [comment]
@CountZeroOr Since this wasn't a bug but a lack of an entry at ComicVine, would you mind closing this issue, please?

**Comment by mcpierce** [comment]
Closing as a not  bug.
