### ISSUE TITLE
Setup Guide - OPDS - YACReader or Chunky

### ISSUE THREAD

**Issue by b101marc** [comixed/comixed#867]
Hi all,

Pretty new to setting this up. Running Comixed via docker behind traffic and could use some support in getting comixed working with a reader. Is there a guide I perhaps missed? Thanks in advance for any support.

**Comment by mcpierce** [comment]
@b101marc This is a great question for the user [mailing list](https://www.freelists.org/list/comixed). Please feel free to ask it over there.
