### ISSUE TITLE
Test Report bmfrosty 2021-09-25

### ISSUE THREAD

**Issue by bmfrosty** [comixed/comixed#969]
Testing based on https://www.reddit.com/r/comicrackusers/comments/p7df2h/anyone_ever_thought_of_a_kickstarter_campaign_to/he83mnn/?context=3

Using the version recommended there.  Was able to get it to start with `bash run.sh.  First try seemed to set up the database and I could log in to the web interface with both included accounts. 

Was unable to configure the library.  Put the path in the field, but could not save.  The save button was greyed out.

did a CTRL-C out and restarted the script.  

Seemed the same, but then I added a comicvine API key.  Then the save button was usable. I used it.   No library files.  No indication that it was trying to import them.

did a CTRL-C out and restarted the script.  

Same thing.  I'm putting this aside for the day.

Here are the outputs from each run:

https://pastebin.com/raw/6YjRzpfY

https://pastebin.com/raw/AD1fDKnz

https://pastebin.com/raw/LGC1TxbZ

```
bmfrosty@vac:~/comixed-release-0.10.0-1.0/bin$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)
bmfrosty@vac:~/comixed-release-0.10.0-1.0/bin$ 
```

```
bmfrosty@vac:~/comixed-release-0.10.0-1.0/bin$ neofetch
             /////////////                bmfrosty@vac 
         /////////////////////            ------------ 
      ///////*767////////////////         OS: Pop!_OS 21.04 x86_64 
    //////7676767676*//////////////       Host: Lemur Pro lemp9 
   /////76767//7676767//////////////      Kernel: 5.11.0-7620-generic 
  /////767676///*76767///////////////     Uptime: 1 hour, 32 mins 
 ///////767676///76767.///7676*///////    Packages: 2548 (dpkg), 36 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.4 
//////////76767676767////76767/////////   Resolution: 3840x2160 
///////////76767676//////7676//////////   DE: GNOME 3.38.4 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop-dark 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Adwaita [GTK2/3] 
  //////////////////////'////////////     Terminal: terminator 
   //////.7676767676767676767,//////      CPU: Intel i5-10210U (8) @ 4.200GHz 
    /////767676767676767676767/////       GPU: Intel CometLake-U GT2 [UHD Graphics] 
      ///////////////////////////         Memory: 8089MiB / 23916MiB 
         /////////////////////
             /////////////                                        


bmfrosty@vac:~/comixed-release-0.10.0-1.0/bin$ 
```

**Comment by mcpierce** [comment]
@bmfrosty Thank you for this.

Comics have to be deliberately imported into the library, CX doesn't add items by default. To perform an import, you click on the Import Comics option in the sidebar, then enter a directory to search, and then select specific comics to be imported. The import process then extracts all the details out of the comics and puts them into the database.

Could you please share this on [the user list](https://www.freelists.org/list/comixed)? This looks like a great jumping off point to discuss how to improve this process and make it more intuitive.

**Comment by bmfrosty** [comment]
That doesn't work.  Was just hoping to give you some test data.  I'll maybe give it another try once it's matured a bit.

**Comment by mcpierce** [comment]
Sorry, I'm not sure I understand what doesn't work. Or do you mean it's not the expected or desired behavior? I appreciate your feedback.

**Comment by bmfrosty** [comment]
Also going to put out there that I also gave it a try with your docker container, but it's a couple of major versions out of date.

**Comment by mcpierce** [comment]
Ah, okay, if it was the docker hub then that's for the previous version. I would recommend trying the release candidate here. Since Docker changed their policies regarding automated builds, it's fallen behind development.
