### ISSUE TITLE
Allow longer passwords

### ISSUE THREAD

**Issue by SaraSmiseth** [comixed/comixed#975]
**Is your feature request related to a problem? Please describe.**

I was frustrated when I tried to change my password. It was very hard to figure out why I was not able to change it. By trial and error I found that the max length for the password is 16 characters. I used a password manager to generate my passwords and started with a 128 character long password.

**Describe the solution you'd like**

Allow at least 128 character long passwords.

**Describe alternatives you've considered**

Show a hint why you can not save the current changes made on the account page. For example: Show a hint that the password has to be between 8 to 16 characters long.

**Comment by mcpierce** [comment]
@SaraSmiseth Thanks for this. I'll add this to the set of enhancements for the next release.

**Comment by mcpierce** [comment]
@SaraSmiseth This will be in the next release.
