### ISSUE TITLE
Generate an MD5 sum for build artifacts and post it as a download artifact.

### ISSUE THREAD

**Issue by Dunuin** [comixed/comixed#98]
Is it possible to create a checksum of the zip file in the build process and place it next to the zip, so scripts can verify that the file was downloaded without errors?

Not super important but that would be a nice feature.

**Comment by mcpierce** [comment]
@Dunuin Anything's possible. :D I'll dig around and see if there's a Github Action already built do do it and, if not, I'll write one soon to provide a MD5 for the zip artifact.
